# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_foreach_multiblock_bilinear_interp_7x7_u8
TEST_BENCH = $(FILE)_tb
CFILES = ../src_C/$(FILE)_cn.c $(FILE)_config.c ../src_kernelC/$(FILE)_host.c
HOST_EXE_FILE_NAME = $(TEST_BENCH).exe
include ../../../common/Makefile.wincommon
