/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-A71
 */

#ifndef ti_sysbios_family_c674_Power__INTERNAL__
#define ti_sysbios_family_c674_Power__INTERNAL__

#ifndef ti_sysbios_family_c674_Power__internalaccess
#define ti_sysbios_family_c674_Power__internalaccess
#endif

#include <ti/sysbios/family/c674/Power.h>

#undef xdc_FILE__
#ifndef xdc_FILE
#define xdc_FILE__ NULL
#else
#define xdc_FILE__ xdc_FILE
#endif

/* changeSetpoint */
#undef ti_sysbios_family_c674_Power_changeSetpoint
#define ti_sysbios_family_c674_Power_changeSetpoint ti_sysbios_family_c674_Power_changeSetpoint__E

/* configure */
#undef ti_sysbios_family_c674_Power_configure
#define ti_sysbios_family_c674_Power_configure ti_sysbios_family_c674_Power_configure__E

/* getCapabilities */
#undef ti_sysbios_family_c674_Power_getCapabilities
#define ti_sysbios_family_c674_Power_getCapabilities ti_sysbios_family_c674_Power_getCapabilities__E

/* getConstraintInfo */
#undef ti_sysbios_family_c674_Power_getConstraintInfo
#define ti_sysbios_family_c674_Power_getConstraintInfo ti_sysbios_family_c674_Power_getConstraintInfo__E

/* getCurrentSetpoint */
#undef ti_sysbios_family_c674_Power_getCurrentSetpoint
#define ti_sysbios_family_c674_Power_getCurrentSetpoint ti_sysbios_family_c674_Power_getCurrentSetpoint__E

/* getDependencyCount */
#undef ti_sysbios_family_c674_Power_getDependencyCount
#define ti_sysbios_family_c674_Power_getDependencyCount ti_sysbios_family_c674_Power_getDependencyCount__E

/* getNumSetpoints */
#undef ti_sysbios_family_c674_Power_getNumSetpoints
#define ti_sysbios_family_c674_Power_getNumSetpoints ti_sysbios_family_c674_Power_getNumSetpoints__E

/* getSetpointInfo */
#undef ti_sysbios_family_c674_Power_getSetpointInfo
#define ti_sysbios_family_c674_Power_getSetpointInfo ti_sysbios_family_c674_Power_getSetpointInfo__E

/* getTransitionLatency */
#undef ti_sysbios_family_c674_Power_getTransitionLatency
#define ti_sysbios_family_c674_Power_getTransitionLatency ti_sysbios_family_c674_Power_getTransitionLatency__E

/* registerConstraint */
#undef ti_sysbios_family_c674_Power_registerConstraint
#define ti_sysbios_family_c674_Power_registerConstraint ti_sysbios_family_c674_Power_registerConstraint__E

/* registerNotify */
#undef ti_sysbios_family_c674_Power_registerNotify
#define ti_sysbios_family_c674_Power_registerNotify ti_sysbios_family_c674_Power_registerNotify__E

/* releaseDependency */
#undef ti_sysbios_family_c674_Power_releaseDependency
#define ti_sysbios_family_c674_Power_releaseDependency ti_sysbios_family_c674_Power_releaseDependency__E

/* setDependency */
#undef ti_sysbios_family_c674_Power_setDependency
#define ti_sysbios_family_c674_Power_setDependency ti_sysbios_family_c674_Power_setDependency__E

/* signalEvent */
#undef ti_sysbios_family_c674_Power_signalEvent
#define ti_sysbios_family_c674_Power_signalEvent ti_sysbios_family_c674_Power_signalEvent__E

/* sleepDSP */
#undef ti_sysbios_family_c674_Power_sleepDSP
#define ti_sysbios_family_c674_Power_sleepDSP ti_sysbios_family_c674_Power_sleepDSP__E

/* unregisterConstraint */
#undef ti_sysbios_family_c674_Power_unregisterConstraint
#define ti_sysbios_family_c674_Power_unregisterConstraint ti_sysbios_family_c674_Power_unregisterConstraint__E

/* unregisterNotify */
#undef ti_sysbios_family_c674_Power_unregisterNotify
#define ti_sysbios_family_c674_Power_unregisterNotify ti_sysbios_family_c674_Power_unregisterNotify__E

/* delayCompletion0 */
#define Power_delayCompletion0 ti_sysbios_family_c674_Power_delayCompletion0__I

/* delayCompletion1 */
#define Power_delayCompletion1 ti_sysbios_family_c674_Power_delayCompletion1__I

/* delayCompletion2 */
#define Power_delayCompletion2 ti_sysbios_family_c674_Power_delayCompletion2__I

/* delayCompletion3 */
#define Power_delayCompletion3 ti_sysbios_family_c674_Power_delayCompletion3__I

/* delayCompletion4 */
#define Power_delayCompletion4 ti_sysbios_family_c674_Power_delayCompletion4__I

/* delayCompletion5 */
#define Power_delayCompletion5 ti_sysbios_family_c674_Power_delayCompletion5__I

/* delayCompletion6 */
#define Power_delayCompletion6 ti_sysbios_family_c674_Power_delayCompletion6__I

/* delayCompletion7 */
#define Power_delayCompletion7 ti_sysbios_family_c674_Power_delayCompletion7__I

/* delayCompletion8 */
#define Power_delayCompletion8 ti_sysbios_family_c674_Power_delayCompletion8__I

/* delayCompletion9 */
#define Power_delayCompletion9 ti_sysbios_family_c674_Power_delayCompletion9__I

/* idleStopClock */
#define Power_idleStopClock ti_sysbios_family_c674_Power_idleStopClock__I

/* init */
#define Power_init ti_sysbios_family_c674_Power_init__I

/* initRefCounts */
#define Power_initRefCounts ti_sysbios_family_c674_Power_initRefCounts__I

/* notify */
#define Power_notify ti_sysbios_family_c674_Power_notify__I

/* rebuildConstraint */
#define Power_rebuildConstraint ti_sysbios_family_c674_Power_rebuildConstraint__I

/* updateConstraints */
#define Power_updateConstraints ti_sysbios_family_c674_Power_updateConstraints__I

/* Module_startup */
#undef ti_sysbios_family_c674_Power_Module_startup
#define ti_sysbios_family_c674_Power_Module_startup ti_sysbios_family_c674_Power_Module_startup__E

/* Instance_init */
#undef ti_sysbios_family_c674_Power_Instance_init
#define ti_sysbios_family_c674_Power_Instance_init ti_sysbios_family_c674_Power_Instance_init__E

/* Instance_finalize */
#undef ti_sysbios_family_c674_Power_Instance_finalize
#define ti_sysbios_family_c674_Power_Instance_finalize ti_sysbios_family_c674_Power_Instance_finalize__E

/* module */
#define Power_module ((ti_sysbios_family_c674_Power_Module_State *)(xdc__MODOBJADDR__(ti_sysbios_family_c674_Power_Module__state__V)))
#if !defined(__cplusplus) || !defined(ti_sysbios_family_c674_Power__cplusplus)
#define module ((ti_sysbios_family_c674_Power_Module_State *)(xdc__MODOBJADDR__(ti_sysbios_family_c674_Power_Module__state__V)))
#endif
/* per-module runtime symbols */
#undef Module__MID
#define Module__MID ti_sysbios_family_c674_Power_Module__id__C
#undef Module__DGSINCL
#define Module__DGSINCL ti_sysbios_family_c674_Power_Module__diagsIncluded__C
#undef Module__DGSENAB
#define Module__DGSENAB ti_sysbios_family_c674_Power_Module__diagsEnabled__C
#undef Module__DGSMASK
#define Module__DGSMASK ti_sysbios_family_c674_Power_Module__diagsMask__C
#undef Module__LOGDEF
#define Module__LOGDEF ti_sysbios_family_c674_Power_Module__loggerDefined__C
#undef Module__LOGOBJ
#define Module__LOGOBJ ti_sysbios_family_c674_Power_Module__loggerObj__C
#undef Module__LOGFXN0
#define Module__LOGFXN0 ti_sysbios_family_c674_Power_Module__loggerFxn0__C
#undef Module__LOGFXN1
#define Module__LOGFXN1 ti_sysbios_family_c674_Power_Module__loggerFxn1__C
#undef Module__LOGFXN2
#define Module__LOGFXN2 ti_sysbios_family_c674_Power_Module__loggerFxn2__C
#undef Module__LOGFXN4
#define Module__LOGFXN4 ti_sysbios_family_c674_Power_Module__loggerFxn4__C
#undef Module__LOGFXN8
#define Module__LOGFXN8 ti_sysbios_family_c674_Power_Module__loggerFxn8__C
#undef Module__G_OBJ
#define Module__G_OBJ ti_sysbios_family_c674_Power_Module__gateObj__C
#undef Module__G_PRMS
#define Module__G_PRMS ti_sysbios_family_c674_Power_Module__gatePrms__C
#undef Module__GP_create
#define Module__GP_create ti_sysbios_family_c674_Power_Module_GateProxy_create
#undef Module__GP_delete
#define Module__GP_delete ti_sysbios_family_c674_Power_Module_GateProxy_delete
#undef Module__GP_enter
#define Module__GP_enter ti_sysbios_family_c674_Power_Module_GateProxy_enter
#undef Module__GP_leave
#define Module__GP_leave ti_sysbios_family_c674_Power_Module_GateProxy_leave
#undef Module__GP_query
#define Module__GP_query ti_sysbios_family_c674_Power_Module_GateProxy_query


#endif /* ti_sysbios_family_c674_Power__INTERNAL____ */
