# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = merge_sort
CFILES = ../src_kernelC/merge_sort_kernel_hard.c ../src_kernelC/merge_sort_init.c
NATURALC = ../src_C/vcop_sort_cn.c
TEST_BENCH = $(FILE)_tb
EVE_LCF = linker.cmd
include ../../../common/Makefile.wincommon
