# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_YCbCr444Deinterleave
TEST_BENCH = $(FILE)_tb
include ../../../common/Makefile.wincommon

