# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_yuv_420nv12_to_422uyvy
TEST_BENCH = $(FILE)_tb

include ../../../common/Makefile.wincommon
