# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_ncc
TEST_BENCH = $(FILE)_tb
CFILES =  ..\src_C\$(FILE)_cn.c ..\src_kernelC\init_slidingSum_params.c $(FILE)_config.c vcop_ncc_tb_utils.c input.c template.c output.c
EVE_LCF = linker_custom.cmd
include ../../../common/Makefile.wincommon
