# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_fast9
TEST_BENCH = $(FILE)_tb
KERNEL = ../src_kernelC/vcop_fast9_kernel
CFILES = ../src_C/$(FILE)_cn.c $(FILE)_config.c

include ../../../common/Makefile.wincommon
