/*
 *  Copyright (C) 2014 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 *  \file stw_dccTestcases.h
 *
 *  \brief This file defines the test cases for DCC UT.
 */

#ifndef STW_DCC_TEST_CASES_H_
#define STW_DCC_TEST_CASES_H_

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
#include <ti/csl/soc.h>
#include <ti/csl/cslr_dcc.h>
#include <ti/csl/soc.h>
#include <ti/csl/csl_dcc.h>
#include <st_dcc.h>

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */
#define DCC_NUM_TESTCASES               (sizeof (gDCCTestcaseParams) / sizeof (st_DCCTestcaseParams_t))

/*#define AVV_RUN_ALL                     (1U)*/
/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/** \brief Defines the various DCC test cases. */
st_DCCTestcaseParams_t gDCCTestcaseParams[] =
{
    /* enableTest, testCaseId,
     * *reqId,
     * *testCaseName,
     * *userInfo, *disableReason,
     * *pass/fail criteria,
     * cpuID, dataSize, sourceMemory,
     * dccConfigParams,
     * printEnable,
     * testType,
     */
    {
        TEST_ENABLE, 0U,
        "None",
        "User defined test",
        "None", "None",
        "None",
        IPU,
        {
            DCC_CLK_SRC0_SYS_CLK2,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DEF_DCC_CLK_SRC1,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        0U,
    },
    {
        TEST_ENABLE, 1U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_core_m2",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            DEF_DCC_MODULE,
            DEF_DCC_MODE,
            DCC_CLK_SRC0_SYS_CLK2,
            DCC_CLK_SRC1_DCC1_DPLLCORE_M2,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
#if !(defined (AVV_TEST_AUTO_BUILD))
#if defined (AVV_RUN_ALL)
    {
        TEST_ENABLE, 2U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_core_m3",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            DEF_DCC_MODULE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC1_DPLLCORE_M3,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 3U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_core_h11",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            DEF_DCC_MODULE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC1_DPLLCORE_H11,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 4U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_core_h12",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            DEF_DCC_MODULE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC1_DPLLCORE_H12,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 5U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_core_h13",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            DEF_DCC_MODULE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC1_DPLLCORE_H13,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 6U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_core_h14",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            DEF_DCC_MODULE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC1_DPLLCORE_H14,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 7U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_core_h21",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            DEF_DCC_MODULE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC1_DPLLCORE_H21,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 8U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_core_h22",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            DEF_DCC_MODULE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC1_DPLLCORE_H22,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 9U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_ddr_m2",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC2_BASE,
            DEF_DCC_MODE,
            DCC_CLK_SRC0_SYS_CLK2,
            DCC_CLK_SRC1_DCC2_DPLLDDR_M2,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_DISABLE, 10U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_ddr_m3",
        "None", "De-scoped",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC2_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC2_DPLLDDR_M3,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
#endif
#endif
    {
        TEST_ENABLE, 11U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_ddr_h11",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC2_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC2_DPLLDDR_H11,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
#if !(defined (AVV_TEST_AUTO_BUILD))
#if defined (AVV_RUN_ALL)
    {
        TEST_DISABLE, 12U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_ddr_h12",
        "None", "De-scoped",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC2_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC2_DPLLDDR_H12,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_NEGATIVE,
    },
    {
        TEST_DISABLE, 13U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_ddr_h13",
        "None", "De-scoped",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC2_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC2_DPLLDDR_H12,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_NEGATIVE,
    },
    {
        TEST_DISABLE, 14U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_ddr_h14",
        "None", "De-scoped",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC2_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC2_DPLLDDR_H12,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_NEGATIVE,
    },
    {
        TEST_ENABLE, 15U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_per_m2",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC3_BASE,
            DEF_DCC_MODE,
            DCC_CLK_SRC0_SYS_CLK2,
            DCC_CLK_SRC1_DCC3_DPLLPER_M2,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 16U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_per_m2x2",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC3_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC3_DPLLPER_M2x2,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_DISABLE, 17U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_per_m3",
        "None", "De-scoped",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC3_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC3_DPLLPER_M2x2,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_NEGATIVE,
    },
    {
        TEST_ENABLE, 18U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_per_h11",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC3_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC3_DPLLPER_H11,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            45U,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 19U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_per_h12",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC3_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC3_DPLLPER_H12,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
#endif
#endif
    {
        TEST_ENABLE, 20U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_per_h13",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC3_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC3_DPLLPER_H13,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
#if !(defined (AVV_TEST_AUTO_BUILD))
#if defined (AVV_RUN_ALL)
    {
        TEST_ENABLE, 21U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_per_h14",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC3_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC3_DPLLPER_H14,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 22U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_gmac_m2",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC4_BASE,
            DEF_DCC_MODE,
            DCC_CLK_SRC0_SYS_CLK2,
            DCC_CLK_SRC1_DCC4_DPLLDSP_GMAC_M2,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_DISABLE, 23U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_gmac_m2x2",
        "None", "De-scoped",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC4_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC4_DPLLDSP_GMAC_M2,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_NEGATIVE,
    },
    {
        TEST_ENABLE, 24U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_gmac_m3",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC4_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC4_DPLLDSP_GMAC_M3,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
#endif
#endif
    {
        TEST_ENABLE, 25U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_gmac_h11",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC4_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC4_DPLLDSP_GMAC_H11,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
#if !(defined (AVV_TEST_AUTO_BUILD))
#if defined (AVV_RUN_ALL)
    {
        TEST_ENABLE, 26U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_gmac_h12",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC4_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC4_DPLLDSP_GMAC_H12,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 27U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_gmac_h13",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC4_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC4_DPLLDSP_GMAC_H13,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_DISABLE, 28U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_gmac_h14",
        "None", "De-scoped",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC4_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC4_DPLLDSP_GMAC_H13,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_NEGATIVE,
    },
    {
        TEST_ENABLE, 29U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_eve_vid_m2",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC5_BASE,
            DEF_DCC_MODE,
            DCC_CLK_SRC0_SYS_CLK2,
            DCC_CLK_SRC1_DCC5_DPLLEVE_VID_M2,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
#endif
#endif
    {
        TEST_ENABLE, 30U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_eve_vid_m2x2",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC5_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC5_DPLLEVE_VID_M2x2,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
#if !(defined (AVV_TEST_AUTO_BUILD))
#if defined (AVV_RUN_ALL)
    {
        TEST_ENABLE, 31U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_eve_vid_m3",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC5_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC5_DPLLEVE_VID_M3,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
#endif
#endif
    {
        TEST_ENABLE, 32U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_sys_clk2",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC6_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC6_SYS_CLK2,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 33U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_core_h23",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC7_BASE,
            DEF_DCC_MODE,
            DCC_CLK_SRC0_SYS_CLK2,
            DCC_CLK_SRC1_DCC7_DPLLCORE_H23,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
#if !(defined (AVV_TEST_AUTO_BUILD))
#if defined (AVV_RUN_ALL)
    {
        TEST_ENABLE, 34U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_dpll_core_h24",
        "None", "De-scoped",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC7_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC7_DPLLCORE_H23,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_NEGATIVE,
    },
    {
        TEST_ENABLE, 35U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_vin1a",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC4_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC4_VIN1A,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 36U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_vin2a",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC4_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC4_VIN2A,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_DISABLE, 37U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_vin1b",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC6_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC6_VIN1B,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_DISABLE, 38U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_vin2b",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC6_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC6_VIN2B,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 39U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_mcasp_aclkx",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC6_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC6_MCASP_ACLKX,
            9900U,
            200U,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 40U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_mdio_mclk",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC7_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC7_MDIO_MCLK,
            990U,
            200U,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 41U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_rgmii_rxclk",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC7_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC7_RGMII_RXCLK,
            990U,
            200U,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 42U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_rxbytehs_clk",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC4_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC4_RXBTEHS_CLK,
            990U,
            20U,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 43U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-350:PDK-351:",
        "dcc_ipu_mcasp_aclkr",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate DONE/ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC6_BASE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC6_MCASP_ACLKR,
            9900U,
            200U,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
#endif
    {
        TEST_ENABLE, 44U,
        ":PDK-71:PDK-339:PDK-340:PDK-342:PDK-343:PDK-344:PDK-345:PDK-346:PDK-348:PDK-353:PDK-352:",
        "dcc_ipu_dplldsp_gmac_h12_continuous_mode",
        "None", "None",
        "DCC module should be able to monitor given clock. It should generate ERROR interrupt accordingly",
        IPU,
        {
            SOC_DCC4_BASE,
            DCC_OPERATION_MODE_CONTINUOUS,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC4_DPLLDSP_GMAC_H12,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            DEF_DCC_SEED_SRC0,
            DEF_DCC_SEED_VALID0,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
    {
        TEST_ENABLE, 100U,
        ":PDP-1393:",
        "[DCC]: Minimum programmable value for Valid0 register is 4",
        "None", "None",
        "This is programming test for above bug.",
        IPU,
        {
            DEF_DCC_MODULE,
            DEF_DCC_MODE,
            DEF_DCC_CLK_SRC0,
            DCC_CLK_SRC1_DCC1_DPLLCORE_M2,
            DEF_DCC_CLK_SRC1_ALT_CLK,
            1000U,
            4U,
            DEF_DCC_SEED_SRC1,
        },
        PRINT_ENABLE,
        ST_TT_SANITY,
    },
#endif
};

#endif /* #ifndef ST_UART_TEST_CASES_H_ */
