# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_yuv_422uyvy_to_420nv12
TEST_BENCH = $(FILE)_tb

include ../../../common/Makefile.wincommon
