# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_block_statistics
TEST_BENCH = $(FILE)_tb
CFILES = ../src_kernelC/$(FILE)_host.c ../src_C/$(FILE)_cn.c

include ../../../common/Makefile.wincommon
