# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/


FILE = UYVY_to_YUVpl
TEST_BENCH = $(FILE)_tb
include ../../../common/Makefile.wincommon

