#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/ndk/tools/servers
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/utils.js:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/utils.js
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/xdc.tci:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/xdc.tci
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/template.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/template.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/om2.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/om2.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/xmlgen.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/xmlgen.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/xmlgen2.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/xmlgen2.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/Warnings.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/Warnings.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/IPackage.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/IPackage.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/package.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/package.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/services/global/Clock.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/services/global/Clock.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/services/global/Trace.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/services/global/Trace.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/bld.js:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/bld.js
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/BuildEnvironment.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/PackageContents.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/PackageContents.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/_gen.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/_gen.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Library.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Library.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Executable.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Executable.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Repository.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Repository.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Configuration.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Configuration.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Script.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Script.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Manifest.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Manifest.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Utils.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/Utils.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget2.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget2.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget3.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget3.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITargetFilter.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/package.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/linux/xdctools_3_32_00_06_core/packages/xdc/bld/package.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/networking/ndk_2_24_02_31/ndk.bld:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/networking/ndk_2_24_02_31/ndk.bld
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/ITarget.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/ITarget.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/C28_large.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/C28_large.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/C28_float.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/C28_float.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/package.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/package.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/arm/elf/IArm.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/arm/elf/package.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/arm/elf/package.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/elf/ITarget.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/elf/ITarget.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/elf/package.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/elf/package.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/ITarget.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/ITarget.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/_utils.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/_utils.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/Linux86.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/Linux86.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/Mingw.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/Mingw.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/package.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/package.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/ITarget.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/ITarget.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/GCArmv6.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/GCArmv7A.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/IM.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/IM.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/M3.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/M3.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/M4.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/M4.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/M4F.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/M4F.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/A8F.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/A8F.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/A9F.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/A9F.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/A15F.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/A15F.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/A53F.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/A53F.xs
/datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/package.xs:
package.mak: /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/package.xs
package.mak: package.bld
endif

ti.targets.arm.elf.M4F.rootDir ?= /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/cg_tools/linux/ti-cgt-arm_5.2.5
ti.targets.arm.elf.packageBase ?= /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/arm/elf/
ti.targets.elf.C66.rootDir ?= /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/cg_tools/linux/C6000_7.4.2
ti.targets.elf.packageBase ?= /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/ti/targets/elf/
gnu.targets.arm.A15F.rootDir ?= /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/cg_tools/linux/gcc-arm-none-eabi-4_9-2015q3
gnu.targets.arm.packageBase ?= /datalocal1/user/surya/vsdk_02_12_RC1/ti_components/os_tools/bios_6_46_00_23/packages/gnu/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.oem4f
.PHONY: all,em4f .dlls,em4f .executables,em4f test,em4f
all,em4f: .executables,em4f
.executables,em4f: .libraries,em4f
.executables,em4f: .dlls,em4f
.dlls,em4f: .libraries,em4f
.libraries,em4f: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em4f
	@$(ECHO) xdc .executables,em4f
	@$(ECHO) xdc .libraries,em4f
	@$(ECHO) xdc .dlls,em4f

.PRECIOUS: $(XDCCFGDIR)/%.oe66
.PHONY: all,e66 .dlls,e66 .executables,e66 test,e66
all,e66: .executables,e66
.executables,e66: .libraries,e66
.executables,e66: .dlls,e66
.dlls,e66: .libraries,e66
.libraries,e66: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e66
	@$(ECHO) xdc .executables,e66
	@$(ECHO) xdc .libraries,e66
	@$(ECHO) xdc .dlls,e66

.PRECIOUS: $(XDCCFGDIR)/%.oa15fg
.PHONY: all,a15fg .dlls,a15fg .executables,a15fg test,a15fg
all,a15fg: .executables,a15fg
.executables,a15fg: .libraries,a15fg
.executables,a15fg: .dlls,a15fg
.dlls,a15fg: .libraries,a15fg
.libraries,a15fg: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,a15fg
	@$(ECHO) xdc .executables,a15fg
	@$(ECHO) xdc .libraries,a15fg
	@$(ECHO) xdc .dlls,a15fg


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.ndk.tools.servers.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.ndk.tools.servers" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.cfg.xdc.inc: .interfaces $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.ndk.tools.servers $@

.libraries,em4f .libraries: lib/servers.aem4f

-include lib/servers.aem4f.mak
lib/servers.aem4f: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/servers/package/package_ti.ndk.tools.servers.oem4f package/lib/lib/servers/autoconn.oem4f package/lib/lib/servers/datasrv.oem4f package/lib/lib/servers/echosrv.oem4f package/lib/lib/servers/newservers.oem4f package/lib/lib/servers/nullsrv.oem4f package/lib/lib/servers/oobsrv.oem4f  into $@ ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armar  rq $@   package/lib/lib/servers/package/package_ti.ndk.tools.servers.oem4f package/lib/lib/servers/autoconn.oem4f package/lib/lib/servers/datasrv.oem4f package/lib/lib/servers/echosrv.oem4f package/lib/lib/servers/newservers.oem4f package/lib/lib/servers/nullsrv.oem4f package/lib/lib/servers/oobsrv.oem4f 
lib/servers.aem4f: export C_DIR=
lib/servers.aem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

clean,em4f clean::
	-$(RM) lib/servers.aem4f
.libraries,em4f .libraries: lib/servers_ipv4.aem4f

-include lib/servers_ipv4.aem4f.mak
lib/servers_ipv4.aem4f: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/servers_ipv4/package/package_ti.ndk.tools.servers.oem4f package/lib/lib/servers_ipv4/autoconn.oem4f package/lib/lib/servers_ipv4/datasrv.oem4f package/lib/lib/servers_ipv4/echosrv.oem4f package/lib/lib/servers_ipv4/newservers.oem4f package/lib/lib/servers_ipv4/nullsrv.oem4f package/lib/lib/servers_ipv4/oobsrv.oem4f  into $@ ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armar  rq $@   package/lib/lib/servers_ipv4/package/package_ti.ndk.tools.servers.oem4f package/lib/lib/servers_ipv4/autoconn.oem4f package/lib/lib/servers_ipv4/datasrv.oem4f package/lib/lib/servers_ipv4/echosrv.oem4f package/lib/lib/servers_ipv4/newservers.oem4f package/lib/lib/servers_ipv4/nullsrv.oem4f package/lib/lib/servers_ipv4/oobsrv.oem4f 
lib/servers_ipv4.aem4f: export C_DIR=
lib/servers_ipv4.aem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

clean,em4f clean::
	-$(RM) lib/servers_ipv4.aem4f
.libraries,em4f .libraries: lib/servers_min.aem4f

-include lib/servers_min.aem4f.mak
lib/servers_min.aem4f: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/servers_min/package/package_ti.ndk.tools.servers.oem4f package/lib/lib/servers_min/datasrv.oem4f package/lib/lib/servers_min/echosrv.oem4f package/lib/lib/servers_min/newservers.oem4f package/lib/lib/servers_min/nullsrv.oem4f package/lib/lib/servers_min/oobsrv.oem4f  into $@ ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armar  rq $@   package/lib/lib/servers_min/package/package_ti.ndk.tools.servers.oem4f package/lib/lib/servers_min/datasrv.oem4f package/lib/lib/servers_min/echosrv.oem4f package/lib/lib/servers_min/newservers.oem4f package/lib/lib/servers_min/nullsrv.oem4f package/lib/lib/servers_min/oobsrv.oem4f 
lib/servers_min.aem4f: export C_DIR=
lib/servers_min.aem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

clean,em4f clean::
	-$(RM) lib/servers_min.aem4f
.libraries,em4f .libraries: lib/servers_min_ipv4.aem4f

-include lib/servers_min_ipv4.aem4f.mak
lib/servers_min_ipv4.aem4f: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/servers_min_ipv4/package/package_ti.ndk.tools.servers.oem4f package/lib/lib/servers_min_ipv4/datasrv.oem4f package/lib/lib/servers_min_ipv4/echosrv.oem4f package/lib/lib/servers_min_ipv4/newservers.oem4f package/lib/lib/servers_min_ipv4/nullsrv.oem4f package/lib/lib/servers_min_ipv4/oobsrv.oem4f  into $@ ...
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armar  rq $@   package/lib/lib/servers_min_ipv4/package/package_ti.ndk.tools.servers.oem4f package/lib/lib/servers_min_ipv4/datasrv.oem4f package/lib/lib/servers_min_ipv4/echosrv.oem4f package/lib/lib/servers_min_ipv4/newservers.oem4f package/lib/lib/servers_min_ipv4/nullsrv.oem4f package/lib/lib/servers_min_ipv4/oobsrv.oem4f 
lib/servers_min_ipv4.aem4f: export C_DIR=
lib/servers_min_ipv4.aem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/:$(PATH)

clean,em4f clean::
	-$(RM) lib/servers_min_ipv4.aem4f
.libraries,e66 .libraries: lib/servers.ae66

-include lib/servers.ae66.mak
lib/servers.ae66: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/servers/package/package_ti.ndk.tools.servers.oe66 package/lib/lib/servers/autoconn.oe66 package/lib/lib/servers/datasrv.oe66 package/lib/lib/servers/echosrv.oe66 package/lib/lib/servers/newservers.oe66 package/lib/lib/servers/nullsrv.oe66 package/lib/lib/servers/oobsrv.oe66  into $@ ...
	$(ti.targets.elf.C66.rootDir)/bin/ar6x  rq $@   package/lib/lib/servers/package/package_ti.ndk.tools.servers.oe66 package/lib/lib/servers/autoconn.oe66 package/lib/lib/servers/datasrv.oe66 package/lib/lib/servers/echosrv.oe66 package/lib/lib/servers/newservers.oe66 package/lib/lib/servers/nullsrv.oe66 package/lib/lib/servers/oobsrv.oe66 
lib/servers.ae66: export C_DIR=
lib/servers.ae66: PATH:=$(ti.targets.elf.C66.rootDir)/bin/:$(PATH)

clean,e66 clean::
	-$(RM) lib/servers.ae66
.libraries,e66 .libraries: lib/servers_ipv4.ae66

-include lib/servers_ipv4.ae66.mak
lib/servers_ipv4.ae66: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/servers_ipv4/package/package_ti.ndk.tools.servers.oe66 package/lib/lib/servers_ipv4/autoconn.oe66 package/lib/lib/servers_ipv4/datasrv.oe66 package/lib/lib/servers_ipv4/echosrv.oe66 package/lib/lib/servers_ipv4/newservers.oe66 package/lib/lib/servers_ipv4/nullsrv.oe66 package/lib/lib/servers_ipv4/oobsrv.oe66  into $@ ...
	$(ti.targets.elf.C66.rootDir)/bin/ar6x  rq $@   package/lib/lib/servers_ipv4/package/package_ti.ndk.tools.servers.oe66 package/lib/lib/servers_ipv4/autoconn.oe66 package/lib/lib/servers_ipv4/datasrv.oe66 package/lib/lib/servers_ipv4/echosrv.oe66 package/lib/lib/servers_ipv4/newservers.oe66 package/lib/lib/servers_ipv4/nullsrv.oe66 package/lib/lib/servers_ipv4/oobsrv.oe66 
lib/servers_ipv4.ae66: export C_DIR=
lib/servers_ipv4.ae66: PATH:=$(ti.targets.elf.C66.rootDir)/bin/:$(PATH)

clean,e66 clean::
	-$(RM) lib/servers_ipv4.ae66
.libraries,e66 .libraries: lib/servers_min.ae66

-include lib/servers_min.ae66.mak
lib/servers_min.ae66: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/servers_min/package/package_ti.ndk.tools.servers.oe66 package/lib/lib/servers_min/datasrv.oe66 package/lib/lib/servers_min/echosrv.oe66 package/lib/lib/servers_min/newservers.oe66 package/lib/lib/servers_min/nullsrv.oe66 package/lib/lib/servers_min/oobsrv.oe66  into $@ ...
	$(ti.targets.elf.C66.rootDir)/bin/ar6x  rq $@   package/lib/lib/servers_min/package/package_ti.ndk.tools.servers.oe66 package/lib/lib/servers_min/datasrv.oe66 package/lib/lib/servers_min/echosrv.oe66 package/lib/lib/servers_min/newservers.oe66 package/lib/lib/servers_min/nullsrv.oe66 package/lib/lib/servers_min/oobsrv.oe66 
lib/servers_min.ae66: export C_DIR=
lib/servers_min.ae66: PATH:=$(ti.targets.elf.C66.rootDir)/bin/:$(PATH)

clean,e66 clean::
	-$(RM) lib/servers_min.ae66
.libraries,e66 .libraries: lib/servers_min_ipv4.ae66

-include lib/servers_min_ipv4.ae66.mak
lib/servers_min_ipv4.ae66: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/servers_min_ipv4/package/package_ti.ndk.tools.servers.oe66 package/lib/lib/servers_min_ipv4/datasrv.oe66 package/lib/lib/servers_min_ipv4/echosrv.oe66 package/lib/lib/servers_min_ipv4/newservers.oe66 package/lib/lib/servers_min_ipv4/nullsrv.oe66 package/lib/lib/servers_min_ipv4/oobsrv.oe66  into $@ ...
	$(ti.targets.elf.C66.rootDir)/bin/ar6x  rq $@   package/lib/lib/servers_min_ipv4/package/package_ti.ndk.tools.servers.oe66 package/lib/lib/servers_min_ipv4/datasrv.oe66 package/lib/lib/servers_min_ipv4/echosrv.oe66 package/lib/lib/servers_min_ipv4/newservers.oe66 package/lib/lib/servers_min_ipv4/nullsrv.oe66 package/lib/lib/servers_min_ipv4/oobsrv.oe66 
lib/servers_min_ipv4.ae66: export C_DIR=
lib/servers_min_ipv4.ae66: PATH:=$(ti.targets.elf.C66.rootDir)/bin/:$(PATH)

clean,e66 clean::
	-$(RM) lib/servers_min_ipv4.ae66
.libraries,a15fg .libraries: lib/servers.aa15fg

-include lib/servers.aa15fg.mak
lib/servers.aa15fg: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/servers/package/package_ti.ndk.tools.servers.oa15fg package/lib/lib/servers/autoconn.oa15fg package/lib/lib/servers/datasrv.oa15fg package/lib/lib/servers/echosrv.oa15fg package/lib/lib/servers/newservers.oa15fg package/lib/lib/servers/nullsrv.oa15fg package/lib/lib/servers/oobsrv.oa15fg  into $@ ...
	$(gnu.targets.arm.A15F.rootDir)/bin/arm-none-eabi-ar  cr $@   package/lib/lib/servers/package/package_ti.ndk.tools.servers.oa15fg package/lib/lib/servers/autoconn.oa15fg package/lib/lib/servers/datasrv.oa15fg package/lib/lib/servers/echosrv.oa15fg package/lib/lib/servers/newservers.oa15fg package/lib/lib/servers/nullsrv.oa15fg package/lib/lib/servers/oobsrv.oa15fg 
lib/servers.aa15fg: export LD_LIBRARY_PATH=

clean,a15fg clean::
	-$(RM) lib/servers.aa15fg
.libraries,a15fg .libraries: lib/servers_ipv4.aa15fg

-include lib/servers_ipv4.aa15fg.mak
lib/servers_ipv4.aa15fg: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/servers_ipv4/package/package_ti.ndk.tools.servers.oa15fg package/lib/lib/servers_ipv4/autoconn.oa15fg package/lib/lib/servers_ipv4/datasrv.oa15fg package/lib/lib/servers_ipv4/echosrv.oa15fg package/lib/lib/servers_ipv4/newservers.oa15fg package/lib/lib/servers_ipv4/nullsrv.oa15fg package/lib/lib/servers_ipv4/oobsrv.oa15fg  into $@ ...
	$(gnu.targets.arm.A15F.rootDir)/bin/arm-none-eabi-ar  cr $@   package/lib/lib/servers_ipv4/package/package_ti.ndk.tools.servers.oa15fg package/lib/lib/servers_ipv4/autoconn.oa15fg package/lib/lib/servers_ipv4/datasrv.oa15fg package/lib/lib/servers_ipv4/echosrv.oa15fg package/lib/lib/servers_ipv4/newservers.oa15fg package/lib/lib/servers_ipv4/nullsrv.oa15fg package/lib/lib/servers_ipv4/oobsrv.oa15fg 
lib/servers_ipv4.aa15fg: export LD_LIBRARY_PATH=

clean,a15fg clean::
	-$(RM) lib/servers_ipv4.aa15fg
.libraries,a15fg .libraries: lib/servers_min.aa15fg

-include lib/servers_min.aa15fg.mak
lib/servers_min.aa15fg: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/servers_min/package/package_ti.ndk.tools.servers.oa15fg package/lib/lib/servers_min/datasrv.oa15fg package/lib/lib/servers_min/echosrv.oa15fg package/lib/lib/servers_min/newservers.oa15fg package/lib/lib/servers_min/nullsrv.oa15fg package/lib/lib/servers_min/oobsrv.oa15fg  into $@ ...
	$(gnu.targets.arm.A15F.rootDir)/bin/arm-none-eabi-ar  cr $@   package/lib/lib/servers_min/package/package_ti.ndk.tools.servers.oa15fg package/lib/lib/servers_min/datasrv.oa15fg package/lib/lib/servers_min/echosrv.oa15fg package/lib/lib/servers_min/newservers.oa15fg package/lib/lib/servers_min/nullsrv.oa15fg package/lib/lib/servers_min/oobsrv.oa15fg 
lib/servers_min.aa15fg: export LD_LIBRARY_PATH=

clean,a15fg clean::
	-$(RM) lib/servers_min.aa15fg
.libraries,a15fg .libraries: lib/servers_min_ipv4.aa15fg

-include lib/servers_min_ipv4.aa15fg.mak
lib/servers_min_ipv4.aa15fg: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/servers_min_ipv4/package/package_ti.ndk.tools.servers.oa15fg package/lib/lib/servers_min_ipv4/datasrv.oa15fg package/lib/lib/servers_min_ipv4/echosrv.oa15fg package/lib/lib/servers_min_ipv4/newservers.oa15fg package/lib/lib/servers_min_ipv4/nullsrv.oa15fg package/lib/lib/servers_min_ipv4/oobsrv.oa15fg  into $@ ...
	$(gnu.targets.arm.A15F.rootDir)/bin/arm-none-eabi-ar  cr $@   package/lib/lib/servers_min_ipv4/package/package_ti.ndk.tools.servers.oa15fg package/lib/lib/servers_min_ipv4/datasrv.oa15fg package/lib/lib/servers_min_ipv4/echosrv.oa15fg package/lib/lib/servers_min_ipv4/newservers.oa15fg package/lib/lib/servers_min_ipv4/nullsrv.oa15fg package/lib/lib/servers_min_ipv4/oobsrv.oa15fg 
lib/servers_min_ipv4.aa15fg: export LD_LIBRARY_PATH=

clean,a15fg clean::
	-$(RM) lib/servers_min_ipv4.aa15fg
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package_ti.ndk.tools.servers.oem4f,copy
package_ti.ndk.tools.servers.oem4f,copy : package_ti.ndk.tools.servers.oem4f,0,copy package_ti.ndk.tools.servers.oem4f,1,copy package_ti.ndk.tools.servers.oem4f,2,copy package_ti.ndk.tools.servers.oem4f,3,copy 
	@

package_ti.ndk.tools.servers.oem4f,0,copy : package/lib/lib/servers/package/package_ti.ndk.tools.servers.oem4f
package_ti.ndk.tools.servers.oem4f,1,copy : package/lib/lib/servers_ipv4/package/package_ti.ndk.tools.servers.oem4f
package_ti.ndk.tools.servers.oem4f,2,copy : package/lib/lib/servers_min/package/package_ti.ndk.tools.servers.oem4f
package_ti.ndk.tools.servers.oem4f,3,copy : package/lib/lib/servers_min_ipv4/package/package_ti.ndk.tools.servers.oem4f
.PHONY: package_ti.ndk.tools.servers.sem4f,copy
package_ti.ndk.tools.servers.sem4f,copy : package_ti.ndk.tools.servers.sem4f,0,copy package_ti.ndk.tools.servers.sem4f,1,copy package_ti.ndk.tools.servers.sem4f,2,copy package_ti.ndk.tools.servers.sem4f,3,copy 
	@

package_ti.ndk.tools.servers.sem4f,0,copy : package/lib/lib/servers/package/package_ti.ndk.tools.servers.sem4f
package_ti.ndk.tools.servers.sem4f,1,copy : package/lib/lib/servers_ipv4/package/package_ti.ndk.tools.servers.sem4f
package_ti.ndk.tools.servers.sem4f,2,copy : package/lib/lib/servers_min/package/package_ti.ndk.tools.servers.sem4f
package_ti.ndk.tools.servers.sem4f,3,copy : package/lib/lib/servers_min_ipv4/package/package_ti.ndk.tools.servers.sem4f
.PHONY: autoconn.oem4f,copy
autoconn.oem4f,copy : autoconn.oem4f,0,copy autoconn.oem4f,1,copy 
	@

autoconn.oem4f,0,copy : package/lib/lib/servers/autoconn.oem4f
autoconn.oem4f,1,copy : package/lib/lib/servers_ipv4/autoconn.oem4f
.PHONY: autoconn.sem4f,copy
autoconn.sem4f,copy : autoconn.sem4f,0,copy autoconn.sem4f,1,copy 
	@

autoconn.sem4f,0,copy : package/lib/lib/servers/autoconn.sem4f
autoconn.sem4f,1,copy : package/lib/lib/servers_ipv4/autoconn.sem4f
.PHONY: datasrv.oem4f,copy
datasrv.oem4f,copy : datasrv.oem4f,0,copy datasrv.oem4f,1,copy datasrv.oem4f,2,copy datasrv.oem4f,3,copy 
	@

datasrv.oem4f,0,copy : package/lib/lib/servers/datasrv.oem4f
datasrv.oem4f,1,copy : package/lib/lib/servers_ipv4/datasrv.oem4f
datasrv.oem4f,2,copy : package/lib/lib/servers_min/datasrv.oem4f
datasrv.oem4f,3,copy : package/lib/lib/servers_min_ipv4/datasrv.oem4f
.PHONY: datasrv.sem4f,copy
datasrv.sem4f,copy : datasrv.sem4f,0,copy datasrv.sem4f,1,copy datasrv.sem4f,2,copy datasrv.sem4f,3,copy 
	@

datasrv.sem4f,0,copy : package/lib/lib/servers/datasrv.sem4f
datasrv.sem4f,1,copy : package/lib/lib/servers_ipv4/datasrv.sem4f
datasrv.sem4f,2,copy : package/lib/lib/servers_min/datasrv.sem4f
datasrv.sem4f,3,copy : package/lib/lib/servers_min_ipv4/datasrv.sem4f
.PHONY: echosrv.oem4f,copy
echosrv.oem4f,copy : echosrv.oem4f,0,copy echosrv.oem4f,1,copy echosrv.oem4f,2,copy echosrv.oem4f,3,copy 
	@

echosrv.oem4f,0,copy : package/lib/lib/servers/echosrv.oem4f
echosrv.oem4f,1,copy : package/lib/lib/servers_ipv4/echosrv.oem4f
echosrv.oem4f,2,copy : package/lib/lib/servers_min/echosrv.oem4f
echosrv.oem4f,3,copy : package/lib/lib/servers_min_ipv4/echosrv.oem4f
.PHONY: echosrv.sem4f,copy
echosrv.sem4f,copy : echosrv.sem4f,0,copy echosrv.sem4f,1,copy echosrv.sem4f,2,copy echosrv.sem4f,3,copy 
	@

echosrv.sem4f,0,copy : package/lib/lib/servers/echosrv.sem4f
echosrv.sem4f,1,copy : package/lib/lib/servers_ipv4/echosrv.sem4f
echosrv.sem4f,2,copy : package/lib/lib/servers_min/echosrv.sem4f
echosrv.sem4f,3,copy : package/lib/lib/servers_min_ipv4/echosrv.sem4f
.PHONY: newservers.oem4f,copy
newservers.oem4f,copy : newservers.oem4f,0,copy newservers.oem4f,1,copy newservers.oem4f,2,copy newservers.oem4f,3,copy 
	@

newservers.oem4f,0,copy : package/lib/lib/servers/newservers.oem4f
newservers.oem4f,1,copy : package/lib/lib/servers_ipv4/newservers.oem4f
newservers.oem4f,2,copy : package/lib/lib/servers_min/newservers.oem4f
newservers.oem4f,3,copy : package/lib/lib/servers_min_ipv4/newservers.oem4f
.PHONY: newservers.sem4f,copy
newservers.sem4f,copy : newservers.sem4f,0,copy newservers.sem4f,1,copy newservers.sem4f,2,copy newservers.sem4f,3,copy 
	@

newservers.sem4f,0,copy : package/lib/lib/servers/newservers.sem4f
newservers.sem4f,1,copy : package/lib/lib/servers_ipv4/newservers.sem4f
newservers.sem4f,2,copy : package/lib/lib/servers_min/newservers.sem4f
newservers.sem4f,3,copy : package/lib/lib/servers_min_ipv4/newservers.sem4f
.PHONY: nullsrv.oem4f,copy
nullsrv.oem4f,copy : nullsrv.oem4f,0,copy nullsrv.oem4f,1,copy nullsrv.oem4f,2,copy nullsrv.oem4f,3,copy 
	@

nullsrv.oem4f,0,copy : package/lib/lib/servers/nullsrv.oem4f
nullsrv.oem4f,1,copy : package/lib/lib/servers_ipv4/nullsrv.oem4f
nullsrv.oem4f,2,copy : package/lib/lib/servers_min/nullsrv.oem4f
nullsrv.oem4f,3,copy : package/lib/lib/servers_min_ipv4/nullsrv.oem4f
.PHONY: nullsrv.sem4f,copy
nullsrv.sem4f,copy : nullsrv.sem4f,0,copy nullsrv.sem4f,1,copy nullsrv.sem4f,2,copy nullsrv.sem4f,3,copy 
	@

nullsrv.sem4f,0,copy : package/lib/lib/servers/nullsrv.sem4f
nullsrv.sem4f,1,copy : package/lib/lib/servers_ipv4/nullsrv.sem4f
nullsrv.sem4f,2,copy : package/lib/lib/servers_min/nullsrv.sem4f
nullsrv.sem4f,3,copy : package/lib/lib/servers_min_ipv4/nullsrv.sem4f
.PHONY: oobsrv.oem4f,copy
oobsrv.oem4f,copy : oobsrv.oem4f,0,copy oobsrv.oem4f,1,copy oobsrv.oem4f,2,copy oobsrv.oem4f,3,copy 
	@

oobsrv.oem4f,0,copy : package/lib/lib/servers/oobsrv.oem4f
oobsrv.oem4f,1,copy : package/lib/lib/servers_ipv4/oobsrv.oem4f
oobsrv.oem4f,2,copy : package/lib/lib/servers_min/oobsrv.oem4f
oobsrv.oem4f,3,copy : package/lib/lib/servers_min_ipv4/oobsrv.oem4f
.PHONY: oobsrv.sem4f,copy
oobsrv.sem4f,copy : oobsrv.sem4f,0,copy oobsrv.sem4f,1,copy oobsrv.sem4f,2,copy oobsrv.sem4f,3,copy 
	@

oobsrv.sem4f,0,copy : package/lib/lib/servers/oobsrv.sem4f
oobsrv.sem4f,1,copy : package/lib/lib/servers_ipv4/oobsrv.sem4f
oobsrv.sem4f,2,copy : package/lib/lib/servers_min/oobsrv.sem4f
oobsrv.sem4f,3,copy : package/lib/lib/servers_min_ipv4/oobsrv.sem4f
.PHONY: package_ti.ndk.tools.servers.oe66,copy
package_ti.ndk.tools.servers.oe66,copy : package_ti.ndk.tools.servers.oe66,0,copy package_ti.ndk.tools.servers.oe66,1,copy package_ti.ndk.tools.servers.oe66,2,copy package_ti.ndk.tools.servers.oe66,3,copy 
	@

package_ti.ndk.tools.servers.oe66,0,copy : package/lib/lib/servers/package/package_ti.ndk.tools.servers.oe66
package_ti.ndk.tools.servers.oe66,1,copy : package/lib/lib/servers_ipv4/package/package_ti.ndk.tools.servers.oe66
package_ti.ndk.tools.servers.oe66,2,copy : package/lib/lib/servers_min/package/package_ti.ndk.tools.servers.oe66
package_ti.ndk.tools.servers.oe66,3,copy : package/lib/lib/servers_min_ipv4/package/package_ti.ndk.tools.servers.oe66
.PHONY: package_ti.ndk.tools.servers.se66,copy
package_ti.ndk.tools.servers.se66,copy : package_ti.ndk.tools.servers.se66,0,copy package_ti.ndk.tools.servers.se66,1,copy package_ti.ndk.tools.servers.se66,2,copy package_ti.ndk.tools.servers.se66,3,copy 
	@

package_ti.ndk.tools.servers.se66,0,copy : package/lib/lib/servers/package/package_ti.ndk.tools.servers.se66
package_ti.ndk.tools.servers.se66,1,copy : package/lib/lib/servers_ipv4/package/package_ti.ndk.tools.servers.se66
package_ti.ndk.tools.servers.se66,2,copy : package/lib/lib/servers_min/package/package_ti.ndk.tools.servers.se66
package_ti.ndk.tools.servers.se66,3,copy : package/lib/lib/servers_min_ipv4/package/package_ti.ndk.tools.servers.se66
.PHONY: autoconn.oe66,copy
autoconn.oe66,copy : autoconn.oe66,0,copy autoconn.oe66,1,copy 
	@

autoconn.oe66,0,copy : package/lib/lib/servers/autoconn.oe66
autoconn.oe66,1,copy : package/lib/lib/servers_ipv4/autoconn.oe66
.PHONY: autoconn.se66,copy
autoconn.se66,copy : autoconn.se66,0,copy autoconn.se66,1,copy 
	@

autoconn.se66,0,copy : package/lib/lib/servers/autoconn.se66
autoconn.se66,1,copy : package/lib/lib/servers_ipv4/autoconn.se66
.PHONY: datasrv.oe66,copy
datasrv.oe66,copy : datasrv.oe66,0,copy datasrv.oe66,1,copy datasrv.oe66,2,copy datasrv.oe66,3,copy 
	@

datasrv.oe66,0,copy : package/lib/lib/servers/datasrv.oe66
datasrv.oe66,1,copy : package/lib/lib/servers_ipv4/datasrv.oe66
datasrv.oe66,2,copy : package/lib/lib/servers_min/datasrv.oe66
datasrv.oe66,3,copy : package/lib/lib/servers_min_ipv4/datasrv.oe66
.PHONY: datasrv.se66,copy
datasrv.se66,copy : datasrv.se66,0,copy datasrv.se66,1,copy datasrv.se66,2,copy datasrv.se66,3,copy 
	@

datasrv.se66,0,copy : package/lib/lib/servers/datasrv.se66
datasrv.se66,1,copy : package/lib/lib/servers_ipv4/datasrv.se66
datasrv.se66,2,copy : package/lib/lib/servers_min/datasrv.se66
datasrv.se66,3,copy : package/lib/lib/servers_min_ipv4/datasrv.se66
.PHONY: echosrv.oe66,copy
echosrv.oe66,copy : echosrv.oe66,0,copy echosrv.oe66,1,copy echosrv.oe66,2,copy echosrv.oe66,3,copy 
	@

echosrv.oe66,0,copy : package/lib/lib/servers/echosrv.oe66
echosrv.oe66,1,copy : package/lib/lib/servers_ipv4/echosrv.oe66
echosrv.oe66,2,copy : package/lib/lib/servers_min/echosrv.oe66
echosrv.oe66,3,copy : package/lib/lib/servers_min_ipv4/echosrv.oe66
.PHONY: echosrv.se66,copy
echosrv.se66,copy : echosrv.se66,0,copy echosrv.se66,1,copy echosrv.se66,2,copy echosrv.se66,3,copy 
	@

echosrv.se66,0,copy : package/lib/lib/servers/echosrv.se66
echosrv.se66,1,copy : package/lib/lib/servers_ipv4/echosrv.se66
echosrv.se66,2,copy : package/lib/lib/servers_min/echosrv.se66
echosrv.se66,3,copy : package/lib/lib/servers_min_ipv4/echosrv.se66
.PHONY: newservers.oe66,copy
newservers.oe66,copy : newservers.oe66,0,copy newservers.oe66,1,copy newservers.oe66,2,copy newservers.oe66,3,copy 
	@

newservers.oe66,0,copy : package/lib/lib/servers/newservers.oe66
newservers.oe66,1,copy : package/lib/lib/servers_ipv4/newservers.oe66
newservers.oe66,2,copy : package/lib/lib/servers_min/newservers.oe66
newservers.oe66,3,copy : package/lib/lib/servers_min_ipv4/newservers.oe66
.PHONY: newservers.se66,copy
newservers.se66,copy : newservers.se66,0,copy newservers.se66,1,copy newservers.se66,2,copy newservers.se66,3,copy 
	@

newservers.se66,0,copy : package/lib/lib/servers/newservers.se66
newservers.se66,1,copy : package/lib/lib/servers_ipv4/newservers.se66
newservers.se66,2,copy : package/lib/lib/servers_min/newservers.se66
newservers.se66,3,copy : package/lib/lib/servers_min_ipv4/newservers.se66
.PHONY: nullsrv.oe66,copy
nullsrv.oe66,copy : nullsrv.oe66,0,copy nullsrv.oe66,1,copy nullsrv.oe66,2,copy nullsrv.oe66,3,copy 
	@

nullsrv.oe66,0,copy : package/lib/lib/servers/nullsrv.oe66
nullsrv.oe66,1,copy : package/lib/lib/servers_ipv4/nullsrv.oe66
nullsrv.oe66,2,copy : package/lib/lib/servers_min/nullsrv.oe66
nullsrv.oe66,3,copy : package/lib/lib/servers_min_ipv4/nullsrv.oe66
.PHONY: nullsrv.se66,copy
nullsrv.se66,copy : nullsrv.se66,0,copy nullsrv.se66,1,copy nullsrv.se66,2,copy nullsrv.se66,3,copy 
	@

nullsrv.se66,0,copy : package/lib/lib/servers/nullsrv.se66
nullsrv.se66,1,copy : package/lib/lib/servers_ipv4/nullsrv.se66
nullsrv.se66,2,copy : package/lib/lib/servers_min/nullsrv.se66
nullsrv.se66,3,copy : package/lib/lib/servers_min_ipv4/nullsrv.se66
.PHONY: oobsrv.oe66,copy
oobsrv.oe66,copy : oobsrv.oe66,0,copy oobsrv.oe66,1,copy oobsrv.oe66,2,copy oobsrv.oe66,3,copy 
	@

oobsrv.oe66,0,copy : package/lib/lib/servers/oobsrv.oe66
oobsrv.oe66,1,copy : package/lib/lib/servers_ipv4/oobsrv.oe66
oobsrv.oe66,2,copy : package/lib/lib/servers_min/oobsrv.oe66
oobsrv.oe66,3,copy : package/lib/lib/servers_min_ipv4/oobsrv.oe66
.PHONY: oobsrv.se66,copy
oobsrv.se66,copy : oobsrv.se66,0,copy oobsrv.se66,1,copy oobsrv.se66,2,copy oobsrv.se66,3,copy 
	@

oobsrv.se66,0,copy : package/lib/lib/servers/oobsrv.se66
oobsrv.se66,1,copy : package/lib/lib/servers_ipv4/oobsrv.se66
oobsrv.se66,2,copy : package/lib/lib/servers_min/oobsrv.se66
oobsrv.se66,3,copy : package/lib/lib/servers_min_ipv4/oobsrv.se66
.PHONY: package_ti.ndk.tools.servers.oa15fg,copy
package_ti.ndk.tools.servers.oa15fg,copy : package_ti.ndk.tools.servers.oa15fg,0,copy package_ti.ndk.tools.servers.oa15fg,1,copy package_ti.ndk.tools.servers.oa15fg,2,copy package_ti.ndk.tools.servers.oa15fg,3,copy 
	@

package_ti.ndk.tools.servers.oa15fg,0,copy : package/lib/lib/servers/package/package_ti.ndk.tools.servers.oa15fg
package_ti.ndk.tools.servers.oa15fg,1,copy : package/lib/lib/servers_ipv4/package/package_ti.ndk.tools.servers.oa15fg
package_ti.ndk.tools.servers.oa15fg,2,copy : package/lib/lib/servers_min/package/package_ti.ndk.tools.servers.oa15fg
package_ti.ndk.tools.servers.oa15fg,3,copy : package/lib/lib/servers_min_ipv4/package/package_ti.ndk.tools.servers.oa15fg
.PHONY: package_ti.ndk.tools.servers.sa15fg,copy
package_ti.ndk.tools.servers.sa15fg,copy : package_ti.ndk.tools.servers.sa15fg,0,copy package_ti.ndk.tools.servers.sa15fg,1,copy package_ti.ndk.tools.servers.sa15fg,2,copy package_ti.ndk.tools.servers.sa15fg,3,copy 
	@

package_ti.ndk.tools.servers.sa15fg,0,copy : package/lib/lib/servers/package/package_ti.ndk.tools.servers.sa15fg
package_ti.ndk.tools.servers.sa15fg,1,copy : package/lib/lib/servers_ipv4/package/package_ti.ndk.tools.servers.sa15fg
package_ti.ndk.tools.servers.sa15fg,2,copy : package/lib/lib/servers_min/package/package_ti.ndk.tools.servers.sa15fg
package_ti.ndk.tools.servers.sa15fg,3,copy : package/lib/lib/servers_min_ipv4/package/package_ti.ndk.tools.servers.sa15fg
.PHONY: autoconn.oa15fg,copy
autoconn.oa15fg,copy : autoconn.oa15fg,0,copy autoconn.oa15fg,1,copy 
	@

autoconn.oa15fg,0,copy : package/lib/lib/servers/autoconn.oa15fg
autoconn.oa15fg,1,copy : package/lib/lib/servers_ipv4/autoconn.oa15fg
.PHONY: autoconn.sa15fg,copy
autoconn.sa15fg,copy : autoconn.sa15fg,0,copy autoconn.sa15fg,1,copy 
	@

autoconn.sa15fg,0,copy : package/lib/lib/servers/autoconn.sa15fg
autoconn.sa15fg,1,copy : package/lib/lib/servers_ipv4/autoconn.sa15fg
.PHONY: datasrv.oa15fg,copy
datasrv.oa15fg,copy : datasrv.oa15fg,0,copy datasrv.oa15fg,1,copy datasrv.oa15fg,2,copy datasrv.oa15fg,3,copy 
	@

datasrv.oa15fg,0,copy : package/lib/lib/servers/datasrv.oa15fg
datasrv.oa15fg,1,copy : package/lib/lib/servers_ipv4/datasrv.oa15fg
datasrv.oa15fg,2,copy : package/lib/lib/servers_min/datasrv.oa15fg
datasrv.oa15fg,3,copy : package/lib/lib/servers_min_ipv4/datasrv.oa15fg
.PHONY: datasrv.sa15fg,copy
datasrv.sa15fg,copy : datasrv.sa15fg,0,copy datasrv.sa15fg,1,copy datasrv.sa15fg,2,copy datasrv.sa15fg,3,copy 
	@

datasrv.sa15fg,0,copy : package/lib/lib/servers/datasrv.sa15fg
datasrv.sa15fg,1,copy : package/lib/lib/servers_ipv4/datasrv.sa15fg
datasrv.sa15fg,2,copy : package/lib/lib/servers_min/datasrv.sa15fg
datasrv.sa15fg,3,copy : package/lib/lib/servers_min_ipv4/datasrv.sa15fg
.PHONY: echosrv.oa15fg,copy
echosrv.oa15fg,copy : echosrv.oa15fg,0,copy echosrv.oa15fg,1,copy echosrv.oa15fg,2,copy echosrv.oa15fg,3,copy 
	@

echosrv.oa15fg,0,copy : package/lib/lib/servers/echosrv.oa15fg
echosrv.oa15fg,1,copy : package/lib/lib/servers_ipv4/echosrv.oa15fg
echosrv.oa15fg,2,copy : package/lib/lib/servers_min/echosrv.oa15fg
echosrv.oa15fg,3,copy : package/lib/lib/servers_min_ipv4/echosrv.oa15fg
.PHONY: echosrv.sa15fg,copy
echosrv.sa15fg,copy : echosrv.sa15fg,0,copy echosrv.sa15fg,1,copy echosrv.sa15fg,2,copy echosrv.sa15fg,3,copy 
	@

echosrv.sa15fg,0,copy : package/lib/lib/servers/echosrv.sa15fg
echosrv.sa15fg,1,copy : package/lib/lib/servers_ipv4/echosrv.sa15fg
echosrv.sa15fg,2,copy : package/lib/lib/servers_min/echosrv.sa15fg
echosrv.sa15fg,3,copy : package/lib/lib/servers_min_ipv4/echosrv.sa15fg
.PHONY: newservers.oa15fg,copy
newservers.oa15fg,copy : newservers.oa15fg,0,copy newservers.oa15fg,1,copy newservers.oa15fg,2,copy newservers.oa15fg,3,copy 
	@

newservers.oa15fg,0,copy : package/lib/lib/servers/newservers.oa15fg
newservers.oa15fg,1,copy : package/lib/lib/servers_ipv4/newservers.oa15fg
newservers.oa15fg,2,copy : package/lib/lib/servers_min/newservers.oa15fg
newservers.oa15fg,3,copy : package/lib/lib/servers_min_ipv4/newservers.oa15fg
.PHONY: newservers.sa15fg,copy
newservers.sa15fg,copy : newservers.sa15fg,0,copy newservers.sa15fg,1,copy newservers.sa15fg,2,copy newservers.sa15fg,3,copy 
	@

newservers.sa15fg,0,copy : package/lib/lib/servers/newservers.sa15fg
newservers.sa15fg,1,copy : package/lib/lib/servers_ipv4/newservers.sa15fg
newservers.sa15fg,2,copy : package/lib/lib/servers_min/newservers.sa15fg
newservers.sa15fg,3,copy : package/lib/lib/servers_min_ipv4/newservers.sa15fg
.PHONY: nullsrv.oa15fg,copy
nullsrv.oa15fg,copy : nullsrv.oa15fg,0,copy nullsrv.oa15fg,1,copy nullsrv.oa15fg,2,copy nullsrv.oa15fg,3,copy 
	@

nullsrv.oa15fg,0,copy : package/lib/lib/servers/nullsrv.oa15fg
nullsrv.oa15fg,1,copy : package/lib/lib/servers_ipv4/nullsrv.oa15fg
nullsrv.oa15fg,2,copy : package/lib/lib/servers_min/nullsrv.oa15fg
nullsrv.oa15fg,3,copy : package/lib/lib/servers_min_ipv4/nullsrv.oa15fg
.PHONY: nullsrv.sa15fg,copy
nullsrv.sa15fg,copy : nullsrv.sa15fg,0,copy nullsrv.sa15fg,1,copy nullsrv.sa15fg,2,copy nullsrv.sa15fg,3,copy 
	@

nullsrv.sa15fg,0,copy : package/lib/lib/servers/nullsrv.sa15fg
nullsrv.sa15fg,1,copy : package/lib/lib/servers_ipv4/nullsrv.sa15fg
nullsrv.sa15fg,2,copy : package/lib/lib/servers_min/nullsrv.sa15fg
nullsrv.sa15fg,3,copy : package/lib/lib/servers_min_ipv4/nullsrv.sa15fg
.PHONY: oobsrv.oa15fg,copy
oobsrv.oa15fg,copy : oobsrv.oa15fg,0,copy oobsrv.oa15fg,1,copy oobsrv.oa15fg,2,copy oobsrv.oa15fg,3,copy 
	@

oobsrv.oa15fg,0,copy : package/lib/lib/servers/oobsrv.oa15fg
oobsrv.oa15fg,1,copy : package/lib/lib/servers_ipv4/oobsrv.oa15fg
oobsrv.oa15fg,2,copy : package/lib/lib/servers_min/oobsrv.oa15fg
oobsrv.oa15fg,3,copy : package/lib/lib/servers_min_ipv4/oobsrv.oa15fg
.PHONY: oobsrv.sa15fg,copy
oobsrv.sa15fg,copy : oobsrv.sa15fg,0,copy oobsrv.sa15fg,1,copy oobsrv.sa15fg,2,copy oobsrv.sa15fg,3,copy 
	@

oobsrv.sa15fg,0,copy : package/lib/lib/servers/oobsrv.sa15fg
oobsrv.sa15fg,1,copy : package/lib/lib/servers_ipv4/oobsrv.sa15fg
oobsrv.sa15fg,2,copy : package/lib/lib/servers_min/oobsrv.sa15fg
oobsrv.sa15fg,3,copy : package/lib/lib/servers_min_ipv4/oobsrv.sa15fg

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_ndk_tools_servers
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_ndk_tools_servers.tar.dep
endif
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: package/package.bld.xml
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: package/build.cfg
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: package/package.xdc.inc
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: package.bld
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: package/package.cfg.xdc.inc
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: lib/servers.aem4f
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: package/package_ti.ndk.tools.servers.c
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: autoconn.c
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: datasrv.c
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: echosrv.c
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: newservers.c
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: nullsrv.c
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: oobsrv.c
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: lib/servers_ipv4.aem4f
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: lib/servers_min.aem4f
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: lib/servers_min_ipv4.aem4f
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: lib/servers.ae66
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: lib/servers_ipv4.ae66
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: lib/servers_min.ae66
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: lib/servers_min_ipv4.ae66
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: lib/servers.aa15fg
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: lib/servers_ipv4.aa15fg
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: lib/servers_min.aa15fg
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: lib/servers_min_ipv4.aa15fg
package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

ti_ndk_tools_servers.tar: package/rel/ti_ndk_tools_servers.xdc.inc package/rel/ti_ndk_tools_servers/ti/ndk/tools/servers/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_ndk_tools_servers.xdc.inc,package/rel/ti_ndk_tools_servers.tar.dep)


release release,ti_ndk_tools_servers: all ti_ndk_tools_servers.tar
clean:: .clean
	-$(RM) ti_ndk_tools_servers.tar
	-$(RM) package/rel/ti_ndk_tools_servers.xdc.inc
	-$(RM) package/rel/ti_ndk_tools_servers.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/servers))
    $(shell $(MKDIR) package/lib/lib/servers)
endif
ifeq (,$(wildcard package/lib/lib/servers/package))
    $(shell $(MKDIR) package/lib/lib/servers/package)
endif
ifeq (,$(wildcard package/lib/lib/servers_ipv4))
    $(shell $(MKDIR) package/lib/lib/servers_ipv4)
endif
ifeq (,$(wildcard package/lib/lib/servers_ipv4/package))
    $(shell $(MKDIR) package/lib/lib/servers_ipv4/package)
endif
ifeq (,$(wildcard package/lib/lib/servers_min))
    $(shell $(MKDIR) package/lib/lib/servers_min)
endif
ifeq (,$(wildcard package/lib/lib/servers_min/package))
    $(shell $(MKDIR) package/lib/lib/servers_min/package)
endif
ifeq (,$(wildcard package/lib/lib/servers_min_ipv4))
    $(shell $(MKDIR) package/lib/lib/servers_min_ipv4)
endif
ifeq (,$(wildcard package/lib/lib/servers_min_ipv4/package))
    $(shell $(MKDIR) package/lib/lib/servers_min_ipv4/package)
endif
endif
clean::
	-$(RMDIR) package


