/*
 *  Copyright (c) Texas Instruments Incorporated 2012
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 *  \file st_uartConfig.h
 *
 *  \brief This file defines the common configurations like driver handle
 *  config, channel config etc...
 */

#ifndef ST_UART_CONFIG_H_
#define ST_UART_CONFIG_H_

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include <testLib/st_uart.h>

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */

/* Defined the following so that it is easy to understand a particular config */
#define USE_DEF_CHUNKSIZE               (ST_UART_USE_DEF)
#define USE_DEF_OPMODE                  (ST_UART_USE_DEF)
#define USE_DEF_BAUDRATE                (ST_UART_USE_DEF)
#define USE_DEF_STOPBITS                (ST_UART_USE_DEF)
#define USE_DEF_CHARLEN                 (ST_UART_USE_DEF)
#define USE_DEF_PARITY                  (ST_UART_USE_DEF)
#define USE_DEF_RXTRIGLVL               (ST_UART_USE_DEF)
#define USE_DEF_TXTRIGLVL               (ST_UART_USE_DEF)
#define USE_DEF_FCTYPE                  (ST_UART_USE_DEF)
#define USE_DEF_FCPARAMRX               (ST_UART_USE_DEF)
#define USE_DEF_FCPARAMTX               (ST_UART_USE_DEF)
#define USE_DEF_LP_CNT                  (ST_UART_USE_DEF)
#define USE_DEF_OC_CNT                  (ST_UART_USE_DEF)
#define USE_DEF_BYTESPERSUBMIT          (ST_UART_USE_DEF)
#define USE_DEF_BYTESPERSUBMIT          (ST_UART_USE_DEF)
#define USE_DEF_POLLEDMODE_TIMEOUT      (0xFFFFFFF0U)

#define TEST_ENABLE                     (TRUE)
#define TEST_DISABLE                    (FALSE)
#define CACHE_ENABLE                    (TRUE)
#define CACHE_DISABLE                   (FALSE)
#define FIFO_ENABLE                     (TRUE)
#define FIFO_DISABLE                    (FALSE)
#define EDMA_RX_TC                      (0U)
#define EDMA_TX_TC                      (0U)
#define HWI_NUMBER                      (8U)
#define PRCMPWRM_ENABLE                 (TRUE)
#define PRCMPWRM_DISABLE                (FALSE)
#define PRCM_HANDLE                     (NULL)
#define PRCM_DEVID                      (0U)
#define LOOPBACK_ENABLE                 (TRUE)
#define LOOPBACK_DISABLE                (FALSE)
#define TIMEST_ENABLE                   (TRUE)
#define TIMEST_DISABLE                  (FALSE)
#define PRF_ENABLE                      (TRUE)
#define PRF_DISABLE                     (FALSE)
#define RANDOMMODE_ENABLE               (TRUE)
#define RANDOMMODE_DISABLE              (FALSE)
#define PRINT_ENABLE                    (TRUE)
#define PRINT_DISABLE                   (FALSE)
#define CROSSBARINT_ENABLE              (TRUE)
#define CROSSBARINT_DISABLE             (FALSE)

#define UART_MAX_HANDLE_CFG              ((sizeof (gStUartHandleCfg)) / \
                                         (sizeof (st_UartHandleCfg)))

#define UART_MAX_CH_CFG                  ((sizeof (gStUartChCfg)) / \
                                         (sizeof (st_UartChCfg)))

/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/** \brief Defines the various handle configuration. */
static const st_UartHandleCfg  gStUartHandleCfg[] =
{
    /* handleCfgId,
     * Uart_Params uartPrms {},
     * loopCnt, openCloseCnt,
     * timeStampEnable, prfEnable, randomModeEnable
     */
    /*
     * All parameters are default.
     */
    {
        ST_UART_HCID_DEFAULT,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            USE_DEF_OPMODE, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },

    /*
     * Polled mode configuration.
     */
    {
        ST_UART_HCID_POLLED_DEFAULT,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_BAUDRATE_2400,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            UART_BAUDRATE_2_4K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_BAUDRATE_4800,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            UART_BAUDRATE_4_8K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_BAUDRATE_9600,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            UART_BAUDRATE_9_6K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_BAUDRATE_19200,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            UART_BAUDRATE_19_2K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_BAUDRATE_38400,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            UART_BAUDRATE_38_4K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_BAUDRATE_57600,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            UART_BAUDRATE_57_6K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_BAUDRATE_115200,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            UART_BAUDRATE_115_2K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_BAUDRATE_3686400,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            UART_BAUDRATE_3686_4K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_STOPBITS_1,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, UART_NUMSTOPBITS_1, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_STOPBITS_1_5,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, UART_NUMSTOPBITS_1_5, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_STOPBITS_2,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, UART_NUMSTOPBITS_2, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_PARITY_NONE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_NO, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_PARITY_EVEN,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_EVEN, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_PARITY_ODD,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_ODD, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_PARITY_FORCED0,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_FORCED0, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_PARITY_FORCED1,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_FORCED1, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_CHARLEN_5,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, UART_CHARLEN_5,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_CHARLEN_6,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, UART_CHARLEN_6,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_CHARLEN_7,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, UART_CHARLEN_7,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_CHARLEN_8,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, UART_CHARLEN_8,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_OPEN_CLOSE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        LOOP_CNT_OC, OPEN_CLOSE_CNT_OC,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_PERFORMANCE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_FIFO_ENABLE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_FIFO_DISABLE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_DISABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_TIMEOUT_2SEC,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            POLLEDMODE_TIMEOUT_2SEC,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_TIMEOUT_10SEC,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            POLLEDMODE_TIMEOUT_10SEC,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_RANDOMLOOPCNT_ENABLE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_RANDOMMODE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_ENABLE
    },
    {
        ST_UART_HCID_POLLED_CHUNKSIZE_1,
        {
            CACHE_ENABLE, 1U, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_CHUNKSIZE_32,
        {
            CACHE_ENABLE, 32U, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_CHUNKSIZE_64,
        {
            CACHE_ENABLE, 64U, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_POLLED_CHUNKSIZE_INVALID,
        {
            CACHE_ENABLE, 100U, FIFO_ENABLE,
            UART_OPMODE_POLLED, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },

    /*
     * Interrupt mode configuration.
     */
    {
        ST_UART_HCID_INTERRUPT_DEFAULT,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_BAUDRATE_2400,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_2_4K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_BAUDRATE_4800,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_4_8K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_BAUDRATE_9600,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_9_6K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_BAUDRATE_19200,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_19_2K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_BAUDRATE_38400,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_38_4K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_BAUDRATE_57600,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_57_6K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_BAUDRATE_115200,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_115_2K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_BAUDRATE_3686400,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_3686_4K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_STOPBITS_1,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, UART_NUMSTOPBITS_1, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_STOPBITS_1_5,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, UART_NUMSTOPBITS_1_5, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_STOPBITS_2,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, UART_NUMSTOPBITS_2, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_PARITY_NONE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_NO, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_PARITY_EVEN,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_EVEN, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_PARITY_ODD,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_ODD, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_PARITY_FORCED0,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_FORCED0, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_PARITY_FORCED1,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_FORCED1, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_CHARLEN_5,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, UART_CHARLEN_5,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_CHARLEN_6,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, UART_CHARLEN_6,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_CHARLEN_7,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, UART_CHARLEN_7,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_CHARLEN_8,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, UART_CHARLEN_8,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_OPEN_CLOSE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        LOOP_CNT_OC, OPEN_CLOSE_CNT_OC,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_PERFORMANCE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_FIFO_ENABLE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_FIFO_DISABLE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_DISABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
        {
        ST_UART_HCID_INTERRUPT_RXTRIGLVL_8,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, UART_RXTRIGLVL_8, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_RXTRIGLVL_16,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, UART_RXTRIGLVL_16, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_RXTRIGLVL_56,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, UART_RXTRIGLVL_56, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_RXTRIGLVL_60,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, UART_RXTRIGLVL_60, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_TXTRIGLVL_8,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, UART_TXTRIGLVL_8,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_TXTRIGLVL_16,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, UART_TXTRIGLVL_16,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_TXTRIGLVL_32,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, UART_TXTRIGLVL_32,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_TXTRIGLVL_56,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, UART_TXTRIGLVL_56,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_RANDOMLOOPCNT_ENABLE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_RANDOMMODE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_ENABLE
    },
    {
        ST_UART_HCID_INTERRUPT_CHUNKSIZE_1,
        {
            CACHE_ENABLE, 1U, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_CHUNKSIZE_32,
        {
            CACHE_ENABLE, 32U, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_CHUNKSIZE_64,
        {
            CACHE_ENABLE, 64U, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_INTERRUPT_CHUNKSIZE_INVALID,
        {
            CACHE_ENABLE, 100U, FIFO_ENABLE,
            UART_OPMODE_INTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },

    /*
     * DMA mode configuration.
     */
    {
        ST_UART_HCID_DMA_DEFAULT,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_BAUDRATE_2400,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_2_4K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_BAUDRATE_4800,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_4_8K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_BAUDRATE_9600,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_9_6K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_BAUDRATE_19200,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_19_2K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_BAUDRATE_38400,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_38_4K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_BAUDRATE_57600,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_57_6K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_BAUDRATE_115200,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_115_2K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_BAUDRATE_3686400,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            UART_BAUDRATE_3686_4K, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
        {
        ST_UART_HCID_DMA_STOPBITS_1,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, UART_NUMSTOPBITS_1, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_STOPBITS_1_5,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, UART_NUMSTOPBITS_1_5, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_STOPBITS_2,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, UART_NUMSTOPBITS_2, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_PARITY_NONE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_NO, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_PARITY_EVEN,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_EVEN, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_PARITY_ODD,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_ODD, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_PARITY_FORCED0,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_FORCED0, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_PARITY_FORCED1,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            UART_PARITY_FORCED1, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_CHARLEN_5,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, UART_CHARLEN_5,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_CHARLEN_6,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, UART_CHARLEN_6,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_CHARLEN_7,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, UART_CHARLEN_7,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_CHARLEN_8,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, UART_CHARLEN_8,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_OPEN_CLOSE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        LOOP_CNT_OC, OPEN_CLOSE_CNT_OC,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_PERFORMANCE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_FIFO_ENABLE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_FIFO_ENABLE_PERFORMANCE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_FIFO_DISABLE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_DISABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_FIFO_DISABLE_PERFORMANCE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_DISABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_RXTRIGLVL_8,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, UART_RXTRIGLVL_8, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_RXTRIGLVL_16,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, UART_RXTRIGLVL_16, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_RXTRIGLVL_56,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, UART_RXTRIGLVL_56, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_RXTRIGLVL_60,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, UART_RXTRIGLVL_60, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        USE_DEF_LP_CNT, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_TXTRIGLVL_8,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, UART_TXTRIGLVL_8,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_TXTRIGLVL_16,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, UART_TXTRIGLVL_16,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_TXTRIGLVL_32,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, UART_TXTRIGLVL_32,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_TXTRIGLVL_56,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, UART_TXTRIGLVL_56,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_RANDOMLOOPCNT_ENABLE,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_RANDOMMODE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_DISABLE, RANDOMMODE_ENABLE
    },
    {
        ST_UART_HCID_DMA_CHUNKSIZE_1,
        {
            CACHE_ENABLE, 1U, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_CHUNKSIZE_32,
        {
            CACHE_ENABLE, 32U, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_CHUNKSIZE_64,
        {
            CACHE_ENABLE, 64U, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },
    {
        ST_UART_HCID_DMA_CHUNKSIZE_INVALID,
        {
            CACHE_ENABLE, 100U, FIFO_ENABLE,
            UART_OPMODE_DMAINTERRUPT, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        DEF_LOOP_CNT_PERFORMANCE, USE_DEF_OC_CNT,
        TIMEST_DISABLE, PRF_ENABLE, RANDOMMODE_DISABLE
    },

    /*
     * Misc configuration
     */
    {
        ST_UART_HCID_MISC_TIMESTAMP,
        {
            CACHE_ENABLE, USE_DEF_CHUNKSIZE, FIFO_ENABLE,
            USE_DEF_OPMODE, LOOPBACK_DISABLE,
            USE_DEF_BAUDRATE, USE_DEF_STOPBITS, USE_DEF_CHARLEN,
            USE_DEF_PARITY, USE_DEF_RXTRIGLVL, USE_DEF_TXTRIGLVL,
            {
                USE_DEF_FCTYPE, USE_DEF_FCPARAMTX, USE_DEF_FCPARAMRX
            },
            EDMA_RX_TC, EDMA_TX_TC, HWI_NUMBER,
            USE_DEF_POLLEDMODE_TIMEOUT,
            PRCMPWRM_DISABLE, UART_PLLDOMAIN_0, PRCM_HANDLE, PRCM_DEVID
        },
        LOOP_CNT_TIMESTAMP, USE_DEF_OC_CNT,
        TIMEST_ENABLE, PRF_DISABLE, RANDOMMODE_DISABLE
    },
};

/** \brief Defines the various channel configuration. */
static const st_UartChCfg      gStUartChCfg[] =
{
    {
        /* All parameters are default. */
        ST_UART_CCID_DEFAULT,
        {
            NULL,
            {
                CROSSBARINT_DISABLE,
                0xFFU
            }
        },
        ST_UART_BPS_FIXED, USE_DEF_BYTESPERSUBMIT, DEF_INCREMENT_FACTOR
    },
    {
        ST_UART_CCID_RAMP_UP,
        {
            NULL,
            {
                CROSSBARINT_DISABLE,
                0xFFU
            }
        },
        ST_UART_BPS_RAMP_UP, USE_DEF_BYTESPERSUBMIT, DEF_INCREMENT_FACTOR
    },
    {
        ST_UART_CCID_RAMP_DOWN,
        {
            NULL,
            {
                CROSSBARINT_DISABLE,
                0xFFU
            }
        },
        ST_UART_BPS_RAMP_DOWN, USE_DEF_BYTESPERSUBMIT, DEF_INCREMENT_FACTOR
    },
    {
        ST_UART_CCID_RX_OPEN_CLOSE,
        {
            NULL,
            {
                CROSSBARINT_DISABLE,
                0xFFU
            }
        },
        ST_UART_BPS_FIXED, RX_BYTESPERSUBMIT_OC, DEF_INCREMENT_FACTOR
    },
    {
        ST_UART_CCID_TX_OPEN_CLOSE,
        {
            NULL,
            {
                CROSSBARINT_DISABLE,
                0xFFU
            }
        },
        ST_UART_BPS_FIXED, TX_BYTESPERSUBMIT_OC, DEF_INCREMENT_FACTOR
    },
};

#endif /* #ifndef ST_UART_CONFIG_H_ */
