UC_iss_capture_isp_simcop_display=yes
UC_iss_mult_capture_isp_2d_3d_sv_tda3x=yes
UC_iss_mult_capture_isp_dewarp_3dsv_tda3xx=yes
UC_iss_mult_capture_isp_simcop_sv_tda3xx=yes
UC_iss_multi_inst_capture_display=yes
UC_saveDisFrame=yes

UC_vip_single_cam_analytics2=yes
UC_vip_single_cam_edge_detection=yes
UC_vip_single_cam_frame_copy=yes
UC_vip_single_cam_frame_copy_safety=yes
UC_vip_single_cam_lane_detection=yes
UC_vip_single_cam_object_detection2=yes
UC_vip_single_cam_sfm=yes
UC_vip_single_cam_sparse_optical_flow=yes
UC_vip_single_cam_subframe_copy=yes
UC_vip_single_cam_tlr=yes
UC_vip_single_cam_view=yes
UC_vip_single_cam_view_encdec=yes


UC_srv_calibration=yes
UC_lvds_vip_sv_standalone=yes
UC_lvds_vip_multi_cam_view=yes

UC_null_src_dec_display=yes
UC_null_src_display=yes
UC_network_rx_tx=yes

ifeq ($(AVB_INCLUDE),yes)
UC_avbrx_dec_display_avbtx=yes
endif

UC_radar_objectdetect_display=yes
UC_camera_radar_capture_display=yes

UC_tidl_OD_radar_process_display=yes
