# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_census_16bits
TEST_BENCH = $(FILE)_tb
CFILES = ../src_kernelC/init_census_16bits_params.c ../src_C/$(FILE)_cn.c $(FILE)_config.c

include ../../../common/Makefile.wincommon
