# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_blockAverage2x2
CFILES = ../src_C/$(FILE)_cn.c
TEST_BENCH = $(FILE)_tb

include ../../../common/Makefile.wincommon
