# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_compute_rBrief
TEST_BENCH = $(FILE)_tb
KERNEL = ../src_kernelC/vcop_compute_rBrief
CFILES = ../src_C/$(FILE)_cn.c $(FILE)_config.c 

include ../../../common/Makefile.wincommon
EVE_LCF := linker.cmd