#!/bin/bash
#   ============================================================================
#   @file   stw_bsp_include_path_migration.sh
#
#   @desc   Script to find and replace the STW/BSP include file paths as per
#           PDK dir structure
#
#   ============================================================================
#   Revision History
#   23-Feb-2017 Sivaraj         Initial draft.
#
#   ============================================================================
# Command: stw_bsp_include_path_migration.sh <$dest_dir> <$pdk_dir)
# ./stw_bsp_include_path_migration.sh ./vision_sdk/ /data/datalocal1_videoapps01/user/sivaraj/pdk

date=`date '+%b_%d_%Y'`
date_print=`date '+%d-%b-%Y %I:%M:%S %p'`

#Get user input
working_dir=`pwd`
dest_dir=$1
#Used to cross check if replaced file exists in pdk repo
pdk_dir=$2
enable_info=$3

#Default values
: ${dest_dir:="/data/datalocal1_videoapps01/user/sivaraj/vision_sdk"}
: ${pdk_dir:="/data/datalocal1_videoapps01/user/sivaraj/pdk"}
: ${enable_info:="yes"}

#File replace list separated by | - find_string|replace_string
file_replace_list=(
    #HW Files
    "hw_mcspi\.h|ti/csl/cslr_mcspi\.h"
    "hw_mailbox\.h|ti/csl/cslr_mailbox\.h"
    "hw_gpmc\.h|ti/csl/cslr_gpmc\.h"
    "hw_mmc\.h|ti/csl/cslr_mmc\.h"
    "hw_edma_tc\.h|ti/csl/cslr_edma\.h"
    "hw_edma_tpcc\.h|ti/csl/cslr_edma\.h"
    "hw_uart\.h|ti/csl/cslr_uart\.h"
    "hw_mmu\.h|ti/csl/cslr_mmu\.h"
    "hw_ocmc_ram\.h|ti/csl/cslr_ocmc_ecc\.h"
    "hw_i2c\.h|ti/csl/cslr_i2c\.h"
    "hw_mcasp\.h|ti/csl/cslr_mcasp\.h"
    "hw_l4_ap\.h|ti/csl/cslr_l4fw\.h"
    "hw_l4_ia\.h|ti/csl/cslr_l4fw\.h"
    "hw_counter_32k\.h|ti/csl/cslr_synctimer\.h"
    "hw_qspi\.h|ti/csl/cslr_qspi\.h"
    "hw_spinlock\.h|ti/csl/cslr_spinlock\.h"
    "hw_timer\.h|ti/csl/cslr_timer\.h"
    "hw_wd_timer\.h|ti/csl/cslr_wd_timer\.h"
    "hw_gpio\.h|ti/csl/cslr_gpio\.h"
    "hw_tesoc\.h|ti/csl/cslr_tesoc\.h"
    "hw_dcan\.h|ti/csl/cslr_dcan\.h"
    "hw_crc\.h|ti/csl/cslr_crc\.h"
    "hw_emif\.h|ti/csl/cslr_emif\.h"
    "hw_adc\.h|ti/csl/cslr_adc\.h"
    "hw_esm\.h|ti/csl/cslr_esm\.h"
    "hw_mcanss\.h|ti/csl/cslr_mcan\.h"
    "hw_dcc\.h|ti/csl/cslr_dcc\.h"
    "hw_rti\.h|ti/csl/cslr_rti\.h"
    "hw_l3fw\.h|ti/csl/cslr_l3fw\.h"
    "hw_dcan\.h|ti/csl/cslr_dcan\.h"
    "hw_emif\.h|ti/csl/cslr_emif\.h"
    "hw_pciectrl_ep_cfg_pcie\.h|ti/csl/cslr_pcie\.h"
    "hw_pciectrl_ep_cfg_dbics\.h|ti/csl/cslr_pcie\.h"
    "hw_pciectrl_rc_cfg_dbics\.h|ti/csl/cslr_pcie\.h"
    "hw_pciectrl_rc_cfg_dbics2\.h|ti/csl/cslr_pcie\.h"
    "hw_pciectrl_pl_conf\.h|ti/csl/cslr_pcie\.h"
    "hw_pciectrl_ep_cfg_dbics2\.h|ti/csl/cslr_pcie\.h"
    "hw_pciectrl_ti_conf\.h|ti/csl/cslr_pcie\.h"
    "cslr_pwmss\.h|ti/csl/cslr_pwmss\.h"
    "hw_pwmss_epwm\.h|ti/csl/cslr_epwm\.h"
    "hw_pwmss_submodule_offsets\.h|ti/csl/cslr_epwm\.h"
    "hw_vpe\.h|ti/csl/cslr_vpe\.h"
    "hw_vip_parser\.h|ti/csl/cslr_vip_parser\.h"
    "hw_chr_us\.h|ti/csl/cslr_chr_us\.h"
    "hw_vpdma\.h|ti/csl/cslr_vpdma\.h"
    "hw_vip\.h|ti/csl/cslr_vip\.h"
    "hw_csc\.h|ti/csl/cslr_csc\.h"
    "hw_sc\.h|ti/csl/cslr_sc\.h"
    "hw_dei\.h|ti/csl/cslr_dei\.h"
    "hw_cal\.h|ti/csl/cslr_cal\.h"
    "hw_hdmi_wp\.h|ti/csl/cslr_dss\.h"
    "hw_hdmi_pll\.h|ti/csl/cslr_dss\.h"
    "hw_hdmi_phy\.h|ti/csl/cslr_dss\.h"
    "hw_hdmi_dwc_tx\.h|ti/csl/cslr_dss\.h"
    "hw_dispc\.h|ti/csl/cslr_dss\.h"
    "hw_dss_family\.h|ti/csl/cslr_dss\.h"
    "hw_dss_vid\.h|ti/csl/cslr_dss\.h"
    "hw_dss_glbce\.h|ti/csl/cslr_dss\.h"
    "hw_dss_wb\.h|ti/csl/cslr_dss\.h"
    "hw_dss_dssreg\.h|ti/csl/cslr_dss\.h"
    "hw_dss_gfx\.h|ti/csl/cslr_dss\.h"
    "hw_dss_vp\.h|ti/csl/cslr_dss\.h"
    "hw_dss_ovr\.h|ti/csl/cslr_dss\.h"
    "hw_dss_venc\.h|ti/csl/cslr_dss\.h"
    "hw_dss_common\.h|ti/csl/cslr_dss\.h"
    "hw_iss_lvdsrx\.h|ti/csl/cslr_iss\.h"
    "hw_iss_isif\.h|ti/csl/cslr_iss\.h"
    "hw_iss_regs\.h|ti/csl/cslr_iss\.h"
    "hw_iss_cal\.h|ti/csl/cslr_cal\.h"
    "hw_iss_nsf3\.h|ti/csl/cslr_iss\.h"
    "hw_iss_rsz\.h|ti/csl/cslr_iss\.h"
    "hw_iss_h3a\.h|ti/csl/cslr_iss\.h"
    "hw_iss_ipipeif\.h|ti/csl/cslr_iss\.h"
    "hw_iss_ipipe\.h|ti/csl/cslr_iss\.h"
    "hw_iss_simcop_dma\.h|ti/csl/cslr_iss\.h"
    "hw_iss_simcop_regs\.h|ti/csl/cslr_iss\.h"
    "hw_iss_vtnf\.h|ti/csl/cslr_iss\.h"
    "hw_iss_sys1\.h|ti/csl/cslr_iss\.h"
    "hw_iss_sys2\.h|ti/csl/cslr_iss\.h"
    "hw_iss_sys3\.h|ti/csl/cslr_iss\.h"
    "hw_mdio\.h|ti/csl/cslr_mdio\.h"
    #HW SOC files
    "soc\.h|ti/csl/soc\.h"
    "soc_defines\.h|ti/csl/soc\.h"
    "tda2xx/soc_defines\.h|ti/csl/soc\.h"
    "tda3xx/soc_defines\.h|ti/csl/soc\.h"
    "hw_iss_ctset_core\.h|ti/csl/soc\.h"
    "hw/hw_ipu_m4_nvic\.h|ti/csl/soc\.h"
    "hw_ipu_m4_nvic\.h|ti/csl/soc\.h"
    "hw_ipu_wugen_local_prcm\.h|ti/csl/soc\.h"
    "hw/hw_ctrl_core\.h|ti/csl/soc\.h"
    "hw_ctrl_core\.h|ti/csl/soc\.h"
    "hw_dsp1_cm_core_aon\.h|ti/csl/soc\.h"
    "hw_ctrl_core_irq_dma\.h|ti/csl/soc\.h"
    "hw_sysconfig\.h|ti/csl/soc\.h"
    "hw_cmi\.h|ti/csl/soc\.h"
    "hw_emu_prm\.h|ti/csl/soc\.h"
    "hw_eve1_prm\.h|ti/csl/soc\.h"
    "hw_ckgen_cm_core\.h|ti/csl/soc\.h"
    "hw_iss_cm_core_aon\.h|ti/csl/soc\.h"
    "hw_dsp2_prm\.h|ti/csl/soc\.h"
    "hw_dsp1_prm\.h|ti/csl/soc\.h"
    "hw_l3_noc\.h|ti/csl/soc\.h"
    "hw_core_prm\.h|ti/csl/soc\.h"
    "hw_ctrl_core_intr_dma\.h|ti/csl/soc\.h"
    "hw_ipu_prm\.h|ti/csl/soc\.h"
    "hw_core_cm_core\.h|ti/csl/soc\.h"
    "hw_cam_prm\.h|ti/csl/soc\.h"
    "hw_ocp_socket_cm_core_aon\.h|ti/csl/soc\.h"
    "hw/hw_wkupaon_cm\.h|ti/csl/soc\.h"
    "hw_wkupaon_cm\.h|ti/csl/soc\.h"
    "hw/hw_ctrl_wkup\.h|ti/csl/soc\.h"
    "hw_ctrl_wkup\.h|ti/csl/soc\.h"
    "hw_ckgen_prm\.h|ti/csl/soc\.h"
    "hw_l4per_prm\.h|ti/csl/soc\.h"
    "hw_l3init_cm_core\.h|ti/csl/soc\.h"
    "hw_custefuse_cm_core\.h|ti/csl/soc\.h"
    "hw_eve1_cm_core_aon\.h|ti/csl/soc\.h"
    "hw_emu_cm\.h|ti/csl/soc\.h"
    "hw_iss_prm\.h|ti/csl/soc\.h"
    "hw_coreaon_cm_core\.h|ti/csl/soc\.h"
    "hw_ckgen_cm_core_aon\.h|ti/csl/soc\.h"
    "hw_l4_cfg_ap\.h|ti/csl/soc\.h"
    "hw_restore_cm_core_aon\.h|ti/csl/soc\.h"
    "hw_cam_cm_core\.h|ti/csl/soc\.h"
    "hw_l4_cfg_ia_ip0\.h|ti/csl/soc\.h"
    "hw_ctrl_core_pad\.h|ti/csl/soc\.h"
    "hw/hw_ctrl_core_pad\.h|ti/csl/soc\.h"
    "hw_ctrl_core_pad_io\.h|ti/csl/soc\.h"
    "hw/hw_ctrl_core_pad_io\.h|ti/csl/soc\.h"
    "hw_dss_cm_core\.h|ti/csl/soc\.h"
    "hw_dsp2_cm_core_aon\.h|ti/csl/soc\.h"
    "hw_custefuse_prm\.h|ti/csl/soc\.h"
    "hw_device_prm\.h|ti/csl/soc\.h"
    "hw_pmi\.h|ti/csl/soc\.h"
    "hw_l4per_cm_core\.h|ti/csl/soc\.h"
    "hw_ipu_cm_core_aon\.h|ti/csl/soc\.h"
    "hw_ocp_socket_prm\.h|ti/csl/soc\.h"
    "hw_wkupaon_prm\.h|ti/csl/soc\.h"
    "hw_l3init_prm\.h|ti/csl/soc\.h"
    "hw_dss_prm\.h|ti/csl/soc\.h"
    "hw_restore_cm_core\.h|ti/csl/soc\.h"
    "hw_ctrl_core_sec\.h|ti/csl/soc\.h"
    "hw_ctrl_wkup_pad\.h|ti/csl/soc\.h"
    "hw_ocp_socket_cm_core\.h|ti/csl/soc\.h"
    "hw_l4_cfg_la\.h|ti/csl/soc\.h"
    # TDA2XX/Common HW SOC files
    "hw_eve2_cm_core_aon\.h|ti/csl/soc\.h"
    "hw_iva_prm\.h|ti/csl/soc\.h"
    "hw_coreaon_prm\.h|ti/csl/soc\.h"
    "hw_mpu_prm\.h|ti/csl/soc\.h"
    "hw_rtc_prm\.h|ti/csl/soc\.h"
    "hw_vpe_cm_core_aon\.h|ti/csl/soc\.h"
    "hw_rtc_cm_core_aon\.h|ti/csl/soc\.h"
    "hw_eve4_cm_core_aon\.h|ti/csl/soc\.h"
    "hw_mpu_prcm_prmc1\.h|ti/csl/soc\.h"
    "hw_eve3_cm_core_aon\.h|ti/csl/soc\.h"
    "hw_mpu_prcm_prmc0\.h|ti/csl/soc\.h"
    "hw_mpu_prcm_cmc1\.h|ti/csl/soc\.h"
    "hw_eve2_prm\.h|ti/csl/soc\.h"
    "hw_mpu_prcm_device\.h|ti/csl/soc\.h"
    "hw_iva_cm_core\.h|ti/csl/soc\.h"
    "hw_mpu_prcm_cmc0\.h|ti/csl/soc\.h"
    "hw_eve4_prm\.h|ti/csl/soc\.h"
    "hw_mpu_prcm_ocpsocket\.h|ti/csl/soc\.h"
    "hw_eve3_prm\.h|ti/csl/soc\.h"
    "hw_mpu_cm_core_aon\.h|ti/csl/soc\.h"
    "hw_vpe_prm\.h|ti/csl/soc\.h"
    #STW DAL
    "l4fw\.h|ti/csl/csl_l4fw\.h"
    "wd_timer\.h|ti/csl/csl_wd_timer\.h"
    "gpio_v2\.h|ti/csl/csl_gpio\.h"
    "mailbox\.h|ti/csl/csl_mailbox\.h"
    "tesoc\.h|ti/csl/csl_tesoc\.h"
    "hsi2c\.h|ti/csl/csl_i2c\.h"
    "csl_epwm\.h|ti/csl/csl_epwm\.h"
    "ocmc_ecc_l1\.h|ti/csl/csl_ocmc_ecc\.h"
    "ocmc_ecc_l2\.h|ti/csl/csl_ocmc_ecc\.h"
    "mcasp\.h|ti/csl/csl_mcasp\.h"
    "edma\.h|ti/csl/csl_edma\.h"
    "l3fw\.h|ti/csl/csl_l3fw\.h"
    "dcan\.h|ti/csl/csl_dcan\.h"
    "adc\.h|ti/csl/csl_adc\.h"
    "uart\.h|ti/csl/csl_uart\.h"
    "emif\.h|ti/csl/csl_emif\.h"
    "esm\.h|ti/csl/csl_esm\.h"
    "rti\.h|ti/csl/csl_rti\.h"
    "spinlock\.h|ti/csl/csl_spinlock\.h"
    "gpmc\.h|ti/csl/csl_gpmc\.h"
    "qspi\.h|ti/csl/csl_qspi\.h"
    "mcspi\.h|ti/csl/csl_mcspi\.h"
    "timer\.h|ti/csl/csl_timer\.h"
    "pcie\.h|ti/csl/csl_pcie\.h"
    "crc\.h|ti/csl/csl_crc\.h"
    "mcan\.h|ti/csl/csl_mcan\.h"
    "dcc\.h|ti/csl/csl_dcc\.h"
    "hs_mmcsd\.h|ti/csl/csl_mmcsd\.h"
    "mmu\.h|ti/csl/csl_mmu\.h"
    "hw_types\.h|ti/csl/hw_types\.h"
    "hw/hw_types\.h|ti/csl/hw_types\.h"
    #STW Sysconfig
    "hw_ipu_unicache_cfg\.h|ti/csl/cslr_cache\.h"
    "hw_ipu_unicache_cfg\.h|ti/csl/cslr_cache\.h"
    "hw_intc\.h|ti/csl/arch/csl_arch\.h"
    "hw_mpu_intc_phys\.h|ti/csl/arch/csl_arch\.h"
    "hw_mpu_intc_dist\.h|ti/csl/arch/csl_arch\.h"
    "hw_mpu_wugen\.h|ti/csl/arch/csl_arch\.h"
    "unicache\.h|ti/csl/arch/csl_arch\.h"
    "ipu_ecc\.h|ti/csl/arch/csl_arch\.h"
    "ammu\.h|ti/csl/arch/csl_arch\.h"
    "interrupt\.h|ti/csl/arch/csl_arch\.h"
    "armv7m/ipu_wugen\.h|ti/csl/arch/csl_arch\.h"
    "ipu_wugen\.h|ti/csl/arch/csl_arch\.h"
    "cpu\.h|ti/csl/arch/csl_arch\.h"
    "cp15\.h|ti/csl/arch/csl_arch\.h"
    "armv7a/tda2xx/mpu_wugen\.h|ti/csl/arch/csl_arch\.h"
    "mpu_wugen\.h|ti/csl/arch/csl_arch\.h"
    "mmu_a15_gcc_asm\.h|ti/csl/arch/csl_arch\.h"
    "mmu_a15\.h|ti/csl/arch/csl_arch\.h"
    "ecc_a15\.h|ti/csl/arch/csl_arch\.h"
    "cache_a15_gcc_asm\.h|ti/csl/arch/csl_arch\.h"
    "ecc_a15_gcc_asm\.h|ti/csl/arch/csl_arch\.h"
    "cache_a15\.h|ti/csl/arch/csl_arch\.h"
    "hw_ipu_unicache_mmu\.h|ti/csl/cslr_mmu\.h"
    "hw_ipu_mmu\.h|ti/csl/cslr_mmu\.h"
    "hw_dsp_icfg\.h|ti/csl/arch/csl_arch\.h"
    "hw_dsp_system\.h|ti/csl/arch/csl_arch\.h"
    "hw_xmc\.h|ti/csl/arch/csl_arch\.h"
    "dsp_config\.h|ti/csl/arch/csl_arch\.h"
    "dsp_ecc\.h|ti/csl/arch/csl_arch\.h"
    "dsp_icfg\.h|ti/csl/arch/csl_arch\.h"
    "dsp_usrSpvSupport\.h|ti/csl/arch/csl_arch\.h"
    "dsp_wugen\.h|ti/csl/arch/csl_arch\.h"
    "dsp_xmc\.h|ti/csl/arch/csl_arch\.h"
    "c66x/dsp_config\.h|ti/csl/arch/csl_arch\.h"
    "c66x/dsp_ecc\.h|ti/csl/arch/csl_arch\.h"
    "c66x/dsp_icfg\.h|ti/csl/arch/csl_arch\.h"
    "c66x/dsp_usrSpvSupport\.h|ti/csl/arch/csl_arch\.h"
    "c66x/dsp_wugen\.h|ti/csl/arch/csl_arch\.h"
    "c66x/dsp_xmc\.h|ti/csl/arch/csl_arch\.h"
    "hw_eve_control\.h|ti/csl/cslr_eve\.h"
    "arp32_wugen\.h|ti/csl/arch/csl_arch\.h"
    "intctl\.h|ti/csl/arch/csl_arch\.h"
    "inth\.h|ti/csl/arch/csl_arch\.h"
    #STW DIAGLIB
    "diagLib/diagLib_crc\.h|ti/diag/diagLib_crc\.h"
    "diagLib/diagLib_ecc\.h|ti/diag/diagLib_ecc\.h"
    "diagLib/diagLib_mcspi\.h|ti/diag/diagLib_mcspi\.h"
    "diagLib/diagLib_can\.h|ti/diag/diagLib_can\.h"
    "diagLib/diagLib_adc\.h|ti/diag/diagLib_adc\.h"
    #STW IPCLIB
    "ipclib/ipclib_interruptTda2ex\.h|ti/drv/ipc_lite/ipclib_interruptTda2ex\.h"
    "ipclib/ipclib_interruptTda3xx\.h|ti/drv/ipc_lite/ipclib_interruptTda3xx\.h"
    "ipclib/ipclib_interruptTda2xx\.h|ti/drv/ipc_lite/ipclib_interruptTda2xx\.h"
    "ipclib/ipclib_interrupt\.h|ti/drv/ipc_lite/ipclib_interrupt\.h"
    #STW I2C LLD
    "i2clib/lld_hsi2c\.h|ti/drv/stw_lld/i2clld/lld_hsi2c\.h"
    "lld_hsi2c_edma\.h|ti/drv/stw_lld/i2clld/src/lld_hsi2c_edma\.h"
    #STW FWLIB
    "safetylib/fwlibl3\.h|ti/drv/fw_l3l4/fwlibl3\.h"
    "safetylib/fwlibl4\.h|ti/drv/fw_l3l4/fwlibl4\.h"
    "fwlibl3\.h|ti/drv/fw_l3l4/fwlibl3\.h"
    "fwlibl4\.h|ti/drv/fw_l3l4/fwlibl4\.h"
    #FATLIB
    "hs_mmcsdlib\.h|ti/drv/stw_lld/fatlib/hs_mmcsdlib\.h"
    "hsmmcsd_edma\.h|ti/drv/stw_lld/fatlib/hsmmcsd_edma\.h"
    "mmcsd_proto\.h|ti/drv/stw_lld/fatlib/mmcsd_proto\.h"
    "fatfs/ff\.h|ti/drv/stw_lld/fatlib/fatfs/ff\.h"
    "fatfs/integer\.h|ti/drv/stw_lld/fatlib/fatfs/integer\.h"
    "fatfs/diskio\.h|ti/drv/stw_lld/fatlib/fatfs/diskio\.h"
    "fatfs/ffconf\.h|ti/drv/stw_lld/fatlib/fatfs/ffconf\.h"
    "hsmmcsd_API\.h|ti/drv/stw_lld/fatlib/hsmmcsd_API\.h"
    #STW Platform
    "platform\.h|ti/drv/stw_lld/platform/platform\.h"
    "platforms/stw_platform\.h|ti/drv/stw_lld/platform/stw_platform\.h"
    "chip_config\.h|ti/drv/stw_lld/platform/chip_config\.h"
    "dma_xbar_event_ids\.h|ti/drv/stw_lld/platform/dma_xbar_event_ids\.h"
    "dma_xbar\.h|ti/drv/stw_lld/platform/dma_xbar\.h"
    "irq_xbar\.h|ti/drv/stw_lld/platform/irq_xbar\.h"
    "irq_xbar_interrupt_ids\.h|ti/drv/stw_lld/platform/irq_xbar_interrupt_ids\.h"
    #STW QSPILIB
    "qspi_flash\.h|ti/boot/sbl_auto/qspiflash/qspi_flash\.h"
    "qspi_cmd_init\.h|ti/boot/sbl_auto/qspiflash/qspi_cmd_init\.h"
    #STW NORFLASHLIB
    "nor\.h|ti/boot/sbl_auto/norflash/nor_flash\.h"
    #STW Utils
    "uartStdio\.h|ti/drv/stw_lld/uartconsole/uartStdio\.h"
    "uartConsole\.h|ti/drv/stw_lld/uartconsole/uartConsole\.h"
    #SBL
    "sbl_lib/sbl_lib\.h|ti/boot/sbl_auto/sbl_lib/sbl_lib\.h"
    "sbl_lib/sbl_lib_config\.h|ti/boot/sbl_auto/sbl_lib/sbl_lib_config\.h"
    "sbl_lib/sbl_lib_board\.h|ti/boot/sbl_auto/sbl_lib/sbl_lib_board\.h"
    "sbl_lib/sbl_lib_tda2xx\.h|ti/boot/sbl_auto/sbl_lib/sbl_lib_tda2xx\.h"
    "sbl_lib/sbl_lib_tda3xx\.h|ti/boot/sbl_auto/sbl_lib/sbl_lib_tda3xx\.h"
    "sbl_lib\.h|ti/boot/sbl_auto/sbl_lib/sbl_lib\.h"
    "sbl_lib_config\.h|ti/boot/sbl_auto/sbl_lib/sbl_lib_config\.h"
    "sbl_lib_board\.h|ti/boot/sbl_auto/sbl_lib/sbl_lib_board\.h"
    "sbl_lib_tda2xx\.h|ti/boot/sbl_auto/sbl_lib/sbl_lib_tda2xx\.h"
    "sbl_lib_tda3xx\.h|ti/boot/sbl_auto/sbl_lib/sbl_lib_tda3xx\.h"
    "sbl_utils/sbl_utils_common\.h|ti/boot/sbl_auto/sbl_utils/sbl_utils_common\.h"
    "sbl_utils/sbl_utils_ddr_config\.h|ti/boot/sbl_auto/sbl_utils/sbl_utils_ddr_config\.h"
    "sbl_utils/sbl_utils_tda2xx\.h|ti/boot/sbl_auto/sbl_utils/sbl_utils_tda2xx\.h"
    "sbl_utils/sbl_utils_tda3xx\.h|ti/boot/sbl_auto/sbl_utils/sbl_utils_tda3xx\.h"
    "sbl_utils/sbl_utils_tda3xx_i2c\.h|ti/boot/sbl_auto/sbl_utils/sbl_utils_tda3xx_i2c\.h"
    "sbl_utils_common\.h|ti/boot/sbl_auto/sbl_utils/sbl_utils_common\.h"
    "sbl_utils_ddr_config\.h|ti/boot/sbl_auto/sbl_utils/sbl_utils_ddr_config\.h"
    "sbl_utils_tda2xx\.h|ti/boot/sbl_auto/sbl_utils/sbl_utils_tda2xx\.h"
    "sbl_utils_tda3xx\.h|ti/boot/sbl_auto/sbl_utils/sbl_utils_tda3xx\.h"
    "sbl_utils_tda3xx_i2c\.h|ti/boot/sbl_auto/sbl_utils/sbl_utils_tda3xx_i2c\.h"
    #STW BOARD
    "stw_board\.h|ti/drv/stw_lld/boards/stw_board\.h"
    "boards/stw_board\.h|ti/drv/stw_lld/boards/stw_board\.h"
    #STW App utils
    "stwutils_app\.h|ti/drv/stw_lld/examples/utility/stwutils_app\.h"
    #STW Security
    "security/aes128\.h|ti/boot/sbl_auto/security/include/aes128\.h"
    "security/aes128_cbc\.h|ti/boot/sbl_auto/security/include/aes128_cbc\.h"
    "security/sha256\.h|ti/boot/sbl_auto/security/include/sha256\.h"
    "security/tda3xx/tda3xx_gp_prime\.h|ti/boot/sbl_auto/security/include/tda3xx/tda3xx_gp_prime\.h"
    "security/tda3xx/hw_fusefarm\.h|ti/boot/sbl_auto/security/include/tda3xx/hw_fusefarm\.h"
    "security/tda3xx/efuse\.h|ti/boot/sbl_auto/security/include/tda3xx/efuse\.h"
    "aes128\.h|ti/boot/sbl_auto/security/include/aes128\.h"
    "aes128_cbc\.h|ti/boot/sbl_auto/security/include/aes128_cbc\.h"
    "sha256\.h|ti/boot/sbl_auto/security/include/sha256\.h"
    "tda3xx/tda3xx_gp_prime\.h|ti/boot/sbl_auto/security/include/tda3xx/tda3xx_gp_prime\.h"
    "tda3xx/hw_fusefarm\.h|ti/boot/sbl_auto/security/include/tda3xx/hw_fusefarm\.h"
    "tda3xx/efuse\.h|ti/boot/sbl_auto/security/include/tda3xx/efuse\.h"
    #STW Devices
    "devices/stw_device\.h|ti/drv/stw_lld/devices/stw_device\.h"
    "devices/stw_deviceIoexp\.h|ti/drv/stw_lld/devices/stw_deviceIoexp\.h"
    #OSAL
    "osal/bsp_safety_osal\.h|ti/drv/vps/include/osal/bsp_safety_osal\.h"
    "osal/bsp_osal\.h|ti/drv/vps/include/osal/bsp_osal\.h"
    "osal/bsp_osalCfg\.h|ti/drv/vps/include/osal/bsp_osalCfg\.h"
    #PM
    "pm/pmlib\.h|ti/drv/pm/pmlib\.h"
    "pmlib_clkrate\.h|ti/drv/pm/pmlib\.h"
    "pmlib_cpuidle\.h|ti/drv/pm/pmlib\.h"
    "pmlib_sysconfig\.h|ti/drv/pm/pmlib\.h"
    "pmlib_videopll\.h|ti/drv/pm/pmlib\.h"
    "pmlib_boardconfig\.h|ti/drv/pm/pmlib\.h"
    "pmlib/pmlib_clkrate\.h|ti/drv/pm/pmlib\.h"
    "pmlib/pmlib_cpuidle\.h|ti/drv/pm/pmlib\.h"
    "pmlib/pmlib_sysconfig\.h|ti/drv/pm/pmlib\.h"
    "pmlib/pmlib_videopll\.h|ti/drv/pm/pmlib\.h"
    "pmlib/pmlib_boardconfig\.h|ti/drv/pm/pmlib\.h"
    "pm/pmlib/pmlib_clkrate\.h|ti/drv/pm/pmlib\.h"
    "pm/pmlib/pmlib_cpuidle\.h|ti/drv/pm/pmlib\.h"
    "pm/pmlib/pmlib_sysconfig\.h|ti/drv/pm/pmlib\.h"
    "pm/pmlib/pmlib_videopll\.h|ti/drv/pm/pmlib\.h"
    "pm/pmlib/pmlib_boardconfig\.h|ti/drv/pm/pmlib\.h"
    "pm/pmhal\.h|ti/drv/pm/pmhal\.h"
    "pmhal_prcm\.h|ti/drv/pm/pmhal\.h"
    "pmhal_prcm_includes\.h|ti/drv/pm/pmhal\.h"
    "pmhal_prcm_includes\.h|ti/drv/pm/pmhal\.h"
    "pmhal_prcm_stats\.h|ti/drv/pm/pmhal\.h"
    "pmhal_ina226\.h|ti/drv/pm/pmhal\.h"
    "pmhal_mm\.h|ti/drv/pm/pmhal\.h"
    "pmhal_pmicComm\.h|ti/drv/pm/pmhal\.h"
    "pmhal_vm\.h|ti/drv/pm/pmhal\.h"
    "pmhal_cm\.h|ti/drv/pm/pmhal\.h"
    "pmhal_bgap\.h|ti/drv/pm/pmhal\.h"
    "pmhal_clocktree\.h|ti/drv/pm/pmhal\.h"
    "pmhal_videopll\.h|ti/drv/pm/pmhal\.h"
    "pmhal_pmic\.h|ti/drv/pm/pmhal\.h"
    "pmhal_sd\.h|ti/drv/pm/pmhal\.h"
    "pmhal_rm\.h|ti/drv/pm/pmhal\.h"
    "pmhal_prm_int\.h|ti/drv/pm/pmhal\.h"
    "hw_pmhal_data_names\.h|ti/drv/pm/pmhal\.h"
    "pmhal_mpu_lprm\.h|ti/drv/pm/pmhal\.h"
    "pmhal_pdm\.h|ti/drv/pm/pmhal\.h"
    "pmhal_i2cComm\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_prcm_stats\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_ina226\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_mm\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_pmicComm\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_vm\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_cm\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_bgap\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_clocktree\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_videopll\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_pmic\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_sd\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_rm\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_prm_int\.h|ti/drv/pm/pmhal\.h"
    "pmhal/hw_pmhal_data_names\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_mpu_lprm\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_pdm\.h|ti/drv/pm/pmhal\.h"
    "pmhal/pmhal_i2cComm\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal_prcm\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal_prcm_includes\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal_prcm_includes\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_prcm_stats\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_ina226\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_mm\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_pmicComm\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_vm\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_cm\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_bgap\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_clocktree\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_videopll\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_pmic\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_sd\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_rm\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_prm_int\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/hw_pmhal_data_names\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_mpu_lprm\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_pdm\.h|ti/drv/pm/pmhal\.h"
    "pm/pmhal/pmhal_i2cComm\.h|ti/drv/pm/pmhal\.h"
    "pm/pm_types\.h|ti/drv/pm/include/pm_types\.h"
    "pm_types\.h|ti/drv/pm/include/pm_types\.h"
    "pm/pm_utils\.h|ti/drv/pm/include/pm_utils\.h"
    "pm_utils\.h|ti/drv/pm/include/pm_utils\.h"
    "pmhal_lp8731\.h|ti/drv/pm/include/pmic/pmhal_lp8731\.h"
    "pmhal_lp8731_lp3907\.h|ti/drv/pm/include/pmic/pmhal_lp8731_lp3907\.h"
    "pmhal_lp8733\.h|ti/drv/pm/include/pmic/pmhal_lp8733\.h"
    "pmhal_tps659037\.h|ti/drv/pm/include/pmic/pmhal_tps659037\.h"
    "pmhal_tps659039\.h|ti/drv/pm/include/pmic/pmhal_tps659039\.h"
    "pmhal_tps65917\.h|ti/drv/pm/include/pmic/pmhal_tps65917\.h"
    "pmhal_lp87565\.h|ti/drv/pm/include/pmic/pmhal_lp87565\.h"
    #BSP LLD
    "uart/bsp_uart\.h|ti/drv/bsp_lld/uart/bsp_uart\.h"
    "mcspi/bsp_mcspi\.h|ti/drv/bsp_lld/mcspi/bsp_mcspi\.h"
    "i2c/bsp_i2c\.h|ti/drv/bsp_lld/i2c/bsp_i2c\.h"
    #STW VPS LIB
    "vps_dctrlDrv\.h|ti/drv/vps/include/dss/vps_dctrlDrv\.h"
    "vps_dssDrv\.h|ti/drv/vps/include/dss/vps_dssDrv\.h"
    "vps_vipDrv\.h|ti/drv/vps/include/vip/vps_vipDrv\.h"
    "common/vpscore\.h|ti/drv/vps/src/vpslib/common/vpscore\.h"
    "dispcore/vpscore_dctrl\.h|ti/drv/vps/src/vpslib/dispcore/vpscore_dctrl\.h"
    "dispcore/vpscore_dss\.h|ti/drv/vps/src/vpslib/dispcore/vpscore_dss\.h"
    "dispcore/vpscore_dssWb\.h|ti/drv/vps/src/vpslib/dispcore/vpscore_dssWb\.h"
    "captcore/vpscore_vip\.h|ti/drv/vps/src/vpslib/captcore/vpscore_vip\.h"
    #BSP VPS
    "boards/bsp_board\.h|ti/drv/vps/include/boards/bsp_board\.h"
    "common/bsp_config\.h|ti/drv/vps/include/common/bsp_config\.h"
    "common/bsp_common\.h|ti/drv/vps/include/common/bsp_common\.h"
    "common/bsp_utilsQue\.h|ti/drv/vps/include/common/bsp_utilsQue\.h"
    "common/bsp_cfgMem\.h|ti/drv/vps/include/common/bsp_cfgMem\.h"
    "devices/bsp_lcdController\.h|ti/drv/vps/include/devices/bsp_lcdController\.h"
    "devices/bsp_sii9022a\.h|ti/drv/vps/include/devices/bsp_sii9022a\.h"
    "devices/bsp_videoEncoder\.h|ti/drv/vps/include/devices/bsp_videoEncoder\.h"
    "devices/bsp_tvp5158\.h|ti/drv/vps/include/devices/bsp_tvp5158\.h"
    "devices/bsp_pga450\.h|ti/drv/vps/include/devices/bsp_pga450\.h"
    "devices/bsp_videoSensor\.h|ti/drv/vps/include/devices/bsp_videoSensor\.h"
    "devices/bsp_ar12xx\.h|ti/drv/vps/include/devices/bsp_ar12xx\.h"
    "devices/bsp_videoDecoder\.h|ti/drv/vps/include/devices/bsp_videoDecoder\.h"
    "devices/bsp_ioexp\.h|ti/drv/vps/include/devices/bsp_ioexp\.h"
    "devices/bsp_device\.h|ti/drv/vps/include/devices/bsp_device\.h"
    "vps/vps_m2m\.h|ti/drv/vps/include/vpe/vps_m2m\.h"
    "vps/vps_displayCtrl\.h|ti/drv/vps/include/vps_displayCtrl\.h"
    "vps/vps_displayDss\.h|ti/drv/vps/include/dss/vps_displayDss\.h"
    "vps/vps_m2mIntf\.h|ti/drv/vps/include/vps_m2mIntf\.h"
    "vps/vps_m2mVpe\.h|ti/drv/vps/include/vpe/vps_m2mVpe\.h"
    "vps/vps_captureVip\.h|ti/drv/vps/include/vip/vps_captureVip\.h"
    "vps/vps\.h|ti/drv/vps/include/vps\.h"
    "vps/vps_display\.h|ti/drv/vps/include/vps_display\.h"
    "vps/vps_control\.h|ti/drv/vps/include/vps_control\.h"
    "vps/vps_captureDssWb\.h|ti/drv/vps/include/dss/vps_captureDssWb\.h"
    "vps/iss/vps_m2mIss\.h|ti/drv/vps/include/iss/vps_m2mIss\.h"
    "vps/vps_captureIss\.h|ti/drv/vps/include/iss/vps_captureIss\.h"
    "vps/vps_capture\.h|ti/drv/vps/include/vps_capture\.h"
    "fvid2/fvid2\.h|ti/drv/vps/include/fvid2/fvid2\.h"
    "platforms/bsp_platform\.h|ti/drv/vps/include/platforms/bsp_platform\.h"
    "bsputils_app\.h|ti/drv/vps/examples/utility/bsputils_app\.h"
    "bsputils_buf\.h|ti/drv/vps/examples/utility/bsputils_buf\.h"
    "bsputils_fileio\.h|ti/drv/vps/examples/utility/bsputils_fileio\.h"
    "bsputils_lvds\.h|ti/drv/vps/examples/utility/bsputils_lvds\.h"
    "bsputils_mbx\.h|ti/drv/vps/examples/utility/bsputils_mbx\.h"
    "bsputils_mem\.h|ti/drv/vps/examples/utility/bsputils_mem\.h"
    "bsputils_prf\.h|ti/drv/vps/examples/utility/bsputils_prf\.h"
    "bsputils_tiler\.h|ti/drv/vps/examples/utility/bsputils_tiler\.h"
    "bsputils_tsk\.h|ti/drv/vps/examples/utility/bsputils_tsk\.h"
    "bsputils_uart\.h|ti/drv/vps/examples/utility/bsputils_uart\.h"
    "bsputils_ub960\.h|ti/drv/vps/examples/utility/bsputils_ub960\.h"
    "common/bsp_types\.h|ti/drv/vps/include/common/bsp_types\.h"
    "common/trace\.h|ti/drv/vps/include/common/trace\.h"
    "common/stw_config\.h|ti/drv/vps/include/common/stw_config\.h"
    "common/bsp_utils\.h|ti/drv/vps/include/common/bsp_utils\.h"
    "common/stw_utils\.h|ti/drv/vps/include/common/bsp_utils\.h"
    "common/stw_types\.h|ti/csl/csl_types\.h"
    "common/stw_dataTypes\.h|ti/csl/tistdtypes\.h"
    "vps/vps_dataTypes\.h|ti/drv/vps/include/vps_dataTypes\.h"
    "vps/vps_cfgDss\.h|ti/drv/vps/include/dss/vps_cfgDss\.h"
    "vps/vps_captureVipDataTypes\.h|ti/drv/vps/include/vip/vps_captureVipDataTypes\.h"
    "vps/vps_cfgCsc\.h|ti/drv/vps/include/vps_cfgCsc\.h"
    "vps/vps_cfgMem\.h|ti/drv/vps/include/vps_cfgMem\.h"
    "vps/vps_cfgVipParser\.h|ti/drv/vps/include/vip/vps_cfgVipParser\.h"
    "vps/vps_advCfgDei\.h|ti/drv/vps/include/vpe/vps_advCfgDei\.h"
    "vps/vps_displayCtrlDataTypes\.h|ti/drv/vps/include/vps_displayCtrlDataTypes\.h"
    "vps/iss/vps_cfgsimcop\.h|ti/drv/vps/include/iss/vps_cfgsimcop\.h"
    "vps/iss/vps_isscommon\.h|ti/drv/vps/include/iss/vps_isscommon\.h"
    "vps/iss/vps_cfgipipeif\.h|ti/drv/vps/include/iss/vps_cfgipipeif\.h"
    "vps/iss/vps_cfgcal\.h|ti/drv/vps/include/iss/vps_cfgcal\.h"
    "vps/iss/vps_cfgldc\.h|ti/drv/vps/include/iss/vps_cfgldc\.h"
    "vps/iss/vps_cfgvtnf\.h|ti/drv/vps/include/iss/vps_cfgvtnf\.h"
    "vps/iss/vps_cfgglbce\.h|ti/drv/vps/include/iss/vps_cfgglbce\.h"
    "vps/iss/vps_cfgrsz\.h|ti/drv/vps/include/iss/vps_cfgrsz\.h"
    "vps/iss/vps_cfgipipe\.h|ti/drv/vps/include/iss/vps_cfgipipe\.h"
    "vps/iss/vps_cfgisp\.h|ti/drv/vps/include/iss/vps_cfgisp\.h"
    "vps/iss/vps_cfgisif\.h|ti/drv/vps/include/iss/vps_cfgisif\.h"
    "vps/iss/vps_cfgcnf\.h|ti/drv/vps/include/iss/vps_cfgcnf\.h"
    "vps/iss/vps_cfgnsf3\.h|ti/drv/vps/include/iss/vps_cfgnsf3\.h"
    "vps/iss/vps_cfgh3a\.h|ti/drv/vps/include/iss/vps_cfgh3a\.h"
    "vps/vps_cfgSc\.h|ti/drv/vps/include/vps_cfgSc\.h"
    "vps/vps_cfgDei\.h|ti/drv/vps/include/vpe/vps_cfgDei\.h"
    "fvid2/fvid2_dataTypes\.h|ti/drv/vps/include/fvid2/fvid2_dataTypes\.h"
)

if [ "$enable_info" == "yes" ]; then
    echo "Starterware/BSP include path to PDK include path replacement script!!"
    echo "Date: $date_print"
    echo ""
fi

############## Replace include paths ##############
cd $dest_dir

for str in "${file_replace_list[@]}"
do
    find_str=`echo $str | cut -d"|" -f1`
    rep_str=`echo $str | cut -d"|" -f2`

    #Remove \ from string
    print_find_str="${find_str//\\}"
    print_rep_str="${rep_str//\\}"

    #Check if the file exists in PDK
    if [ ! -f "$pdk_dir/packages/$print_rep_str" ]; then
        echo "[ERROR] $pdk_dir/packages/$print_rep_str file not found in PDK repo!!"
    fi

    #Find and replace if found
    #Match any #include with muliple spaces and with "" or <> type file include
    if grep -r -q -I "#include *[\"<]$find_str[\">]" * ; then
        if [ "$enable_info" == "yes" ]; then
            printf "[INFO] Replacing: %-35s -> %s\n" $print_find_str $print_rep_str;
        fi
        grep -r -l -I "#include *[\"<]$find_str[\">]" * | xargs sed -i -e "s|#include\( *\)\([\",<]\)$find_str\([\",>]\)|#include <$rep_str>|g"
    else
        if grep -r -q -I "#include *[\"<].*\/$find_str[\">]" * ; then
            if [ "$enable_info" == "yes" ]; then
                echo "[WARN] Ignoring : $print_find_str as include path has different folder prefix. Cross check and fix manually to $print_rep_str!!"
            fi
        else
            if [ "$enable_info" == "yes" ]; then
                echo "[INFO] Ignoring : $print_find_str"
            fi
        fi
    fi
done

exit
