# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_vec_bin_image_erode_single_pixel
TEST_BENCH = $(FILE)_tb
include ../../../common/Makefile.wincommon

