# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_FilterPoly
CFILES = EVEGenFilterCoeffs.c
TEST_BENCH = $(FILE)_tb
EVE_LCF = ./linker_cama.cmd
include ../../../common/Makefile.wincommon

