/*
 * Copyright (C) 2013 Texas Instruments Incorporated - http://www.ti.com/
 *
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*! ============================================================================
 *   \file  cslr_gmacsw_stats.h
 *
 *   @path  $(CSLPATH)\inc
 *
 *   @desc  This file contains the Register Descriptions for GMAC_SW
 *
 *  ============================================================================
 */

#ifndef CSLR_GMACSW_STATS_H_
#define CSLR_GMACSW_STATS_H_

#ifdef __cplusplus
extern "C" {
#endif


/*---------------------------------------------------------------------------*\
|                                Header Files                                 |
\*---------------------------------------------------------------------------*/

/* Standard language headers */
#include <stdlib.h>
#include <stdint.h>

/* OS/Posix headers */

/* Project dependency headers */


/*---------------------------------------------------------------------------*\
|                           Global Typedefs/Enums                             |
\*---------------------------------------------------------------------------*/

typedef struct
{
#if defined(DEVICE_CENTAURUS)
    volatile uint8_t  RSVD0[0x400U];          /* offset since union is used for Centaurus */
#endif
    volatile uint32_t RXGOODFRAMES;           /* 0x000U */
    volatile uint32_t RXBROADCASTFRAMES;
    volatile uint32_t RXMULTICASTFRAMES;
    volatile uint32_t RXPAUSEFRAMES;
    volatile uint32_t RXCRCERRORS;            /* 0x010U */
    volatile uint32_t RXALIGNCODEERRORS;
    volatile uint32_t RXOVERSIZEDFRAMES;
    volatile uint32_t RXJABBERFRAMES;
    volatile uint32_t RXUNDERSIZEDFRAMES;     /* 0x020U */
    volatile uint32_t RXFRAGMENTS;
    volatile uint8_t  RSVD1[8];
    volatile uint32_t RXOCTETS;               /* 0x030U */
    volatile uint32_t TXGOODFRAMES;
    volatile uint32_t TXBROADCASTFRAMES;
    volatile uint32_t TXMULTICASTFRAMES;
    volatile uint32_t TXPAUSEFRAMES;          /* 0x040U */
    volatile uint32_t TXDEFERREDFRAMES;
    volatile uint32_t TXCOLLISIONFRAMES;
    volatile uint32_t TXSINGLECOLLFRAMES;
    volatile uint32_t TXMULTCOLLFRAMES;       /* 0x050U */
    volatile uint32_t TXEXCESSIVECOLLISIONS;
    volatile uint32_t TXLATECOLLISIONS;
    volatile uint32_t TXUNDERRUN;
    volatile uint32_t TXCARRIERSENSEERRORS;   /* 0x060U */
    volatile uint32_t TXOCTETS;
    volatile uint32_t OCTETFRAMES64;
    volatile uint32_t OCTETFRAMES65T127;
    volatile uint32_t OCTETFRAMES128T255;     /* 0x070U */
    volatile uint32_t OCTETFRAMES256T511;
    volatile uint32_t OCTETFRAMES512T1023;
    volatile uint32_t OCTETFRAMES1024TUP;
    volatile uint32_t NETOCTETS;              /* 0x080U */
    volatile uint32_t RXSOFOVERRUNS;
    volatile uint32_t RXMOFOVERRUNS;
    volatile uint32_t RXDMAOVERRUNS;
    volatile uint8_t  RSVD2[112];             /* 0x090U */
}
CSL_GMACSW_statsRegs;


/*---------------------------------------------------------------------------*\
|                           Global Macros/Defines                             |
\*---------------------------------------------------------------------------*/

/* Field Definition Macros */

/* RXGOODFRAMES */

#define CSL_GMACSW_RXGOODFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXGOODFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXGOODFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXGOODFRAMES_RESETVAL (0x00000000U)

/* RXBROADCASTFRAMES */

#define CSL_GMACSW_RXBROADCASTFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXBROADCASTFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXBROADCASTFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXBROADCASTFRAMES_RESETVAL (0x00000000U)

/* RXMULTICASTFRAMES */

#define CSL_GMACSW_RXMULTICASTFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXMULTICASTFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXMULTICASTFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXMULTICASTFRAMES_RESETVAL (0x00000000U)

/* RXPAUSEFRAMES */

#define CSL_GMACSW_RXPAUSEFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXPAUSEFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXPAUSEFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXPAUSEFRAMES_RESETVAL (0x00000000U)

/* RXCRCERRORS */

#define CSL_GMACSW_RXCRCERRORS_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXCRCERRORS_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXCRCERRORS_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXCRCERRORS_RESETVAL (0x00000000U)

/* RXALIGNCODEERRORS */

#define CSL_GMACSW_RXALIGNCODEERRORS_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXALIGNCODEERRORS_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXALIGNCODEERRORS_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXALIGNCODEERRORS_RESETVAL (0x00000000U)

/* RXOVERSIZEDFRAMES */

#define CSL_GMACSW_RXOVERSIZEDFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXOVERSIZEDFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXOVERSIZEDFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXOVERSIZEDFRAMES_RESETVAL (0x00000000U)

/* RXJABBERFRAMES */

#define CSL_GMACSW_RXJABBERFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXJABBERFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXJABBERFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXJABBERFRAMES_RESETVAL (0x00000000U)

/* RXUNDERSIZEDFRAMES */

#define CSL_GMACSW_RXUNDERSIZEDFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXUNDERSIZEDFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXUNDERSIZEDFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXUNDERSIZEDFRAMES_RESETVAL (0x00000000U)

/* RXFRAGMENTS */

#define CSL_GMACSW_RXFRAGMENTS_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXFRAGMENTS_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXFRAGMENTS_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXFRAGMENTS_RESETVAL (0x00000000U)

/* RXOCTETS */

#define CSL_GMACSW_RXOCTETS_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXOCTETS_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXOCTETS_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXOCTETS_RESETVAL (0x00000000U)

/* TXGOODFRAMES */

#define CSL_GMACSW_TXGOODFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_TXGOODFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_TXGOODFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_TXGOODFRAMES_RESETVAL (0x00000000U)

/* TXBROADCASTFRAMES */

#define CSL_GMACSW_TXBROADCASTFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_TXBROADCASTFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_TXBROADCASTFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_TXBROADCASTFRAMES_RESETVAL (0x00000000U)

/* TXMULTICASTFRAMES */

#define CSL_GMACSW_TXMULTICASTFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_TXMULTICASTFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_TXMULTICASTFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_TXMULTICASTFRAMES_RESETVAL (0x00000000U)

/* TXPAUSEFRAMES */

#define CSL_GMACSW_TXPAUSEFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_TXPAUSEFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_TXPAUSEFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_TXPAUSEFRAMES_RESETVAL (0x00000000U)

/* TXDEFERREDFRAMES */

#define CSL_GMACSW_TXDEFERREDFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_TXDEFERREDFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_TXDEFERREDFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_TXDEFERREDFRAMES_RESETVAL (0x00000000U)

/* TXCOLLISIONFRAMES */

#define CSL_GMACSW_TXCOLLISIONFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_TXCOLLISIONFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_TXCOLLISIONFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_TXCOLLISIONFRAMES_RESETVAL (0x00000000U)

/* TXSINGLECOLLFRAMES */

#define CSL_GMACSW_TXSINGLECOLLFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_TXSINGLECOLLFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_TXSINGLECOLLFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_TXSINGLECOLLFRAMES_RESETVAL (0x00000000U)

/* TXMULTCOLLFRAMES */

#define CSL_GMACSW_TXMULTCOLLFRAMES_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_TXMULTCOLLFRAMES_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_TXMULTCOLLFRAMES_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_TXMULTCOLLFRAMES_RESETVAL (0x00000000U)

/* TXEXCESSIVECOLLISIONS */

#define CSL_GMACSW_TXEXCESSIVECOLLISIONS_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_TXEXCESSIVECOLLISIONS_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_TXEXCESSIVECOLLISIONS_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_TXEXCESSIVECOLLISIONS_RESETVAL (0x00000000U)

/* TXLATECOLLISIONS */

#define CSL_GMACSW_TXLATECOLLISIONS_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_TXLATECOLLISIONS_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_TXLATECOLLISIONS_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_TXLATECOLLISIONS_RESETVAL (0x00000000U)

/* TXUNDERRUN */

#define CSL_GMACSW_TXUNDERRUN_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_TXUNDERRUN_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_TXUNDERRUN_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_TXUNDERRUN_RESETVAL (0x00000000U)

/* TXCARRIERSENSEERRORS */

#define CSL_GMACSW_TXCARRIERSENSEERRORS_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_TXCARRIERSENSEERRORS_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_TXCARRIERSENSEERRORS_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_TXCARRIERSENSEERRORS_RESETVAL (0x00000000U)

/* TXOCTETS */

#define CSL_GMACSW_TXOCTETS_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_TXOCTETS_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_TXOCTETS_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_TXOCTETS_RESETVAL (0x00000000U)

/* OCTETFRAMES64 */

#define CSL_GMACSW_OCTETFRAMES64_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_OCTETFRAMES64_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_OCTETFRAMES64_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_OCTETFRAMES64_RESETVAL (0x00000000U)

/* OCTETFRAMES65T127 */

#define CSL_GMACSW_OCTETFRAMES65T127_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_OCTETFRAMES65T127_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_OCTETFRAMES65T127_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_OCTETFRAMES65T127_RESETVAL (0x00000000U)

/* OCTETFRAMES128T255 */

#define CSL_GMACSW_OCTETFRAMES128T255_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_OCTETFRAMES128T255_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_OCTETFRAMES128T255_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_OCTETFRAMES128T255_RESETVAL (0x00000000U)

/* OCTETFRAMES256T511 */

#define CSL_GMACSW_OCTETFRAMES256T511_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_OCTETFRAMES256T511_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_OCTETFRAMES256T511_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_OCTETFRAMES256T511_RESETVAL (0x00000000U)

/* OCTETFRAMES512T1023 */

#define CSL_GMACSW_OCTETFRAMES512T1023_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_OCTETFRAMES512T1023_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_OCTETFRAMES512T1023_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_OCTETFRAMES512T1023_RESETVAL (0x00000000U)

/* OCTETFRAMES1024TUP */

#define CSL_GMACSW_OCTETFRAMES1024TUP_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_OCTETFRAMES1024TUP_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_OCTETFRAMES1024TUP_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_OCTETFRAMES1024TUP_RESETVAL (0x00000000U)

/* NETOCTETS */

#define CSL_GMACSW_NETOCTETS_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_NETOCTETS_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_NETOCTETS_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_NETOCTETS_RESETVAL (0x00000000U)

/* RXSOFOVERRUNS */

#define CSL_GMACSW_RXSOFOVERRUNS_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXSOFOVERRUNS_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXSOFOVERRUNS_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXSOFOVERRUNS_RESETVAL (0x00000000U)

/* RXMOFOVERRUNS */

#define CSL_GMACSW_RXMOFOVERRUNS_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXMOFOVERRUNS_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXMOFOVERRUNS_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXMOFOVERRUNS_RESETVAL (0x00000000U)

/* RXDMAOVERRUNS */

#define CSL_GMACSW_RXDMAOVERRUNS_COUNT_MASK (0xFFFFFFFFU)
#define CSL_GMACSW_RXDMAOVERRUNS_COUNT_SHIFT (0x00000000U)
#define CSL_GMACSW_RXDMAOVERRUNS_COUNT_RESETVAL (0x00000000U)

#define CSL_GMACSW_RXDMAOVERRUNS_RESETVAL (0x00000000U)


/*---------------------------------------------------------------------------*\
|                                 End of File                                 |
\*---------------------------------------------------------------------------*/

#ifdef __cplusplus
}
#endif

#endif /* CSLR_GMACSW_STATS_H_ */

