# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_contrast_stretching
TEST_BENCH = $(FILE)_tb
CFILES = ../src_C/$(FILE)_cn.c $(FILE)_config.c

include ../../../common/Makefile.wincommon
TARGETLD_FLAGS = --define VCOP_CAMA
