# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_alpha_blend_yuv420nv12
TEST_BENCH = $(FILE)_tb
CFILES = ../src_kernelC/$(FILE)_host.c $(FILE)_config.c

include ../../../common/Makefile.wincommon
