# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_nonMaxSuppress_mxn_32s
TEST_BENCH = $(FILE)_tb

CFILES = ../src_C/$(FILE)_c.c $(FILE)_config.c

include ../../../common/Makefile.wincommon
TARGETLD_FLAGS = --define VCOP_CAMA
