.bd B 3
.TH cg-arp32 1 "Jan 05, 2015" "TI Tools" "TI Code Generation Tools"
.SH NAME
cg-arp32 - Code Generator
.SH SYNOPSIS
.B cg-arp32
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
The code generator creates assembly code and debugging information from the internal compiler representation.  The Code Generator should not be invoked directly; it should be invoked via the shell (cl).  For more information on the code generator, see the 
.B Optimizing C Compiler User's Guide.

This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2015, Texas Instruments, Inc.
