.bd B 3
.TH dem-arp32 1 "Jan 05, 2015" "TI Tools" "TI Code Generation Tools"
.SH NAME
dem-arp32 - Demangler
.SH SYNOPSIS
.B dem-arp32
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
The demangler decodes mangled C++ names
.SH OPTIONS
The following options are accepted by this tool:
.SS Options:
.SS
.TP
--abi=eabi
Used to specify the application binary interface.
.TP
--d
Print debug messages
.TP
--diag_wrap[=on,off]
Set diagnostic messages to wrap at 79 columns (on) or not (off). The argument to the option is optional, and if not specified it will default to: on
.TP
-h
Print a help message that includes usage and option information.
.TP
-o=file
Full filename of the output file.
.TP
-q
Reduce the number of messages generated while executing.
.SH EXIT STATUS
The following error values are returned:
.PD 0
.TP 10
.B 0
Successful completion.
.TP
.B >0
Unsuccessful completion; an error occured.
.PD
.SH COPYRIGHT
.TP
Copyright (c) 2015, Texas Instruments, Inc.
