.bd B 3
.TH embed-arp32 1 "Jan 05, 2015" "TI Tools" "TI Code Generation Tools"
.SH NAME
embed-arp32 - Embed Utility
.SH SYNOPSIS
.B embed-arp32
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Embed ICODE into an object file as a section.
.SH OPTIONS
The following options are accepted by this tool:
.SS Options:
.SS
.TP
--diag_wrap[=on,off]
Set diagnostic messages to wrap at 79 columns (on) or not (off). The argument to the option is optional, and if not specified it will default to: on
.TP
-h
Print a help message that includes usage and option information.
.SH EXIT STATUS
The following error values are returned:
.PD 0
.TP 10
.B 0
Successful completion.
.TP
.B >0
Unsuccessful completion; an error occured.
.PD
.SH COPYRIGHT
.TP
Copyright (c) 2015, Texas Instruments, Inc.
