.bd B 3
.TH ilk-arp32 1 "Jan 05, 2015" "TI Tools" "TI Code Generation Tools"
.SH NAME
ilk-arp32 - Ifile Linker
.SH SYNOPSIS
.B ilk-arp32
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Links multiple input intermediate files into one output file.  Used for program-level compilation.
.SH OPTIONS
The following options are accepted by this tool:
.SS Options:
.SS
.TP
--diag_error=id
Suppress diagnostic <id>
.TP
--diag_remark=id
Suppress diagnostic <id>
.TP
--diag_suppress=id
Suppress diagnostic <id>
.TP
--diag_warning=id
Treat diagnostic <id> as warning
.TP
--diag_wrap[=on,off]
Set diagnostic messages to wrap at 79 columns (on) or not (off). The argument to the option is optional, and if not specified it will default to: on
.TP
--display_error_number
Emit diagnostic identifier numbers
.TP
-h
Print a help message that includes usage and option information.
.TP
--issue_remarks
Issue remarks
.TP
-pdew
Treat warnings as errors
.SH EXIT STATUS
The following error values are returned:
.PD 0
.TP 10
.B 0
Successful completion.
.TP
.B >0
Unsuccessful completion; an error occured.
.PD
.SH COPYRIGHT
.TP
Copyright (c) 2015, Texas Instruments, Inc.
