.bd B 3
.TH libinfo-arp32 1 "Jan 05, 2015" "TI Tools" "TI Code Generation Tools"
.SH NAME
libinfo-arp32 - Library Information Archiver
.SH SYNOPSIS
.B libinfo-arp32
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Builds an archive of information about available libraries.
This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2015, Texas Instruments, Inc.
