.bd B 3
.TH opt-arp32 1 "Jan 05, 2015" "TI Tools" "TI Code Generation Tools"
.SH NAME
opt-arp32 - Optimizer
.SH SYNOPSIS
.B opt-arp32
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
The Optimizer optimizes the parser generated internal compiler representation. The Optimizer should not be invoked directly; it should be invoked via the shell (cl).  For more information on the Optimizer, see the 
.B Optimizing C Compiler User's Guide.

This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2015, Texas Instruments, Inc.
