.bd B 3
.TH vcc-arp32 1 "Jan 05, 2015" "TI Tools" "TI Code Generation Tools"
.SH NAME
vcc-arp32 - VCOP-C Kernel Compiler
.SH SYNOPSIS
.B vcc-arp32
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Used to translate high level VCOP-C Kernels into
standard C for processing by the C compiler.
This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2015, Texas Instruments, Inc.
