/*
*
* Copyright (c) 2008-2017 Texas Instruments Incorporated
*
* All rights reserved not granted herein.
*
* Limited License.
*
* Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
* license under copyrights and patents it now or hereafter owns or controls to make,
* have made, use, import, offer to sell and sell ("Utilize") this software subject to the
* terms herein.  With respect to the foregoing patent license, such license is granted
* solely to the extent that any such patent is necessary to Utilize the software alone.
* The patent license shall not apply to any combinations which include this software,
* other than combinations with devices manufactured by or for TI ("TI Devices").
* No hardware patent is licensed hereunder.
*
* Redistributions must preserve existing copyright notices and reproduce this license
* (including the above copyright notice and the disclaimer and (if applicable) source
* code license limitations below) in the documentation and/or other materials provided
* with the distribution
*
* Redistribution and use in binary form, without modification, are permitted provided
* that the following conditions are met:
*
* *       No reverse engineering, decompilation, or disassembly of this software is
* permitted with respect to any software provided in binary form.
*
* *       any redistribution and use are licensed by TI for use only with TI Devices.
*
* *       Nothing shall obligate TI to provide you with source code for the software
* licensed and provided to you in object code.
*
* If software source code is provided to you, modification and redistribution of the
* source code are permitted provided that the following conditions are met:
*
* *       any redistribution and use of the source code, including any resulting derivative
* works, are licensed by TI for use only with TI Devices.
*
* *       any redistribution and use of any object code compiled from the source code
* and any resulting derivative works, are licensed by TI for use only with TI Devices.
*
* Neither the name of Texas Instruments Incorporated nor the names of its suppliers
*
* may be used to endorse or promote products derived from this software without
* specific prior written permission.
*
* DISCLAIMER.
*
* THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS
* OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
* BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/



/**
 *  @Component:   MLB
 *
 *  @Filename:    mlb_cred.h
 *
 *  @Description: Mailbox module registers 
 *
 *  Generated by: Socrates CRED generator prototype
 *
 *//* ====================================================================== */

#ifndef __MLB_H
#define __MLB_H

#ifdef __cplusplus
extern "C"
{
#endif

/*
 * Instance MAILBOX0 of component MLB mapped in NETRA at address 0x480C8000
 * Instance IVAHD0__MAILBOX of component MLB mapped in NETRA at address 0x5805A800
 * Instance IVAHD1__MAILBOX of component MLB mapped in NETRA at address 0x5A05A800
 */

 /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
 *//*------------------------------------------------------------------------ */
#define BITFIELD BITFIELD_32

/*
 *  List of Register arrays for component MLB
 *
 */


/*
 *  List of bundle arrays for component MLB
 *
 */
/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_FIFOSTATUS_REGSET_0_15
 *
 * @BRIEF        Bundle description is not available
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_FIFOSTATUS_REGSET_0_15                0x80u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_FIFOSTATUS_REGSET_0_15__ELSIZE
 *
 * @BRIEF        MAILBOX_FIFOSTATUS_REGSET_0_15 bundle array element size in Bytes
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_FIFOSTATUS_REGSET_0_15__ELSIZE        0x4u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_FIFOSTATUS_REGSET_0_15__NELEMS
 *
 * @BRIEF        MAILBOX_FIFOSTATUS_REGSET_0_15 bundle array number of elements
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_FIFOSTATUS_REGSET_0_15__NELEMS        6

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQ_REGSET_0_3
 *
 * @BRIEF        Bundle description is not available
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQ_REGSET_0_3                        0x100u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQ_REGSET_0_3__ELSIZE
 *
 * @BRIEF        MAILBOX_IRQ_REGSET_0_3 bundle array element size in Bytes
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQ_REGSET_0_3__ELSIZE                0x10u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQ_REGSET_0_3__NELEMS
 *
 * @BRIEF        MAILBOX_IRQ_REGSET_0_3 bundle array number of elements
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQ_REGSET_0_3__NELEMS                4

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_MESSAGE_REGSET_0_15
 *
 * @BRIEF        Bundle description is not available
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_MESSAGE_REGSET_0_15                   0x40u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_MESSAGE_REGSET_0_15__ELSIZE
 *
 * @BRIEF        MAILBOX_MESSAGE_REGSET_0_15 bundle array element size in Bytes
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_MESSAGE_REGSET_0_15__ELSIZE           0x4u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_MESSAGE_REGSET_0_15__NELEMS
 *
 * @BRIEF        MAILBOX_MESSAGE_REGSET_0_15 bundle array number of elements
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_MESSAGE_REGSET_0_15__NELEMS           6

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_MSGSTATUS_REGSET_0_15
 *
 * @BRIEF        Bundle description is not available
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_MSGSTATUS_REGSET_0_15                 0xC0u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_MSGSTATUS_REGSET_0_15__ELSIZE
 *
 * @BRIEF        MAILBOX_MSGSTATUS_REGSET_0_15 bundle array element size in Bytes
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_MSGSTATUS_REGSET_0_15__ELSIZE         0x4u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_MSGSTATUS_REGSET_0_15__NELEMS
 *
 * @BRIEF        MAILBOX_MSGSTATUS_REGSET_0_15 bundle array number of elements
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_MSGSTATUS_REGSET_0_15__NELEMS         6


/*
 *  List of bundles for component MLB
 *
 */

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_FIFOSTATUS__OFFSET
 *
 * @BRIEF        Register MAILBOX_FIFOSTATUS offset in bundle MAILBOX_FIFOSTATUS_REGSET_0_15 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_FIFOSTATUS__OFFSET                    0x0u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW__OFFSET
 *
 * @BRIEF        Register MAILBOX_IRQSTATUS_RAW offset in bundle MAILBOX_IRQ_REGSET_0_3 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW__OFFSET                 0x0u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR__OFFSET
 *
 * @BRIEF        Register MAILBOX_IRQSTATUS_CLR offset in bundle MAILBOX_IRQ_REGSET_0_3 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR__OFFSET                 0x4u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET__OFFSET
 *
 * @BRIEF        Register MAILBOX_IRQENABLE_SET offset in bundle MAILBOX_IRQ_REGSET_0_3 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET__OFFSET                 0x8u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR__OFFSET
 *
 * @BRIEF        Register MAILBOX_IRQENABLE_CLR offset in bundle MAILBOX_IRQ_REGSET_0_3 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR__OFFSET                 0xCu

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_MESSAGE__OFFSET
 *
 * @BRIEF        Register MAILBOX_MESSAGE offset in bundle MAILBOX_MESSAGE_REGSET_0_15 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_MESSAGE__OFFSET                       0x0u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_MSGSTATUS__OFFSET
 *
 * @BRIEF        Register MAILBOX_MSGSTATUS offset in bundle MAILBOX_MSGSTATUS_REGSET_0_15 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_MSGSTATUS__OFFSET                     0x0u


/*
 * List of registers for component MLB
 *
 */

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_REVISION
 *
 * @BRIEF        This register contains the IP revision code  
 *                 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_REVISION                              0x0u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_SYSCONFIG
 *
 * @BRIEF        This register controls the various parameters of the OCP 
 *               interface  
 *                 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_SYSCONFIG                             0x10u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_MESSAGE
 *
 * @BRIEF        The message register stores the next to be read message of 
 *               the mailbox X  
 *                 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_MESSAGE                               0x40u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_FIFOSTATUS
 *
 * @BRIEF        The FIFO status register has the status related to the 
 *               mailbox internal FIFO  
 *                 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_FIFOSTATUS                            0x80u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_MSGSTATUS
 *
 * @BRIEF        The message status register has the status of the messages 
 *               in the mailbox  
 *                 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_MSGSTATUS                             0xC0u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW
 *
 * @BRIEF        The interrupt status register has the status for each event 
 *               that may be responsible for the generation of an interrupt 
 *               to the corresponding user - write 1 to a given bit sets this 
 *               bit  
 *               (note : HW reset value is 0x0, but first value that can be 
 *               seen by SW is 0x0AAA) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW                         0x100u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR
 *
 * @BRIEF        The interrupt status register has the status combined with 
 *               irq-enable for each event that may be responsible for the 
 *               generation of an interrupt to the corresponding user  
 *               - write 1 to a given bit resets this bit 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR                         0x104u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET
 *
 * @BRIEF        The interrupt enable register enables to mask/unmask the 
 *               module internal source of interrupt to the corresponding 
 *               user  
 *               This register is write 1 to set. 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET                         0x108u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR
 *
 * @BRIEF        The interrupt enable register enables to mask/unmask the 
 *               module internal source of interrupt to the corresponding 
 *               user.  
 *               This register is write 1 to clear. 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR                         0x10Cu

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQ_EOI
 *
 * @BRIEF        This register is used for the software EOI clearance of the 
 *               pulse. 
 *               This register being write only gives 0 on read. 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQ_EOI                               0x140u


/*
 * List of register bitfields for component MLB
 *
 */
 
/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_REVISION__SCHEME   
 *
 * @BRIEF        Not defined yet - (RO) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_REVISION__SCHEME                 BITFIELD(31, 30)
#define MLB__MAILBOX_REVISION__SCHEME__POS            30

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_REVISION__FUNC   
 *
 * @BRIEF        Not defined yet - (RO) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_REVISION__FUNC                   BITFIELD(27, 16)
#define MLB__MAILBOX_REVISION__FUNC__POS              16

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_REVISION__RTL   
 *
 * @BRIEF        Not defined yet - (RO) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_REVISION__RTL                    BITFIELD(15, 11)
#define MLB__MAILBOX_REVISION__RTL__POS               11

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_REVISION__MAJOR   
 *
 * @BRIEF        IP-Major Revision - (RO) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_REVISION__MAJOR                  BITFIELD(10, 8)
#define MLB__MAILBOX_REVISION__MAJOR__POS             8

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_REVISION__CUSTOM   
 *
 * @BRIEF        Not Defined Yet - (RO) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_REVISION__CUSTOM                 BITFIELD(7, 6)
#define MLB__MAILBOX_REVISION__CUSTOM__POS            6

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_REVISION__MINOR   
 *
 * @BRIEF        IP-Minor Revision - (RO) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_REVISION__MINOR                  BITFIELD(5, 0)
#define MLB__MAILBOX_REVISION__MINOR__POS             0

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_SYSCONFIG__SIDLEMODE   
 *
 * @BRIEF        Idle Mode - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_SYSCONFIG__SIDLEMODE             BITFIELD(3, 2)
#define MLB__MAILBOX_SYSCONFIG__SIDLEMODE__POS        2

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_SYSCONFIG__SOFTRESET   
 *
 * @BRIEF        Softreset - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_SYSCONFIG__SOFTRESET             BITFIELD(0, 0)
#define MLB__MAILBOX_SYSCONFIG__SOFTRESET__POS        0

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_MESSAGE__MESSAGEVALUEMBM   
 *
 * @BRIEF        Message in Mailbox m - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_MESSAGE__MESSAGEVALUEMBM         BITFIELD(31, 0)
#define MLB__MAILBOX_MESSAGE__MESSAGEVALUEMBM__POS    0

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_FIFOSTATUS__FIFOFULLMBM   
 *
 * @BRIEF        Full flag for Mailbox m - (RO) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_FIFOSTATUS__FIFOFULLMBM          BITFIELD(0, 0)
#define MLB__MAILBOX_FIFOSTATUS__FIFOFULLMBM__POS     0

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_MSGSTATUS__NBOFMSGMBM   
 *
 * @BRIEF        Number of Messages in Mailbox m - (RO) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_MSGSTATUS__NBOFMSGMBM            BITFIELD(6, 0)
#define MLB__MAILBOX_MSGSTATUS__NBOFMSGMBM__POS       0

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB5   
 *
 * @BRIEF        NotFull Status bit for User u, Mailbox 5 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB5 BITFIELD(11, 11)
#define MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB5__POS 11

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB5   
 *
 * @BRIEF        NewMessage Status bit for User u, Mailbox 5 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB5 BITFIELD(10, 10)
#define MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB5__POS 10

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB4   
 *
 * @BRIEF        NotFull Status bit for User u, Mailbox 4 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB4 BITFIELD(9, 9)
#define MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB4__POS 9

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB4   
 *
 * @BRIEF        NewMessage Status bit for User u, Mailbox 4 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB4 BITFIELD(8, 8)
#define MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB4__POS 8

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB3   
 *
 * @BRIEF        NotFull Status bit for User u, Mailbox 3 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB3 BITFIELD(7, 7)
#define MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB3__POS 7

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB3   
 *
 * @BRIEF        NewMessage Status bit for User u, Mailbox 3 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB3 BITFIELD(6, 6)
#define MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB3__POS 6

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB2   
 *
 * @BRIEF        NotFull Status bit for User u, Mailbox 2 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB2 BITFIELD(5, 5)
#define MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB2__POS 5

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB2   
 *
 * @BRIEF        NewMessage Status bit for User u, Mailbox 2 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB2 BITFIELD(4, 4)
#define MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB2__POS 4

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB1   
 *
 * @BRIEF        NotFull Status bit for User u, Mailbox 1 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB1 BITFIELD(3, 3)
#define MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB1__POS 3

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB1   
 *
 * @BRIEF        NewMessage Status bit for User u, Mailbox 1 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB1 BITFIELD(2, 2)
#define MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB1__POS 2

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB0   
 *
 * @BRIEF        NotFull Status bit for User u, Mailbox 0 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB0 BITFIELD(1, 1)
#define MLB__MAILBOX_IRQSTATUS_RAW__NOTFULLSTATUSUUMB0__POS 1

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB0   
 *
 * @BRIEF        NewMessage Status bit for User u, Mailbox 0 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB0 BITFIELD(0, 0)
#define MLB__MAILBOX_IRQSTATUS_RAW__NEWMSGSTATUSUUMB0__POS 0

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB5   
 *
 * @BRIEF        NotFull Status bit for User u, Mailbox 5 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB5 BITFIELD(11, 11)
#define MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB5__POS 11

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB5   
 *
 * @BRIEF        NewMessage Status bit for User u, Mailbox 5 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB5 BITFIELD(10, 10)
#define MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB5__POS 10

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB4   
 *
 * @BRIEF        NotFull Status bit for User u, Mailbox 4 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB4 BITFIELD(9, 9)
#define MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB4__POS 9

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB4   
 *
 * @BRIEF        NewMessage Status bit for User u, Mailbox 4 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB4 BITFIELD(8, 8)
#define MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB4__POS 8

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB3   
 *
 * @BRIEF        NotFull Status bit for User u, Mailbox 3 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB3 BITFIELD(7, 7)
#define MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB3__POS 7

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB3   
 *
 * @BRIEF        NewMessage Status bit for User u, Mailbox 3 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB3 BITFIELD(6, 6)
#define MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB3__POS 6

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB2   
 *
 * @BRIEF        NotFull Status bit for User u, Mailbox 2 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB2 BITFIELD(5, 5)
#define MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB2__POS 5

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB2   
 *
 * @BRIEF        NewMessage Status bit for User u, Mailbox 2 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB2 BITFIELD(4, 4)
#define MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB2__POS 4

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB1   
 *
 * @BRIEF        NotFull Status bit for User u, Mailbox 1 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB1 BITFIELD(3, 3)
#define MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB1__POS 3

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB1   
 *
 * @BRIEF        NewMessage Status bit for User u, Mailbox 1 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB1 BITFIELD(2, 2)
#define MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB1__POS 2

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB0   
 *
 * @BRIEF        NotFull Status bit for User u, Mailbox 0 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB0 BITFIELD(1, 1)
#define MLB__MAILBOX_IRQSTATUS_CLR__NOTFULLSTATUSENUUMB0__POS 1

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB0   
 *
 * @BRIEF        NewMessage Status bit for User u, Mailbox 0 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB0 BITFIELD(0, 0)
#define MLB__MAILBOX_IRQSTATUS_CLR__NEWMSGSTATUSENUUMB0__POS 0

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB5   
 *
 * @BRIEF        NotFull Enable bit for User u, Mailbox 5 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB5 BITFIELD(11, 11)
#define MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB5__POS 11

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB5   
 *
 * @BRIEF        NewMessage Enable bit for User u, Mailbox 5 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB5 BITFIELD(10, 10)
#define MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB5__POS 10

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB4   
 *
 * @BRIEF        NotFull Enable bit for User u, Mailbox 4 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB4 BITFIELD(9, 9)
#define MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB4__POS 9

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB4   
 *
 * @BRIEF        NewMessage Enable bit for User u, Mailbox 4 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB4 BITFIELD(8, 8)
#define MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB4__POS 8

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB3   
 *
 * @BRIEF        NotFull Enable bit for User u, Mailbox 3 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB3 BITFIELD(7, 7)
#define MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB3__POS 7

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB3   
 *
 * @BRIEF        NewMessage Enable bit for User u, Mailbox 3 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB3 BITFIELD(6, 6)
#define MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB3__POS 6

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB2   
 *
 * @BRIEF        NotFull Enable bit for User u, Mailbox 2 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB2 BITFIELD(5, 5)
#define MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB2__POS 5

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB2   
 *
 * @BRIEF        NewMessage Enable bit for User u, Mailbox 2 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB2 BITFIELD(4, 4)
#define MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB2__POS 4

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB1   
 *
 * @BRIEF        NotFull Enable bit for User u, Mailbox 1 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB1 BITFIELD(3, 3)
#define MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB1__POS 3

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB1   
 *
 * @BRIEF        NewMessage Enable bit for User u, Mailbox 1 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB1 BITFIELD(2, 2)
#define MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB1__POS 2

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB0   
 *
 * @BRIEF        NotFull Enable bit for User u, Mailbox 0 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB0 BITFIELD(1, 1)
#define MLB__MAILBOX_IRQENABLE_SET__NOTFULLENABLEUUMB0__POS 1

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB0   
 *
 * @BRIEF        NewMessage Enable bit for User u, Mailbox 0 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB0 BITFIELD(0, 0)
#define MLB__MAILBOX_IRQENABLE_SET__NEWMSGENABLEUUMB0__POS 0

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB5   
 *
 * @BRIEF        NotFull Enable bit for User u, Mailbox 5 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB5 BITFIELD(11, 11)
#define MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB5__POS 11

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB5   
 *
 * @BRIEF        NewMessage Enable bit for User u, Mailbox 5 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB5 BITFIELD(10, 10)
#define MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB5__POS 10

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB4   
 *
 * @BRIEF        NotFull Enable bit for User u, Mailbox 4 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB4 BITFIELD(9, 9)
#define MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB4__POS 9

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB4   
 *
 * @BRIEF        NewMessage Enable bit for User u, Mailbox 4 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB4 BITFIELD(8, 8)
#define MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB4__POS 8

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB3   
 *
 * @BRIEF        NotFull Enable bit for User u, Mailbox 3 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB3 BITFIELD(7, 7)
#define MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB3__POS 7

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB3   
 *
 * @BRIEF        NewMessage Enable bit for User u, Mailbox 3 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB3 BITFIELD(6, 6)
#define MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB3__POS 6

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB2   
 *
 * @BRIEF        NotFull Enable bit for User u, Mailbox 2 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB2 BITFIELD(5, 5)
#define MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB2__POS 5

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB2   
 *
 * @BRIEF        NewMessage Enable bit for User u, Mailbox 2 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB2 BITFIELD(4, 4)
#define MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB2__POS 4

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB1   
 *
 * @BRIEF        NotFull Enable bit for User u, Mailbox 1 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB1 BITFIELD(3, 3)
#define MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB1__POS 3

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB1   
 *
 * @BRIEF        NewMessage Enable bit for User u, Mailbox 1 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB1 BITFIELD(2, 2)
#define MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB1__POS 2

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB0   
 *
 * @BRIEF        NotFull Enable bit for User u, Mailbox 0 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB0 BITFIELD(1, 1)
#define MLB__MAILBOX_IRQENABLE_CLR__NOTFULLENABLEUUMB0__POS 1

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB0   
 *
 * @BRIEF        NewMessage Enable bit for User u, Mailbox 0 - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB0 BITFIELD(0, 0)
#define MLB__MAILBOX_IRQENABLE_CLR__NEWMSGENABLEUUMB0__POS 0

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQ_EOI__EOIVAL   
 *
 * @BRIEF        EOI VALUE - (WO) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQ_EOI__EOIVAL                  BITFIELD(1, 0)
#define MLB__MAILBOX_IRQ_EOI__EOIVAL__POS             0


/*
 * List of register bitfields values for component MLB
 *
 */

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_SYSCONFIG__SIDLEMODE__B00
 *
 * @BRIEF        Force-idle. An idle request is acknowledged unconditionally 
 *               - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_SYSCONFIG__SIDLEMODE__B00        0x0u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_SYSCONFIG__SIDLEMODE__B01
 *
 * @BRIEF        No-idle. An idle request is never acknowledged - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_SYSCONFIG__SIDLEMODE__B01        0x1u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_SYSCONFIG__SIDLEMODE__B10
 *
 * @BRIEF        Smart-idle. Acknowledgement to an idle request is given 
 *               based on the internal activity of the module based on the 
 *               internal activity of the module - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_SYSCONFIG__SIDLEMODE__B10        0x2u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_SYSCONFIG__SIDLEMODE__B11
 *
 * @BRIEF        reserved   do not use - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_SYSCONFIG__SIDLEMODE__B11        0x3u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_SYSCONFIG__SOFTRESET__B0
 *
 * @BRIEF        Soft/Hard reset done - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_SYSCONFIG__SOFTRESET__B0         0x0u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_SYSCONFIG__SOFTRESET__B1
 *
 * @BRIEF        Write 1 to start the soft reset sequence - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_SYSCONFIG__SOFTRESET__B1         0x1u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQ_EOI__EOIVAL__B0
 *
 * @BRIEF        EOI val first bit - (Write) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQ_EOI__EOIVAL__B0              0x0u

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MLB__MAILBOX_IRQ_EOI__EOIVAL__B1
 *
 * @BRIEF        EOI val second bit - (Write) 
 *
 *//*------------------------------------------------------------------------ */
#define MLB__MAILBOX_IRQ_EOI__EOIVAL__B1              0x1u


#ifdef __cplusplus
}
#endif
#endif  /* __MLB_H */
