ALG_tidl=yes
Alg_ObjectDraw=yes
ALG_objectdetection=yes
ALG_FXN_radarfft2=yes
ALG_FXN_radarpeakdetect=yes
ALG_FXN_radardraw=yes
ALG_FXN_radarbeamform=yes
ALG_radarprocess=yes

NEED_PROC_IPU1_0=yes
NEED_PROC_EVE1=yes
NEED_PROC_EVE2=yes
NEED_PROC_DSP1=yes
NEED_PROC_DSP2=yes
NEED_PROC_A15_0=yes
