ALG_sparseopticalflow=yes
ALG_structurefrommotion=yes

NEED_PROC_IPU1_0=yes
NEED_PROC_A15_0=yes
NEED_PROC_DSP1=yes
NEED_PROC_DSP2=yes
NEED_PROC_EVE1=yes
NEED_PROC_EVE2=yes
NEED_PROC_EVE3=yes
NEED_PROC_EVE4=yes