# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_median_filter_mxn_u8
TEST_BENCH = $(FILE)_tb
CFILES = ../src_kernelC/$(FILE)_host.c
CFILES += ../src_kernelC/vcop_median_filter_mxn_u8.c vcop_median_filter_mxn_u8_config.c 

include ../../../common/Makefile.wincommon
