/*
 *  Copyright (C) 2014 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 *  \file stw_dcanUtTestcases.h
 *
 *  \brief This file defines the test cases for DCAN UT.
 */

#ifndef STW_DCAN_UT_TEST_CASES_H_
#define STW_DCAN_UT_TEST_CASES_H_

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
#include <st_dcanUt.h>

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */
#define DCAN_NUM_TX_TESTCASES         (sizeof (gDCANTxTestcaseParams) / sizeof (st_DCANTestcaseParams_t))
#define DCAN_NUM_RX_TESTCASES         (sizeof (gDCANRxTestcaseParams) / sizeof (st_DCANTestcaseParams_t))
#define DCAN_NUM_TEST_MODE_TESTCASES  (sizeof (gDCANTestModeTestcaseParams) / sizeof (st_DCANTestcaseParams_t))
#define DCAN_NUM_ERR_TESTCASES        (sizeof (gDCANErrTestcaseParams) / sizeof (st_DCANTestcaseParams_t))

/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/** \brief Defines the various DCAN test cases. */
static st_DCANTestcaseParams_t gDCANTxTestcaseParams[] =
{
    /* enableTest, testCaseId,
     * testcaseType,
     * reqId,
     * testCaseName,
     * userInfo, *disableReason
     * clkFreq, bitrate,
     * dcanAppInstance,
     * dcanAppTxMsgObj,
     * dcanAppRxMsgObj,
     * dcanAppIfReg,
     * dcanCfgPrms,
     * dcanTxCfgPrms,
     * dcanRxCfgPrms,
     * dcanTxPrms,
     * printEnable,
     * testType,
     * numMsg,
     */
    {
        TEST_ENABLE, 1U,
        ST_TCT_DCAN_TX,
        ":PDK-163:PDK-272:PDK-288:PDK-273:PDK-274:PDK-275:PDK-276:PDK-277:PDK-280:PDK-281:PDK-282:PDK-283:PDK-284:PDK-278:PDK-306:PDK-312:",
        "DCAN1_TX_INT0_1MBPS_EXT_MSGIDT_0xC1_DLC_8_MSGOBJ_1_IFREG_1",
        NULL, NULL,
        20000000U, 1000000U, 70U, 700U,
        DCAN1_APP_INST,
        1U,
        65U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            DEF_DATA_SIZE,
            0U,
            0U,
            0U,
            0U,
            {0x12,
             0x34,
             0x56,
             0x78,
             0x90,
             0x09,
             0x87,
             0x65},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_SANITY | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 2U,
        ST_TCT_DCAN_TX,
        ":PDK-163:PDK-272:PDK-288:PDK-273:PDK-274:PDK-275:PDK-276:PDK-277:PDK-280:PDK-281:PDK-282:PDK-283:PDK-284:PDK-278:PDK-305:PDK-311:",
        "DCAN1_TX_INT0_1MBPS_STD_MSGIDT_0x1ECC0000_DLC_1_MSGOBJ_32_IFREG_2",
        NULL, NULL,
        20000000U, 1000000U, 75U, 700U,
        DCAN1_APP_INST,
        32U,
        65U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x1ECC0000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            1U,
            0U,
            0U,
            0U,
            0U,
            {0xA5},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 3U,
        ST_TCT_DCAN_TX,
        ":PDK-278:PDK-306:PDK-312:",
        "DCAN1_TX_INT0_800KBPS_EXT_MSGIDT_0xBCD1234_DLC_7_MSGOBJ_6_IFREG_2",
        NULL, NULL,
        20000000U, 800000U, 80U, 700U,
        DCAN1_APP_INST,
        6U,
        65U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xBCD1234,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            7U,
            0U,
            0U,
            0U,
            0U,
            {0xA5,
             0x5A,
             0xB4,
             0x4B,
             0xC3,
             0x3C,
             0xFF},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 4U,
        ST_TCT_DCAN_TX,
        ":PDK-278:PDK-305:PDK-311:",
        "DCAN1_TX_INT0_800KBPS_STD_MSGIDT_0xAB80000_DLC_6_MSGOBJ_14_IFREG_1",
        NULL, NULL,
        20000000U, 800000U, 85U, 700U,
        DCAN1_APP_INST,
        14U,
        65U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0xAB80000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            6U,
            0U,
            0U,
            0U,
            0U,
            {0xA1,
             0xB2,
             0xC3,
             0xD4,
             0xE5,
             0xF6},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 5U,
        ST_TCT_DCAN_TX,
        ":PDK-278:PDK-305:PDK-311:",
        "DCAN1_TX_INT0_500KBPS_STD_MSGIDT_0x1FFC0000_DLC_5_MSGBOX_10_IFREG_2",
        NULL, NULL,
        20000000U, 500000U, 90U, 700U,
        DCAN1_APP_INST,
        10U,
        65U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x1FFC0000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            5U,
            0U,
            0U,
            0U,
            0U,
            {0xA5,
             0x5A,
             0x3c,
             0xc3,
             0xFF},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 6U,
        ST_TCT_DCAN_TX,
        ":PDK-278:PDK-306:PDK-312:",
        "DCAN1_TX_INT0_500KBPS_EXT_MSGIDT_0xCDD9012_DLC_4_MSGBOX_19_IFREG_1",
        NULL, NULL,
        20000000U, 500000U, 70U, 600U,
        DCAN1_APP_INST,
        19U,
        65U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xCDD9012,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            4U,
            0U,
            0U,
            0U,
            0U,
            {0x1A,
             0x2B,
             0x3C,
             0x4D},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 7U,
        ST_TCT_DCAN_TX,
        ":PDK-278:PDK-306:PDK-312:",
        "DCAN1_TX_INT0_250KBPS_EXT_MSGIDT_0xEFF9876_DLC_3_MSGBOX_27_IFREG_2",
        NULL, NULL,
        20000000U, 250000U, 75U, 600U,
        DCAN1_APP_INST,
        27U,
        65U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xEFF9876,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            3U,
            0U,
            0U,
            0U,
            0U,
            {0xAA,
             0xBB,
             0xCC},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 8U,
        ST_TCT_DCAN_TX,
        ":PDK-278:PDK-305:PDK-311:",
        "DCAN1_TX_INT0_250KBPS_STD_MSGIDT_0xABC0000_DLC_2_MSGBOX_40_IFREG_1",
        NULL, NULL,
        20000000U, 250000U, 80U, 600U,
        DCAN1_APP_INST,
        40U,
        65U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0xABC0000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            2U,
            0U,
            0U,
            0U,
            0U,
            {0x4B,
             0xB4},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 9U,
        ST_TCT_DCAN_TX,
        ":PDK-289:PDK-290:PDK-291:PDK-293:PDK-296:PDK-298:PDK-299:PDK-300:PDK-303:PDK-308:PDK-278:PDK-306:PDK-312:",
        "DCAN1_TX_INT0_125KBPS_EXT_MSGIDT_0x1FBE5432_DLC_1_MSGBOX_58_IFREG_2",
        NULL, NULL,
        20000000U, 125000U, 85U, 600U,
        DCAN1_APP_INST,
        58U,
        65U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0x1FBE5432,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            1U,
            0U,
            0U,
            0U,
            0U,
            {0x55},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 10U,
        ST_TCT_DCAN_TX,
        ":PDK-289:PDK-290:PDK-291:PDK-293:PDK-296:PDK-298:PDK-299:PDK-300:PDK-303:PDK-308:PDK-278:PDK-305:PDK-311:",
        "DCAN1_TX_INT0_125KBPS_STD_MSGIDT_0x1CBE1098_DLC_8_MSGBOX_63_IFREG_1",
        NULL, NULL,
        20000000U, 125000U, 90U, 600U,
        DCAN1_APP_INST,
        63U,
        65U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0x1CBE1098,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            DEF_DATA_SIZE,
            0U,
            0U,
            0U,
            0U,
            {0xAB,
             0xCD,
             0xEF,
             0xFA,
             0xFE,
             0xDC,
             0xBA,
             0xFF},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 11U,
        ST_TCT_DCAN_TX,
        ":PDK-278:PDK-306:PDK-312:",
        "DCAN1_TX_INT0_1MBPS_EXT_MSGIDT_0xC1_DLC_8_MSGOBJ_1_IFREG_1_NUMMSG_2",
        NULL, NULL,
        20000000U, 1000000U, 70U, 800U,
        DCAN1_APP_INST,
        1U,
        65U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            DEF_DATA_SIZE,
            0U,
            0U,
            0U,
            0U,
            {0x12,
             0x34,
             0x56,
             0x78,
             0x90,
             0x09,
             0x87,
             0x65},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_SANITY | ST_TT_FULL,
        2U,
    },
    {
        TEST_ENABLE, 12U,
        ST_TCT_DCAN_TX,
        ":PDK-278:PDK-305:PDK-311:",
        "DCAN1_TX_INT0_1MBPS_STD_MSGIDT_0x1FEC0000_DLC_1_MSGOBJ_32_IFREG_2_NUMMSG_3",
        NULL, NULL,
        20000000U, 1000000U, 75U, 800U,
        DCAN1_APP_INST,
        32U,
        65U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x1FEC0000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            1U,
            0U,
            0U,
            0U,
            0U,
            {0xA5},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        3U,
    },
    {
        TEST_ENABLE, 13U,
        ST_TCT_DCAN_TX,
        ":PDK-278:PDK-306:PDK-312:",
        "DCAN1_TX_INT0_800KBPS_EXT_MSGIDT_0x1234FEDC_DLC_7_MSGOBJ_6_IFREG_2_NUMMSG_6",
        NULL, NULL,
        20000000U, 800000U, 80U, 800U,
        DCAN1_APP_INST,
        6U,
        65U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0x1234FEDC,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            7U,
            0U,
            0U,
            0U,
            0U,
            {0xA5,
             0x5A,
             0xB4,
             0x4B,
             0xC3,
             0x3C,
             0xFF},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        6U,
    },
    {
        TEST_ENABLE, 14U,
        ST_TCT_DCAN_TX,
        ":PDK-278:PDK-305:PDK-311:",
        "DCAN1_TX_INT0_800KBPS_STD_MSGIDT_0x1CB80000_DLC_6_MSGOBJ_14_IFREG_1_NUMMSG_7",
        NULL, NULL,
        20000000U, 800000U, 85U, 800U,
        DCAN1_APP_INST,
        14U,
        65U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x1CB80000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            6U,
            0U,
            0U,
            0U,
            0U,
            {0xA1,
             0xB2,
             0xC3,
             0xD4,
             0xE5,
             0xF6},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        7U,
    },
    {
        TEST_ENABLE, 15U,
        ST_TCT_DCAN_TX,
        ":PDK-278:PDK-305:PDK-311:",
        "DCAN1_TX_INT0_500KBPS_STD_MSGIDT_0x123C0000_DLC_5_MSGBOX_10_IFREG_2_NUMMSG_10",
        NULL, NULL,
        20000000U, 500000U, 90U, 800U,
        DCAN1_APP_INST,
        10U,
        65U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x123C0000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            5U,
            0U,
            0U,
            0U,
            0U,
            {0xA5,
             0x5A,
             0x3c,
             0xc3,
             0xFF},
        },
        {
            0U,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        10U,
    },
};
static st_DCANTestcaseParams_t gDCANRxTestcaseParams[] =
{
    /* enableTest, testCaseId,
     * testcaseType,
     * reqId,
     * testCaseName,
     * userInfo, disableReason
     * clkFreq, bitrate,
     * dcanAppInstance,
     * dcanAppTxMsgObj,
     * dcanAppRxMsgObj,
     * dcanAppIfReg,
     * dcanCfgPrms,
     * dcanTxCfgPrms,
     * dcanRxCfgPrms,
     * dcanTxPrms,
     * printEnable,
     * testType,
     */
    {
        TEST_ENABLE, 100U,
        ST_TCT_DCAN_RX,
        ":PDK-163:PDK-272:PDK-288:PDK-273:PDK-274:PDK-275:PDK-276:PDK-277:PDK-280:PDK-281:PDK-282:PDK-283:PDK-284:PDK-279:PDK-306:PDK-312:",
        "DCAN1_RX_INT0_1MBPS_EXT_MSGIDT_0xC1_DLC_8_MSGOBJ_5_IFREG_2",
        NULL, NULL,
        20000000U, 1000000U, 70U, 700U,
        DCAN1_APP_INST,
        65U,
        5U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            DEF_DATA_SIZE,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0xC1,
            DEF_FRAME_TYPE,
            {0xA5,
             0xA5,
             0x5A,
             0x5A,
             0x3c,
             0x3c,
             0xc3,
             0xc3},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_SANITY | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 101U,
        ST_TCT_DCAN_RX,
        ":PDK-163:PDK-272:PDK-288:PDK-273:PDK-274:PDK-275:PDK-276:PDK-277:PDK-280:PDK-281:PDK-282:PDK-283:PDK-284:PDK-279:PDK-305:PDK-311:",
        "DCAN1_RX_INT0_1MBPS_STD_MSGIDT_0x2300000_DLC_7_MSGOBJ_10_IFREG_1",
        NULL, NULL,
        20000000U, 1000000U, 75U, 700U,
        DCAN1_APP_INST,
        65U,
        10U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x2300000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            7U,
            DEF_MSG_LOST_STAT,
            STD_FRAME,
            0x2300000,
            DEF_FRAME_TYPE,
            {0x12,
             0x34,
             0x56,
             0x78,
             0x90,
             0x09,
             0x87},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 102U,
        ST_TCT_DCAN_RX,
        ":PDK-279:PDK-305:PDK-311:",
        "DCAN1_RX_INT0_800KBPS_STD_MSGIDT_0x1EA80000_DLC_4_MSGBOX_25_IFREG_1",
        NULL, NULL,
        20000000U, 800000U, 80U, 700U,
        DCAN1_APP_INST,
        65U,
        25U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x1EA80000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            4U,
            DEF_MSG_LOST_STAT,
            STD_FRAME,
            0x1EA80000,
            DEF_FRAME_TYPE,
            {0x12,
             0x90,
             0x34,
             0x78},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 103U,
        ST_TCT_DCAN_RX,
        ":PDK-279:PDK-306:PDK-312:",
        "DCAN1_RX_INT0_800KBPS_EXT_MSGIDT_0x765ABCD_DLC_6_MSGOBJ_15_IFREG_2",
        NULL, NULL,
        20000000U, 800000U, 85U, 700U,
        DCAN1_APP_INST,
        65U,
        15U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0x765ABCD,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            6U,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0x765ABCD,
            DEF_FRAME_TYPE,
            {0xAB,
             0xCD,
             0xEF,
             0xFE,
             0xDC,
             0xBA},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 104U,
        ST_TCT_DCAN_RX,
        ":PDK-279:PDK-306:PDK-312:",
        "DCAN1_RX_INT0_500KBPS_EXT_MSGIDT_0x1109AABB_DLC_5_MSGOBJ_20_IFREG_1",
        NULL, NULL,
        20000000U, 500000U, 90U, 700U,
        DCAN1_APP_INST,
        65U,
        20U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0x1109AABB,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            5U,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0x1109AABB,
            DEF_FRAME_TYPE,
            {0xA1,
             0xB2,
             0xC3,
             0xD4,
             0xE5},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 105U,
        ST_TCT_DCAN_RX,
        ":PDK-279:PDK-305:PDK-311:",
        "DCAN1_RX_INT0_500KBPS_STD_MSGIDT_0x13540000_DLC_3_MSGOBJ_30_IFREG_2",
        NULL, NULL,
        20000000U, 500000U, 70U, 600U,
        DCAN1_APP_INST,
        65U,
        30U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x13540000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            3U,
            DEF_MSG_LOST_STAT,
            STD_FRAME,
            0x13540000,
            DEF_FRAME_TYPE,
            {0x1A,
             0x2B,
             0x3C},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 106U,
        ST_TCT_DCAN_RX,
        ":PDK-279:PDK-306:PDK-312:",
        "DCAN1_RX_INT0_250KBPS_EXT_MSGIDT_0x1753EEFF_DLC_2_MSGOBJ_35_IFREG_1",
        NULL, NULL,
        20000000U, 250000U, 75U, 600U,
        DCAN1_APP_INST,
        65U,
        35U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0x1753EEFF,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            2U,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0x1753EEFF,
            DEF_FRAME_TYPE,
            {0xFF,
             0x99},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 107U,
        ST_TCT_DCAN_RX,
        ":PDK-279:PDK-305:PDK-311:",
        "DCAN1_RX_INT0_250KBPS_STD_MSGIDT_0x4680000_DLC_1_MSGOBJ_50_IFREG_2",
        NULL, NULL,
        20000000U, 250000U, 80U, 600U,
        DCAN1_APP_INST,
        65U,
        50U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x4680000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            1U,
            DEF_MSG_LOST_STAT,
            STD_FRAME,
            0x4680000,
            DEF_FRAME_TYPE,
            {0xFF},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 108U,
        ST_TCT_DCAN_RX,
        ":PDK-289:PDK-290:PDK-291:PDK-293:PDK-296:PDK-298:PDK-299:PDK-300:PDK-303:PDK-308:PDK-279:PDK-305:PDK-311:",
        "DCAN1_RX_INT0_125KBPS_STD_MSGIDT_0x1EDC0000_DLC_1_MSGBOX_55_IFREG_2",
        NULL, NULL,
        20000000U, 125000U, 85U, 600U,
        DCAN1_APP_INST,
        65U,
        55U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x1EDC0000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            1U,
            DEF_MSG_LOST_STAT,
            STD_FRAME,
            0x1EDC0000,
            DEF_FRAME_TYPE,
            {0xF8},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 109U,
        ST_TCT_DCAN_RX,
        ":PDK-289:PDK-290:PDK-291:PDK-293:PDK-296:PDK-298:PDK-299:PDK-300:PDK-303:PDK-308:PDK-279:PDK-306:PDK-312:",
        "DCAN1_RX_INT0_125KBPS_EXT_MSGIDT_0x0864FDEC_DLC_8_MSGBOX_60_IFREG_1",
        NULL, NULL,
        20000000U, 125000U, 90U, 600U,
        DCAN1_APP_INST,
        65U,
        60U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0x0864FDEC,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            8U,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0x0864FDEC,
            DEF_FRAME_TYPE,
            {0xAF,
             0xBE,
             0xCD,
             0xDC,
             0xEB,
             0xFA,
             0xFF,
             0xAA},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 110U,
        ST_TCT_DCAN_RX,
        ":PDK-279:PDK-306:PDK-312:",
        "DCAN1_RX_INT0_1MBPS_EXT_MSGIDT_0xC1_DLC_8_MSGOBJ_5_IFREG_2_NUMMSG_2",
        NULL, NULL,
        20000000U, 1000000U, 70U, 800U,
        DCAN1_APP_INST,
        65U,
        5U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            DEF_DATA_SIZE,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0xC1,
            DEF_FRAME_TYPE,
            {0xA5,
             0xA5,
             0x5A,
             0x5A,
             0x3c,
             0x3c,
             0xc3,
             0xc3},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_SANITY | ST_TT_FULL,
        2U,
    },
    {
        TEST_ENABLE, 111U,
        ST_TCT_DCAN_RX,
        ":PDK-279:PDK-305:PDK-311:",
        "DCAN1_RX_INT0_1MBPS_STD_MSGIDT_0xF300000_DLC_7_MSGOBJ_10_IFREG_1_NUMMSG_3",
        NULL, NULL,
        20000000U, 1000000U, 75U, 800U,
        DCAN1_APP_INST,
        65U,
        10U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0xF300000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            7U,
            DEF_MSG_LOST_STAT,
            STD_FRAME,
            0xF300000,
            DEF_FRAME_TYPE,
            {0x12,
             0x34,
             0x56,
             0x78,
             0x90,
             0x09,
             0x87},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        3U,
    },
    {
        TEST_ENABLE, 112U,
        ST_TCT_DCAN_RX,
        ":PDK-279:PDK-305:PDK-311:",
        "DCAN1_RX_INT0_800KBPS_STD_MSGIDT_0x1FA00000_DLC_4_MSGBOX_25_IFREG_1_NUMMSG_6",
        NULL, NULL,
        20000000U, 800000U, 80U, 800U,
        DCAN1_APP_INST,
        65U,
        25U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x1FA00000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            4U,
            DEF_MSG_LOST_STAT,
            STD_FRAME,
            0x1FA00000,
            DEF_FRAME_TYPE,
            {0x12,
             0x90,
             0x34,
             0x78},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        6U,
    },
    {
        TEST_ENABLE, 113U,
        ST_TCT_DCAN_RX,
        ":PDK-279:PDK-306:PDK-312:",
        "DCAN1_RX_INT0_800KBPS_EXT_MSGIDT_0x8765ABCD_DLC_6_MSGOBJ_15_IFREG_2_NUMMSG_7",
        NULL, NULL,
        20000000U, 800000U, 85U, 800U,
        DCAN1_APP_INST,
        65U,
        15U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_ENABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0x765ABCD,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            6U,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0x765ABCD,
            DEF_FRAME_TYPE,
            {0xAB,
             0xCD,
             0xEF,
             0xFE,
             0xDC,
             0xBA},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        7U,
    },
    {
        TEST_ENABLE, 114U,
        ST_TCT_DCAN_RX,
        ":PDK-279:PDK-306:PDK-312:",
        "DCAN1_RX_INT0_500KBPS_EXT_MSGIDT_0x2109AABB_DLC_5_MSGOBJ_20_IFREG_1_NUMMSG_10",
        NULL, NULL,
        20000000U, 500000U, 90U, 800U,
        DCAN1_APP_INST,
        65U,
        20U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_ENABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            0U,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0x1109AABB,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            5U,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0x1109AABB,
            DEF_FRAME_TYPE,
            {0xA1,
             0xB2,
             0xC3,
             0xD4,
             0xE5},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        10U,
    },
};

static st_DCANTestcaseParams_t gDCANTestModeTestcaseParams[] =
{
    /* enableTest, testCaseId,
     * testcaseType,
     * reqId,
     * testCaseName,
     * userInfo, disableReason
     * clkFreq, bitrate,
     * dcanAppInstance,
     * dcanAppTxMsgObj,
     * dcanAppRxMsgObj,
     * dcanAppIfReg,
     * dcanCfgPrms,
     * dcanTxCfgPrms,
     * dcanRxCfgPrms,
     * dcanTxPrms,
     * printEnable,
     * testType,
     */
    {
        TEST_ENABLE, 200U,
        ST_TCT_DCAN_TEST_MODE,
        ":PDK-163:PDK-272:PDK-288:PDK-273:PDK-274:PDK-275:PDK-276:PDK-277:PDK-280:PDK-281:PDK-282:PDK-283:PDK-284:PDK-278:PDK-279:PDK-306:PDK-312:PDK-292:OMAPS00319168:",
        "DCAN1_LBACK_TESTMODE_INT0_1MBPS_EXT_MSGIDT_0xC1_DLC_8",
        NULL, NULL,
        20000000U, 1000000U, 70U, 700U,
        DCAN1_APP_INST,
        1U,
        10U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_DISABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_DISABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_ENABLE,
            DCAN_TEST_MODE_LPBACK,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            DEF_DATA_SIZE,
            0U,
            0U,
            0U,
            0U,
            {0x12,
             0x34,
             0x56,
             0x78,
             0x90,
             0x09,
             0x87,
             0x65},
        },
        {
            DEF_DATA_SIZE,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0xC1,
            DEF_FRAME_TYPE,
            {0x12,
             0x34,
             0x56,
             0x78,
             0x90,
             0x09,
             0x87,
             0x65},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 201U,
        ST_TCT_DCAN_TEST_MODE,
        ":PDK-278:PDK-279:PDK-306:PDK-312:PDK-292:",
        "DCAN1_EXL_TESTMODE_INT0_1MBPS_EXT_MSGIDT_0xC1_DLC_8",
        NULL, NULL,
        20000000U, 1000000U, 80U, 700U,
        DCAN1_APP_INST,
        11U,
        20U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_ENABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_DISABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_ENABLE,
            DCAN_TEST_MODE_EXT_LPBACK,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            DEF_DATA_SIZE,
            0U,
            0U,
            0U,
            0U,
            {0xA5,
             0xA5,
             0x5A,
             0x5A,
             0xC3,
             0xC3,
             0x3C,
             0x3C},
        },
        {
            DEF_DATA_SIZE,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0xC1,
            DEF_FRAME_TYPE,
            {0xA5,
             0xA5,
             0x5A,
             0x5A,
             0xC3,
             0xC3,
             0x3C,
             0x3C},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA3XX |
        PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 202U,
        ST_TCT_DCAN_TEST_MODE,
        ":PDK-278:PDK-279:PDK-306:PDK-312:PDK-292:PDK-302:OMAPS00319168:",
        "DCAN2_LBACK_TESTMODE_POLLED_1MBPS_EXT_MSGIDT_0xC1_DLC_8",
        NULL, NULL,
        20000000U, 1000000U, 90U, 700U,
        DCAN2_APP_INST,
        21U,
        30U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_DISABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_DISABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_ENABLE,
            DCAN_TEST_MODE_LPBACK,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            DEF_DATA_SIZE,
            0U,
            0U,
            0U,
            0U,
            {0x12,
             0x34,
             0x56,
             0x78,
             0x90,
             0x09,
             0x87,
             0x65},
        },
        {
            DEF_DATA_SIZE,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0xC1,
            DEF_FRAME_TYPE,
            {0x12,
             0x34,
             0x56,
             0x78,
             0x90,
             0x09,
             0x87,
             0x65},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
    {
        TEST_ENABLE, 203U,
        ST_TCT_DCAN_TEST_MODE,
        ":PDK-278:PDK-279:PDK-306:PDK-312:PDK-292:PDK-302:",
        "DCAN2_EXL_TESTMODE_POLLED_1MBPS_EXT_MSGIDT_0xC1_DLC_8",
        NULL, NULL,
        20000000U, 1000000U, 70U, 700U,
        DCAN2_APP_INST,
        31U,
        40U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_DISABLE,
            ECC_MODE_DISABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_DISABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_DISABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_ENABLE,
            DCAN_TEST_MODE_EXT_LPBACK,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            DCAN_DIR_RX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            DEF_DATA_SIZE,
            0U,
            0U,
            0U,
            0U,
            {0xA5,
             0xA5,
             0x5A,
             0x5A,
             0xC3,
             0xC3,
             0x3C,
             0x3C},
        },
        {
            DEF_DATA_SIZE,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0xC1,
            DEF_FRAME_TYPE,
            {0xA5,
             0xA5,
             0x5A,
             0x5A,
             0xC3,
             0xC3,
             0x3C,
             0x3C},
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
    },
};

static st_DCANTestcaseParams_t gDCANErrTestcaseParams[] =
{
    /* enableTest, testCaseId,
     * testcaseType,
     * reqId,
     * testCaseName,
     * userInfo, disableReason
     * clkFreq, bitrate,
     * dcanAppInstance,
     * dcanAppTxMsgObj,
     * dcanAppRxMsgObj,
     * dcanAppIfReg,
     * dcanCfgPrms,
     * dcanTxCfgPrms,
     * dcanRxCfgPrms,
     * dcanTxPrms,
     * printEnable,
     * testType,
     */
    {
        TEST_ENABLE, 300U,
        ST_TCT_DCAN_ERR,
        ":PDK-294:PDK-285:PDK-297:",
        "DCAN1_ERR_PARITY_1MBPS_EXT_MSGIDT_0xC1_DLC_8_MSGOBJ_1_IFREG_1",
        NULL, NULL,
        20000000U, 1000000U, 80U, 700U,
        DCAN1_APP_INST,
        1U,
        60U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_ENABLE,
            ECC_MODE_ENABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_DISABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_DISABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            DEF_DATA_SIZE,
            0U,
            0U,
            0U,
            0U,
            {0x12,
             0x34,
             0x56,
             0x78,
             0x90,
             0x09,
             0x87,
             0x65},
        },
        {
            0U,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0xC1,
            DEF_FRAME_TYPE,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA2EX,
        ST_TT_SANITY | ST_TT_FULL,
        1U,
        ST_TET_PARITY,
        0xFFFFFFFE,
    },
    {
        TEST_ENABLE, 301U,
        ST_TCT_DCAN_ERR,
        ":PDK-294:PDK-285:PDK-297:",
        "DCAN1_ERR_PARITY_500KBPS_STD_MSGIDT_0x1ECC0000_DLC_4_MSGOBJ_32_IFREG_2",
        NULL, NULL,
        20000000U, 500000U, 90U, 700U,
        DCAN1_APP_INST,
        32U,
        60U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_ENABLE,
            ECC_MODE_ENABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_DISABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_DISABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x1ECC0000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            4U,
            0U,
            0U,
            0U,
            0U,
            {0x5A,
             0x3F,
             0xc3,
             0xFF},
        },
        {
            0U,
            DEF_MSG_LOST_STAT,
            STD_FRAME,
            0x1ECC0000,
            DEF_FRAME_TYPE,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
        ST_TET_PARITY,
        0xFFFEFFFF,
    },
    {
        TEST_ENABLE, 302U,
        ST_TCT_DCAN_ERR,
        ":PDK-294:PDK-285:PDK-297:",
        "DCAN1_ERR_PARITY_800KBPS_EXT_MSGIDT_0x1BCD1234_DLC_7_MSGOBJ_55_IFREG_1",
        NULL, NULL,
        20000000U, 800000U, 70U, 700U,
        DCAN1_APP_INST,
        55U,
        60U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_ENABLE,
            ECC_MODE_ENABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_DISABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_DISABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0x1BCD1234,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            7U,
            0U,
            0U,
            0U,
            0U,
            {0xA5,
             0x5A,
             0xB7,
             0xFB,
             0x13,
             0x3C,
             0xFF},
        },
        {
            0U,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0x1BCD1234,
            DEF_FRAME_TYPE,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA2XX | PLATFORM_SOC_ID_TDA2PX | PLATFORM_SOC_ID_TDA2EX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
        ST_TET_PARITY,
        0xEFFFFFFF,
    },
    {
        TEST_ENABLE, 303U,
        ST_TCT_DCAN_ERR,
        ":PDK-295:PDK-285:PDK-297:",
        "DCAN1_ERR_SBE_1MBPS_EXT_MSGIDT_0xC1_DLC_8_MSGOBJ_1_IFREG_1",
        NULL, NULL,
        20000000U, 1000000U, 80U, 700U,
        DCAN1_APP_INST,
        1U,
        60U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_ENABLE,
            ECC_MODE_ENABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_DISABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_DISABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            DEF_DATA_SIZE,
            0U,
            0U,
            0U,
            0U,
            {0x12,
             0x34,
             0x56,
             0x78,
             0x90,
             0x09,
             0x87,
             0x65},
        },
        {
            0U,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0xC1,
            DEF_FRAME_TYPE,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA3XX,
        ST_TT_SANITY | ST_TT_FULL,
        1U,
        ST_TET_ECC_SBE,
        0xFFFFFFFE,
    },
    {
        TEST_ENABLE, 304U,
        ST_TCT_DCAN_ERR,
        ":PDK-295:PDK-285:PDK-297:",
        "DCAN1_ERR_SBE_500KBPS_STD_MSGIDT_0x1FED0000_DLC_4_MSGOBJ_32_IFREG_2",
        NULL, NULL,
        20000000U, 500000U, 90U, 700U,
        DCAN1_APP_INST,
        32U,
        60U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_ENABLE,
            ECC_MODE_ENABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_DISABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_DISABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x1FED0000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            4U,
            0U,
            0U,
            0U,
            0U,
            {0x5A,
             0x3F,
             0xc3,
             0xFF},
        },
        {
            0U,
            DEF_MSG_LOST_STAT,
            STD_FRAME,
            0x1FED0000,
            DEF_FRAME_TYPE,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA3XX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
        ST_TET_ECC_SBE,
        0xFFFEFFFF,
    },
    {
        TEST_ENABLE, 305U,
        ST_TCT_DCAN_ERR,
        ":PDK-295:PDK-285:PDK-297:",
        "DCAN1_ERR_SBE_800KBPS_EXT_MSGIDT_0x1FBA9876_DLC_7_MSGOBJ_55_IFREG_1",
        NULL, NULL,
        20000000U, 800000U, 70U, 700U,
        DCAN1_APP_INST,
        55U,
        60U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_ENABLE,
            ECC_MODE_ENABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_DISABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_DISABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0x1FBA9876,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            7U,
            0U,
            0U,
            0U,
            0U,
            {0xA5,
             0x5A,
             0xB7,
             0xFB,
             0x13,
             0x3C,
             0xFF},
        },
        {
            0U,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0x1FBA9876,
            DEF_FRAME_TYPE,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA3XX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
        ST_TET_ECC_SBE,
        0xEFFFFFFF,
    },
    {
        TEST_ENABLE, 306U,
        ST_TCT_DCAN_ERR,
        ":PDK-295:PDK-285:PDK-297:",
        "DCAN1_ERR_DBE_1MBPS_EXT_MSGIDT_0xC1_DLC_8_MSGOBJ_1_IFREG_1",
        NULL, NULL,
        20000000U, 1000000U, 80U, 700U,
        DCAN1_APP_INST,
        1U,
        60U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_ENABLE,
            ECC_MODE_ENABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_DISABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_DISABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0xC1,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            DEF_DATA_SIZE,
            0U,
            0U,
            0U,
            0U,
            {0x12,
             0x34,
             0x56,
             0x78,
             0x90,
             0x09,
             0x87,
             0x65},
        },
        {
            0U,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0xC1,
            DEF_FRAME_TYPE,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA3XX,
        ST_TT_SANITY | ST_TT_FULL,
        1U,
        ST_TET_ECC_DBE,
        0xFFFFFFFA,
    },
    {
        TEST_ENABLE, 307U,
        ST_TCT_DCAN_ERR,
        ":PDK-295:PDK-285:PDK-297:",
        "DCAN1_ERR_DBE_500KBPS_STD_MSGIDT_0x1ECC0000_DLC_4_MSGOBJ_32_IFREG_2",
        NULL, NULL,
        20000000U, 500000U, 90U, 700U,
        DCAN1_APP_INST,
        32U,
        60U,
        DCAN_IF_REG_NUM_2,
        {
            PARITY_ENABLE,
            ECC_MODE_ENABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_DISABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_DISABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            STD_FRAME,
            0x1ECC0000,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            4U,
            0U,
            0U,
            0U,
            0U,
            {0x5A,
             0x3F,
             0xc3,
             0xFF},
        },
        {
            0U,
            DEF_MSG_LOST_STAT,
            STD_FRAME,
            0x1ECC0000,
            DEF_FRAME_TYPE,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA3XX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
        ST_TET_ECC_DBE,
        0xFFFAFFFF,
    },
    {
        TEST_ENABLE, 308U,
        ST_TCT_DCAN_ERR,
        ":PDK-295:PDK-285:PDK-297:",
        "DCAN1_ERR_DBE_800KBPS_EXT_MSGIDT_0x1BCD1234_DLC_7_MSGOBJ_55_IFREG_1",
        NULL, NULL,
        20000000U, 800000U, 70U, 700U,
        DCAN1_APP_INST,
        55U,
        60U,
        DCAN_IF_REG_NUM_1,
        {
            PARITY_ENABLE,
            ECC_MODE_ENABLE,
            ECC_DIAG_MODE_DISABLE,
            SBE_EVENT_DISABLE,
            INTR_LINE_0_DISABLE,
            INTR_LINE_1_DISABLE,
            STAT_CHG_INT_DISABLE,
            ERR_INT_DISABLE,
            IF1_DMA_DISABLE,
            IF2_DMA_DISABLE,
            IF3_DMA_DISABLE,
            AUTO_RETX_DISABLE,
            AUTO_BUS_ON_DISABLE,
            0U,
            TEST_MODE_DISABLE,
            DCAN_TEST_MODE_NONE,
            RAM_ACCESS_DISABLE,
        },
        {
            DCAN_DIR_TX,
            0x1U,
            0x1U,
            0x1FFFFFFF,
            EXT_FRAME,
            0x1BCD1234,
            MSG_VALID,
            UMASK_ENABLE,
            INT_ENABLE,
            RMT_DISABLE,
        },
        {
            0U,
        },
        {
            7U,
            0U,
            0U,
            0U,
            0U,
            {0xA5,
             0x5A,
             0xB7,
             0xFB,
             0x53,
             0x3C,
             0xFF},
        },
        {
            0U,
            DEF_MSG_LOST_STAT,
            EXT_FRAME,
            0x1BCD1234,
            DEF_FRAME_TYPE,
        },
        PRINT_ENABLE,
        PLATFORM_SOC_ID_TDA3XX,
        ST_TT_REGRESSION | ST_TT_FULL,
        1U,
        ST_TET_ECC_DBE,
        0xAFFFFFFF,
    },
};

#endif /* #ifndef STW_DCAN_UT_TEST_CASES_H_ */
