/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-B21
 */

#ifndef ti_sdo_ipc_heaps__
#define ti_sdo_ipc_heaps__


/*
 * ======== module ti.sdo.ipc.heaps.HeapBufMP ========
 */

typedef struct ti_sdo_ipc_heaps_HeapBufMP_Attrs ti_sdo_ipc_heaps_HeapBufMP_Attrs;
typedef struct ti_sdo_ipc_heaps_HeapBufMP_Module_State ti_sdo_ipc_heaps_HeapBufMP_Module_State;
typedef struct ti_sdo_ipc_heaps_HeapBufMP_Fxns__ ti_sdo_ipc_heaps_HeapBufMP_Fxns__;
typedef const struct ti_sdo_ipc_heaps_HeapBufMP_Fxns__* ti_sdo_ipc_heaps_HeapBufMP_Module;
typedef struct ti_sdo_ipc_heaps_HeapBufMP_Params ti_sdo_ipc_heaps_HeapBufMP_Params;
typedef struct ti_sdo_ipc_heaps_HeapBufMP_Object ti_sdo_ipc_heaps_HeapBufMP_Object;
typedef struct ti_sdo_ipc_heaps_HeapBufMP_Struct ti_sdo_ipc_heaps_HeapBufMP_Struct;
typedef ti_sdo_ipc_heaps_HeapBufMP_Object* ti_sdo_ipc_heaps_HeapBufMP_Handle;
typedef struct ti_sdo_ipc_heaps_HeapBufMP_Object__ ti_sdo_ipc_heaps_HeapBufMP_Instance_State;
typedef ti_sdo_ipc_heaps_HeapBufMP_Object* ti_sdo_ipc_heaps_HeapBufMP_Instance;

/*
 * ======== module ti.sdo.ipc.heaps.HeapMultiBufMP ========
 */

typedef struct ti_sdo_ipc_heaps_HeapMultiBufMP_Bucket ti_sdo_ipc_heaps_HeapMultiBufMP_Bucket;
typedef struct ti_sdo_ipc_heaps_HeapMultiBufMP_ExtendedStats ti_sdo_ipc_heaps_HeapMultiBufMP_ExtendedStats;
typedef struct ti_sdo_ipc_heaps_HeapMultiBufMP_Elem ti_sdo_ipc_heaps_HeapMultiBufMP_Elem;
typedef struct ti_sdo_ipc_heaps_HeapMultiBufMP_BucketAttrs ti_sdo_ipc_heaps_HeapMultiBufMP_BucketAttrs;
typedef struct ti_sdo_ipc_heaps_HeapMultiBufMP_Attrs ti_sdo_ipc_heaps_HeapMultiBufMP_Attrs;
typedef struct ti_sdo_ipc_heaps_HeapMultiBufMP_Module_State ti_sdo_ipc_heaps_HeapMultiBufMP_Module_State;
typedef struct ti_sdo_ipc_heaps_HeapMultiBufMP_Fxns__ ti_sdo_ipc_heaps_HeapMultiBufMP_Fxns__;
typedef const struct ti_sdo_ipc_heaps_HeapMultiBufMP_Fxns__* ti_sdo_ipc_heaps_HeapMultiBufMP_Module;
typedef struct ti_sdo_ipc_heaps_HeapMultiBufMP_Params ti_sdo_ipc_heaps_HeapMultiBufMP_Params;
typedef struct ti_sdo_ipc_heaps_HeapMultiBufMP_Object ti_sdo_ipc_heaps_HeapMultiBufMP_Object;
typedef struct ti_sdo_ipc_heaps_HeapMultiBufMP_Struct ti_sdo_ipc_heaps_HeapMultiBufMP_Struct;
typedef ti_sdo_ipc_heaps_HeapMultiBufMP_Object* ti_sdo_ipc_heaps_HeapMultiBufMP_Handle;
typedef struct ti_sdo_ipc_heaps_HeapMultiBufMP_Object__ ti_sdo_ipc_heaps_HeapMultiBufMP_Instance_State;
typedef ti_sdo_ipc_heaps_HeapMultiBufMP_Object* ti_sdo_ipc_heaps_HeapMultiBufMP_Instance;

/*
 * ======== module ti.sdo.ipc.heaps.HeapMemMP ========
 */

typedef struct ti_sdo_ipc_heaps_HeapMemMP_ExtendedStats ti_sdo_ipc_heaps_HeapMemMP_ExtendedStats;
typedef struct ti_sdo_ipc_heaps_HeapMemMP_Header ti_sdo_ipc_heaps_HeapMemMP_Header;
typedef struct ti_sdo_ipc_heaps_HeapMemMP_Attrs ti_sdo_ipc_heaps_HeapMemMP_Attrs;
typedef struct ti_sdo_ipc_heaps_HeapMemMP_Module_State ti_sdo_ipc_heaps_HeapMemMP_Module_State;
typedef struct ti_sdo_ipc_heaps_HeapMemMP_Fxns__ ti_sdo_ipc_heaps_HeapMemMP_Fxns__;
typedef const struct ti_sdo_ipc_heaps_HeapMemMP_Fxns__* ti_sdo_ipc_heaps_HeapMemMP_Module;
typedef struct ti_sdo_ipc_heaps_HeapMemMP_Params ti_sdo_ipc_heaps_HeapMemMP_Params;
typedef struct ti_sdo_ipc_heaps_HeapMemMP_Object ti_sdo_ipc_heaps_HeapMemMP_Object;
typedef struct ti_sdo_ipc_heaps_HeapMemMP_Struct ti_sdo_ipc_heaps_HeapMemMP_Struct;
typedef ti_sdo_ipc_heaps_HeapMemMP_Object* ti_sdo_ipc_heaps_HeapMemMP_Handle;
typedef struct ti_sdo_ipc_heaps_HeapMemMP_Object__ ti_sdo_ipc_heaps_HeapMemMP_Instance_State;
typedef ti_sdo_ipc_heaps_HeapMemMP_Object* ti_sdo_ipc_heaps_HeapMemMP_Instance;


#endif /* ti_sdo_ipc_heaps__ */ 
