# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_calc_determinant_tensor_matrix
TEST_BENCH = $(FILE)_tb
CFILES = ../src_C/$(FILE)_cn.c
#Below File name is Optional to specify . Default name is a.exe
HOSTFILES += $(KERNELFILES)
HOST_EXE_FILE_NAME = vcop_calc_determinant_tensor_matrix_tb.exe 
include ../../../common/Makefile.wincommon
