# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_sum_grad_cross_inter_frame_diff_7x7
TEST_BENCH = $(FILE)_tb
CFILES = ../src_C/$(FILE)_cn.c
#Below File name is Optional to specify . Default name is a.exe
HOST_EXE_FILE_NAME = vcop_sum_grad_cross_inter_frame_diff_7x7_tb.exe 
include ../../../common/Makefile.wincommon
