# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/

FILE = vcop_rgb_srgb
TEST_BENCH = $(FILE)_tb
include ../../../common/Makefile.wincommon

