# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_alpha_blend_yuv422i
TEST_BENCH = $(FILE)_tb
CFILES = ../src_kernelC/$(FILE)_host.c

include ../../../common/Makefile.wincommon
