/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-A71
 */

#ifndef ti_sysbios_family_arm_a8_intcps_Hwi__INTERNAL__
#define ti_sysbios_family_arm_a8_intcps_Hwi__INTERNAL__

#ifndef ti_sysbios_family_arm_a8_intcps_Hwi__internalaccess
#define ti_sysbios_family_arm_a8_intcps_Hwi__internalaccess
#endif

#include <ti/sysbios/family/arm/a8/intcps/Hwi.h>

#undef xdc_FILE__
#ifndef xdc_FILE
#define xdc_FILE__ NULL
#else
#define xdc_FILE__ xdc_FILE
#endif

/* getStackInfo */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_getStackInfo
#define ti_sysbios_family_arm_a8_intcps_Hwi_getStackInfo ti_sysbios_family_arm_a8_intcps_Hwi_getStackInfo__E

/* getCoreStackInfo */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_getCoreStackInfo
#define ti_sysbios_family_arm_a8_intcps_Hwi_getCoreStackInfo ti_sysbios_family_arm_a8_intcps_Hwi_getCoreStackInfo__E

/* startup */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_startup
#define ti_sysbios_family_arm_a8_intcps_Hwi_startup ti_sysbios_family_arm_a8_intcps_Hwi_startup__E

/* switchFromBootStack */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_switchFromBootStack
#define ti_sysbios_family_arm_a8_intcps_Hwi_switchFromBootStack ti_sysbios_family_arm_a8_intcps_Hwi_switchFromBootStack__E

/* getTaskSP */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_getTaskSP
#define ti_sysbios_family_arm_a8_intcps_Hwi_getTaskSP ti_sysbios_family_arm_a8_intcps_Hwi_getTaskSP__E

/* disableInterrupt */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_disableInterrupt
#define ti_sysbios_family_arm_a8_intcps_Hwi_disableInterrupt ti_sysbios_family_arm_a8_intcps_Hwi_disableInterrupt__E

/* enableInterrupt */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_enableInterrupt
#define ti_sysbios_family_arm_a8_intcps_Hwi_enableInterrupt ti_sysbios_family_arm_a8_intcps_Hwi_enableInterrupt__E

/* restoreInterrupt */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_restoreInterrupt
#define ti_sysbios_family_arm_a8_intcps_Hwi_restoreInterrupt ti_sysbios_family_arm_a8_intcps_Hwi_restoreInterrupt__E

/* clearInterrupt */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_clearInterrupt
#define ti_sysbios_family_arm_a8_intcps_Hwi_clearInterrupt ti_sysbios_family_arm_a8_intcps_Hwi_clearInterrupt__E

/* getFunc */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_getFunc
#define ti_sysbios_family_arm_a8_intcps_Hwi_getFunc ti_sysbios_family_arm_a8_intcps_Hwi_getFunc__E

/* setFunc */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_setFunc
#define ti_sysbios_family_arm_a8_intcps_Hwi_setFunc ti_sysbios_family_arm_a8_intcps_Hwi_setFunc__E

/* getHookContext */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_getHookContext
#define ti_sysbios_family_arm_a8_intcps_Hwi_getHookContext ti_sysbios_family_arm_a8_intcps_Hwi_getHookContext__E

/* setHookContext */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_setHookContext
#define ti_sysbios_family_arm_a8_intcps_Hwi_setHookContext ti_sysbios_family_arm_a8_intcps_Hwi_setHookContext__E

/* getIrp */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_getIrp
#define ti_sysbios_family_arm_a8_intcps_Hwi_getIrp ti_sysbios_family_arm_a8_intcps_Hwi_getIrp__E

/* post */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_post
#define ti_sysbios_family_arm_a8_intcps_Hwi_post ti_sysbios_family_arm_a8_intcps_Hwi_post__E

/* clearPostedInterrupt */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_clearPostedInterrupt
#define ti_sysbios_family_arm_a8_intcps_Hwi_clearPostedInterrupt ti_sysbios_family_arm_a8_intcps_Hwi_clearPostedInterrupt__E

/* getHandle */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_getHandle
#define ti_sysbios_family_arm_a8_intcps_Hwi_getHandle ti_sysbios_family_arm_a8_intcps_Hwi_getHandle__E

/* enableFIQ */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_enableFIQ
#define ti_sysbios_family_arm_a8_intcps_Hwi_enableFIQ ti_sysbios_family_arm_a8_intcps_Hwi_enableFIQ__E

/* disableFIQ */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_disableFIQ
#define ti_sysbios_family_arm_a8_intcps_Hwi_disableFIQ ti_sysbios_family_arm_a8_intcps_Hwi_disableFIQ__E

/* restoreFIQ */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_restoreFIQ
#define ti_sysbios_family_arm_a8_intcps_Hwi_restoreFIQ ti_sysbios_family_arm_a8_intcps_Hwi_restoreFIQ__E

/* enableIRQ */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_enableIRQ
#define ti_sysbios_family_arm_a8_intcps_Hwi_enableIRQ ti_sysbios_family_arm_a8_intcps_Hwi_enableIRQ__E

/* disableIRQ */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_disableIRQ
#define ti_sysbios_family_arm_a8_intcps_Hwi_disableIRQ ti_sysbios_family_arm_a8_intcps_Hwi_disableIRQ__E

/* restoreIRQ */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_restoreIRQ
#define ti_sysbios_family_arm_a8_intcps_Hwi_restoreIRQ ti_sysbios_family_arm_a8_intcps_Hwi_restoreIRQ__E

/* disableMIR0 */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_disableMIR0
#define ti_sysbios_family_arm_a8_intcps_Hwi_disableMIR0 ti_sysbios_family_arm_a8_intcps_Hwi_disableMIR0__E

/* disableMIR1 */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_disableMIR1
#define ti_sysbios_family_arm_a8_intcps_Hwi_disableMIR1 ti_sysbios_family_arm_a8_intcps_Hwi_disableMIR1__E

/* disableMIR2 */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_disableMIR2
#define ti_sysbios_family_arm_a8_intcps_Hwi_disableMIR2 ti_sysbios_family_arm_a8_intcps_Hwi_disableMIR2__E

/* disableMIR3 */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_disableMIR3
#define ti_sysbios_family_arm_a8_intcps_Hwi_disableMIR3 ti_sysbios_family_arm_a8_intcps_Hwi_disableMIR3__E

/* enableMIR0 */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_enableMIR0
#define ti_sysbios_family_arm_a8_intcps_Hwi_enableMIR0 ti_sysbios_family_arm_a8_intcps_Hwi_enableMIR0__E

/* enableMIR1 */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_enableMIR1
#define ti_sysbios_family_arm_a8_intcps_Hwi_enableMIR1 ti_sysbios_family_arm_a8_intcps_Hwi_enableMIR1__E

/* enableMIR2 */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_enableMIR2
#define ti_sysbios_family_arm_a8_intcps_Hwi_enableMIR2 ti_sysbios_family_arm_a8_intcps_Hwi_enableMIR2__E

/* enableMIR3 */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_enableMIR3
#define ti_sysbios_family_arm_a8_intcps_Hwi_enableMIR3 ti_sysbios_family_arm_a8_intcps_Hwi_enableMIR3__E

/* restoreMIR0 */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_restoreMIR0
#define ti_sysbios_family_arm_a8_intcps_Hwi_restoreMIR0 ti_sysbios_family_arm_a8_intcps_Hwi_restoreMIR0__E

/* restoreMIR1 */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_restoreMIR1
#define ti_sysbios_family_arm_a8_intcps_Hwi_restoreMIR1 ti_sysbios_family_arm_a8_intcps_Hwi_restoreMIR1__E

/* restoreMIR2 */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_restoreMIR2
#define ti_sysbios_family_arm_a8_intcps_Hwi_restoreMIR2 ti_sysbios_family_arm_a8_intcps_Hwi_restoreMIR2__E

/* restoreMIR3 */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_restoreMIR3
#define ti_sysbios_family_arm_a8_intcps_Hwi_restoreMIR3 ti_sysbios_family_arm_a8_intcps_Hwi_restoreMIR3__E

/* setPriority */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_setPriority
#define ti_sysbios_family_arm_a8_intcps_Hwi_setPriority ti_sysbios_family_arm_a8_intcps_Hwi_setPriority__E

/* setType */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_setType
#define ti_sysbios_family_arm_a8_intcps_Hwi_setType ti_sysbios_family_arm_a8_intcps_Hwi_setType__E

/* reconfig */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_reconfig
#define ti_sysbios_family_arm_a8_intcps_Hwi_reconfig ti_sysbios_family_arm_a8_intcps_Hwi_reconfig__E

/* postInit */
#define Hwi_postInit ti_sysbios_family_arm_a8_intcps_Hwi_postInit__I

/* initIntController */
#define Hwi_initIntController ti_sysbios_family_arm_a8_intcps_Hwi_initIntController__I

/* init */
#define Hwi_init ti_sysbios_family_arm_a8_intcps_Hwi_init__I

/* initVbar */
#define Hwi_initVbar ti_sysbios_family_arm_a8_intcps_Hwi_initVbar__I

/* dispatchIRQ */
#define Hwi_dispatchIRQ ti_sysbios_family_arm_a8_intcps_Hwi_dispatchIRQ__I

/* dispatchIRQC */
#define Hwi_dispatchIRQC ti_sysbios_family_arm_a8_intcps_Hwi_dispatchIRQC__I

/* dispatchFIQC */
#define Hwi_dispatchFIQC ti_sysbios_family_arm_a8_intcps_Hwi_dispatchFIQC__I

/* nonPluggedHwiHandler */
#define Hwi_nonPluggedHwiHandler ti_sysbios_family_arm_a8_intcps_Hwi_nonPluggedHwiHandler__I

/* Module_startup */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_Module_startup
#define ti_sysbios_family_arm_a8_intcps_Hwi_Module_startup ti_sysbios_family_arm_a8_intcps_Hwi_Module_startup__E

/* Instance_init */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_Instance_init
#define ti_sysbios_family_arm_a8_intcps_Hwi_Instance_init ti_sysbios_family_arm_a8_intcps_Hwi_Instance_init__E

/* Instance_finalize */
#undef ti_sysbios_family_arm_a8_intcps_Hwi_Instance_finalize
#define ti_sysbios_family_arm_a8_intcps_Hwi_Instance_finalize ti_sysbios_family_arm_a8_intcps_Hwi_Instance_finalize__E

/* module */
#define Hwi_module ((ti_sysbios_family_arm_a8_intcps_Hwi_Module_State *)(xdc__MODOBJADDR__(ti_sysbios_family_arm_a8_intcps_Hwi_Module__state__V)))
#if !defined(__cplusplus) || !defined(ti_sysbios_family_arm_a8_intcps_Hwi__cplusplus)
#define module ((ti_sysbios_family_arm_a8_intcps_Hwi_Module_State *)(xdc__MODOBJADDR__(ti_sysbios_family_arm_a8_intcps_Hwi_Module__state__V)))
#endif
/* per-module runtime symbols */
#undef Module__MID
#define Module__MID ti_sysbios_family_arm_a8_intcps_Hwi_Module__id__C
#undef Module__DGSINCL
#define Module__DGSINCL ti_sysbios_family_arm_a8_intcps_Hwi_Module__diagsIncluded__C
#undef Module__DGSENAB
#define Module__DGSENAB ti_sysbios_family_arm_a8_intcps_Hwi_Module__diagsEnabled__C
#undef Module__DGSMASK
#define Module__DGSMASK ti_sysbios_family_arm_a8_intcps_Hwi_Module__diagsMask__C
#undef Module__LOGDEF
#define Module__LOGDEF ti_sysbios_family_arm_a8_intcps_Hwi_Module__loggerDefined__C
#undef Module__LOGOBJ
#define Module__LOGOBJ ti_sysbios_family_arm_a8_intcps_Hwi_Module__loggerObj__C
#undef Module__LOGFXN0
#define Module__LOGFXN0 ti_sysbios_family_arm_a8_intcps_Hwi_Module__loggerFxn0__C
#undef Module__LOGFXN1
#define Module__LOGFXN1 ti_sysbios_family_arm_a8_intcps_Hwi_Module__loggerFxn1__C
#undef Module__LOGFXN2
#define Module__LOGFXN2 ti_sysbios_family_arm_a8_intcps_Hwi_Module__loggerFxn2__C
#undef Module__LOGFXN4
#define Module__LOGFXN4 ti_sysbios_family_arm_a8_intcps_Hwi_Module__loggerFxn4__C
#undef Module__LOGFXN8
#define Module__LOGFXN8 ti_sysbios_family_arm_a8_intcps_Hwi_Module__loggerFxn8__C
#undef Module__G_OBJ
#define Module__G_OBJ ti_sysbios_family_arm_a8_intcps_Hwi_Module__gateObj__C
#undef Module__G_PRMS
#define Module__G_PRMS ti_sysbios_family_arm_a8_intcps_Hwi_Module__gatePrms__C
#undef Module__GP_create
#define Module__GP_create ti_sysbios_family_arm_a8_intcps_Hwi_Module_GateProxy_create
#undef Module__GP_delete
#define Module__GP_delete ti_sysbios_family_arm_a8_intcps_Hwi_Module_GateProxy_delete
#undef Module__GP_enter
#define Module__GP_enter ti_sysbios_family_arm_a8_intcps_Hwi_Module_GateProxy_enter
#undef Module__GP_leave
#define Module__GP_leave ti_sysbios_family_arm_a8_intcps_Hwi_Module_GateProxy_leave
#undef Module__GP_query
#define Module__GP_query ti_sysbios_family_arm_a8_intcps_Hwi_Module_GateProxy_query

/* Object__sizingError */
#line 1 "Error_inconsistent_object_size_in_ti.sysbios.family.arm.a8.intcps.Hwi"
typedef char ti_sysbios_family_arm_a8_intcps_Hwi_Object__sizingError[sizeof(ti_sysbios_family_arm_a8_intcps_Hwi_Object) > sizeof(ti_sysbios_family_arm_a8_intcps_Hwi_Struct) ? -1 : 1];


#endif /* ti_sysbios_family_arm_a8_intcps_Hwi__INTERNAL____ */
