/****************************************************************************
Copyright (c) [2012 - 2017] Texas Instruments Incorporated

All rights reserved not granted herein.

Limited License.

 Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
 license under copyrights and patents it now or hereafter owns or controls to
 make,  have made, use, import, offer to sell and sell ('Utilize') this software
 subject to the terms herein.  With respect to the foregoing patent license,
 such license is granted  solely to the extent that any such patent is necessary
 to Utilize the software alone.  The patent license shall not apply to any
 combinations which include this software, other than combinations with devices
 manufactured by or for TI ('TI Devices').  No hardware patent is licensed
 hereunder.

 Redistributions must preserve existing copyright notices and reproduce this
 license (including the above copyright notice and the disclaimer and
 (if applicable) source code license limitations below) in the documentation
 and/or other materials provided with the distribution

 Redistribution and use in binary form, without modification, are permitted
 provided that the following conditions are met:

 * No reverse engineering, decompilation, or disassembly of this software
   is permitted with respect to any software provided in binary form.

 * Any redistribution and use are licensed by TI for use only with TI Devices.

 * Nothing shall obligate TI to provide you with source code for the software
   licensed and provided to you in object code.

 If software source code is provided to you, modification and redistribution of
 the source code are permitted provided that the following conditions are met:

 * Any redistribution and use of the source code, including any resulting
   derivative works, are licensed by TI for use only with TI Devices.

 * Any redistribution and use of any object code compiled from the source code
   and any resulting derivative works, are licensed by TI for use only with TI
   Devices.

 Neither the name of Texas Instruments Incorporated nor the names of its
 suppliers may be used to endorse or promote products derived from this software
 without specific prior written permission.

 DISCLAIMER.

 THIS SOFTWARE IS PROVIDED BY TI AND TI’S LICENSORS 'AS IS' AND ANY EXPRESS OR
 IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 IN NO EVENT SHALL TI AND TI’S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
******************************************************************************
*/
/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/
#include "chains_issMultCaptIspSimcop_Stereo_priv.h"
Void chains_issMultCaptIspSimcop_Stereo_SetLinkId(chains_issMultCaptIspSimcop_StereoObj *pObj){
       pObj->IssCaptureLinkID               = SYSTEM_LINK_ID_ISSCAPTURE_0;
       pObj->IssM2mIspLinkID                = SYSTEM_LINK_ID_ISSM2MISP_0;
       pObj->Alg_IssAewbLinkID              = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_1);
       pObj->IssM2mResizer_CaptureLinkID    = SYSTEM_LINK_ID_ISS_RESIZER_0;
       pObj->Select_CaptureLinkID           = IPU1_0_LINK (SYSTEM_LINK_ID_SELECT_0);
       pObj->IssM2mSimcopLinkID             = SYSTEM_LINK_ID_ISSM2MSIMCOP_0;
       pObj->Merge_SimcopLinkID             = IPU1_0_LINK (SYSTEM_LINK_ID_MERGE_0);
       pObj->Dup_SimcopLinkID               = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_0);
       pObj->Sync_CensusInLinkID            = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_1);
       pObj->Dup_CensusInLinkID             = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_1);
       pObj->IPCOut_IPU1_0_EVE1_0LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_EVE1_IPU1_0_0LinkID      = EVE1_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_CensusLinkID               = EVE1_LINK (SYSTEM_LINK_ID_ALG_1);
       pObj->Alg_DisparityHamDistLinkID     = EVE1_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_EVE1_IPU1_0_0LinkID     = EVE1_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_IPU1_0_EVE1_0LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Merge_StereoOutLinkID          = IPU1_0_LINK (SYSTEM_LINK_ID_MERGE_1);
       pObj->IPCOut_IPU1_0_DSP1_1LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_1);
       pObj->IPCIn_DSP1_IPU1_0_0LinkID      = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_StereoPostProcessLinkID    = DSP1_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_DSP1_IPU1_0_0LinkID     = DSP1_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_IPU1_0_DSP1_1LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_1);
       pObj->Display_DisparityLinkID        = SYSTEM_LINK_ID_DISPLAY_0;
       pObj->Sync_OrgLinkID                 = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_0);
       pObj->Alg_DmaSwMsLinkID              = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->Display_OrgLinkID              = SYSTEM_LINK_ID_DISPLAY_1;
       pObj->GrpxSrcLinkID                  = IPU1_0_LINK (SYSTEM_LINK_ID_GRPX_SRC_0);
       pObj->Display_GrpxLinkID             = SYSTEM_LINK_ID_DISPLAY_2;
}

Void chains_issMultCaptIspSimcop_Stereo_ResetLinkPrms(chains_issMultCaptIspSimcop_StereoObj *pObj){
       IssCaptureLink_CreateParams_Init(&pObj->IssCapturePrm);
       IssM2mIspLink_CreateParams_Init(&pObj->IssM2mIspPrm);
       AlgorithmLink_IssAewb_Init(&pObj->Alg_IssAewbPrm);
       IssRszLink_CreateParams_Init(&pObj->IssM2mResizer_CapturePrm);
       SelectLink_CreateParams_Init(&pObj->Select_CapturePrm);
       IssM2mSimcopLink_CreateParams_Init(&pObj->IssM2mSimcopPrm);
       MergeLink_CreateParams_Init(&pObj->Merge_SimcopPrm);
       DupLink_CreateParams_Init(&pObj->Dup_SimcopPrm);
       SyncLink_CreateParams_Init(&pObj->Sync_CensusInPrm);
       DupLink_CreateParams_Init(&pObj->Dup_CensusInPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_EVE1_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_EVE1_IPU1_0_0Prm);
       AlgorithmLink_Census_Init(&pObj->Alg_CensusPrm);
       AlgorithmLink_DisparityHamDist_Init(&pObj->Alg_DisparityHamDistPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_EVE1_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_EVE1_0Prm);
       MergeLink_CreateParams_Init(&pObj->Merge_StereoOutPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_DSP1_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_IPU1_0_0Prm);
       AlgorithmLink_StereoPostProcess_Init(&pObj->Alg_StereoPostProcessPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP1_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_DSP1_1Prm);
       DisplayLink_CreateParams_Init(&pObj->Display_DisparityPrm);
       SyncLink_CreateParams_Init(&pObj->Sync_OrgPrm);
       AlgorithmLink_DmaSwMsCreateParams_Init(&pObj->Alg_DmaSwMsPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_OrgPrm);
       GrpxSrcLink_CreateParams_Init(&pObj->GrpxSrcPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_GrpxPrm);
}

Void chains_issMultCaptIspSimcop_Stereo_SetPrms(chains_issMultCaptIspSimcop_StereoObj *pObj){
       (pObj->Alg_IssAewbPrm).baseClassCreate.size  = sizeof(AlgorithmLink_IssAewbCreateParams);
       (pObj->Alg_IssAewbPrm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_ISS_AEWB1;
       (pObj->Select_CapturePrm).numOutQue = 2;
       (pObj->IssM2mSimcopPrm).numInQue = 1;
       (pObj->Merge_SimcopPrm).numInQue = 2;
       (pObj->Dup_SimcopPrm).numOutQue = 2;
       (pObj->Dup_CensusInPrm).numOutQue = 2;
       (pObj->Alg_CensusPrm).baseClassCreate.size  = sizeof(AlgorithmLink_CensusCreateParams);
       (pObj->Alg_CensusPrm).baseClassCreate.algId  = ALGORITHM_LINK_EVE_ALG_CENSUS;
       (pObj->Alg_DisparityHamDistPrm).baseClassCreate.size  = sizeof(AlgorithmLink_DisparityHamDistCreateParams);
       (pObj->Alg_DisparityHamDistPrm).baseClassCreate.algId  = ALGORITHM_LINK_EVE_ALG_DISPARITY_HAMDIST;
       (pObj->Merge_StereoOutPrm).numInQue = 2;
       (pObj->Alg_StereoPostProcessPrm).baseClassCreate.size  = sizeof(AlgorithmLink_StereoPostProcessCreateParams);
       (pObj->Alg_StereoPostProcessPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_STEREO_POST_PROCESS;
       (pObj->Alg_DmaSwMsPrm).baseClassCreate.size  = sizeof(AlgorithmLink_DmaSwMsCreateParams);
       (pObj->Alg_DmaSwMsPrm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_DMA_SWMS;
}

Void chains_issMultCaptIspSimcop_Stereo_ConnectLinks(chains_issMultCaptIspSimcop_StereoObj *pObj){

       //IssCapture -> IssM2mIsp
       pObj->IssCapturePrm.outQueParams.nextLink = pObj->IssM2mIspLinkID;
       pObj->IssM2mIspPrm.inQueParams[0].prevLinkId = pObj->IssCaptureLinkID;
       pObj->IssM2mIspPrm.inQueParams[0].prevLinkQueId = 0;

       //IssM2mIsp -> IssM2mResizer_Capture
       pObj->IssM2mIspPrm.outQueParams[0].nextLink = pObj->IssM2mResizer_CaptureLinkID;
       pObj->IssM2mResizer_CapturePrm.inQueParams.prevLinkId = pObj->IssM2mIspLinkID;
       pObj->IssM2mResizer_CapturePrm.inQueParams.prevLinkQueId = 0;

       //IssM2mIsp -> Alg_IssAewb
       pObj->IssM2mIspPrm.outQueParams[1].nextLink = pObj->Alg_IssAewbLinkID;
       pObj->Alg_IssAewbPrm.inQueParams.prevLinkId = pObj->IssM2mIspLinkID;
       pObj->Alg_IssAewbPrm.inQueParams.prevLinkQueId = 1;

       //IssM2mResizer_Capture -> Select_Capture
       pObj->IssM2mResizer_CapturePrm.outQueParams[0].nextLink = pObj->Select_CaptureLinkID;
       pObj->Select_CapturePrm.inQueParams.prevLinkId = pObj->IssM2mResizer_CaptureLinkID;
       pObj->Select_CapturePrm.inQueParams.prevLinkQueId = 0;

       //Select_Capture -> IssM2mSimcop
       pObj->Select_CapturePrm.outQueParams[0].nextLink = pObj->IssM2mSimcopLinkID;
       pObj->IssM2mSimcopPrm.inQueParams[0].prevLinkId = pObj->Select_CaptureLinkID;
       pObj->IssM2mSimcopPrm.inQueParams[0].prevLinkQueId = 0;

       //Select_Capture -> Merge_Simcop
       pObj->Select_CapturePrm.outQueParams[1].nextLink = pObj->Merge_SimcopLinkID;
       pObj->Merge_SimcopPrm.inQueParams[1].prevLinkId = pObj->Select_CaptureLinkID;
       pObj->Merge_SimcopPrm.inQueParams[1].prevLinkQueId = 1;

       //IssM2mSimcop -> Merge_Simcop
       pObj->IssM2mSimcopPrm.outQueParams.nextLink = pObj->Merge_SimcopLinkID;
       pObj->Merge_SimcopPrm.inQueParams[0].prevLinkId = pObj->IssM2mSimcopLinkID;
       pObj->Merge_SimcopPrm.inQueParams[0].prevLinkQueId = 0;

       //Merge_Simcop -> Dup_Simcop
       pObj->Merge_SimcopPrm.outQueParams.nextLink = pObj->Dup_SimcopLinkID;
       pObj->Dup_SimcopPrm.inQueParams.prevLinkId = pObj->Merge_SimcopLinkID;
       pObj->Dup_SimcopPrm.inQueParams.prevLinkQueId = 0;

       //Dup_Simcop -> Sync_Org
       pObj->Dup_SimcopPrm.outQueParams[0].nextLink = pObj->Sync_OrgLinkID;
       pObj->Sync_OrgPrm.inQueParams.prevLinkId = pObj->Dup_SimcopLinkID;
       pObj->Sync_OrgPrm.inQueParams.prevLinkQueId = 0;

       //Dup_Simcop -> Sync_CensusIn
       pObj->Dup_SimcopPrm.outQueParams[1].nextLink = pObj->Sync_CensusInLinkID;
       pObj->Sync_CensusInPrm.inQueParams.prevLinkId = pObj->Dup_SimcopLinkID;
       pObj->Sync_CensusInPrm.inQueParams.prevLinkQueId = 1;

       //Sync_CensusIn -> Dup_CensusIn
       pObj->Sync_CensusInPrm.outQueParams.nextLink = pObj->Dup_CensusInLinkID;
       pObj->Dup_CensusInPrm.inQueParams.prevLinkId = pObj->Sync_CensusInLinkID;
       pObj->Dup_CensusInPrm.inQueParams.prevLinkQueId = 0;

       //Dup_CensusIn -> IPCOut_IPU1_0_EVE1_0
       pObj->Dup_CensusInPrm.outQueParams[0].nextLink = pObj->IPCOut_IPU1_0_EVE1_0LinkID;
       pObj->IPCOut_IPU1_0_EVE1_0Prm.inQueParams.prevLinkId = pObj->Dup_CensusInLinkID;
       pObj->IPCOut_IPU1_0_EVE1_0Prm.inQueParams.prevLinkQueId = 0;

       //Dup_CensusIn -> Merge_StereoOut
       pObj->Dup_CensusInPrm.outQueParams[1].nextLink = pObj->Merge_StereoOutLinkID;
       pObj->Merge_StereoOutPrm.inQueParams[1].prevLinkId = pObj->Dup_CensusInLinkID;
       pObj->Merge_StereoOutPrm.inQueParams[1].prevLinkQueId = 1;

       //IPCOut_IPU1_0_EVE1_0 -> IPCIn_EVE1_IPU1_0_0
       pObj->IPCOut_IPU1_0_EVE1_0Prm.outQueParams.nextLink = pObj->IPCIn_EVE1_IPU1_0_0LinkID;
       pObj->IPCIn_EVE1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_EVE1_0LinkID;
       pObj->IPCIn_EVE1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_EVE1_IPU1_0_0 -> Alg_Census
       pObj->IPCIn_EVE1_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_CensusLinkID;
       pObj->Alg_CensusPrm.inQueParams.prevLinkId = pObj->IPCIn_EVE1_IPU1_0_0LinkID;
       pObj->Alg_CensusPrm.inQueParams.prevLinkQueId = 0;

       //Alg_Census -> Alg_DisparityHamDist
       pObj->Alg_CensusPrm.outQueParams.nextLink = pObj->Alg_DisparityHamDistLinkID;
       pObj->Alg_DisparityHamDistPrm.inQueParams.prevLinkId = pObj->Alg_CensusLinkID;
       pObj->Alg_DisparityHamDistPrm.inQueParams.prevLinkQueId = 0;

       //Alg_DisparityHamDist -> IPCOut_EVE1_IPU1_0_0
       pObj->Alg_DisparityHamDistPrm.outQueParams.nextLink = pObj->IPCOut_EVE1_IPU1_0_0LinkID;
       pObj->IPCOut_EVE1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->Alg_DisparityHamDistLinkID;
       pObj->IPCOut_EVE1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_EVE1_IPU1_0_0 -> IPCIn_IPU1_0_EVE1_0
       pObj->IPCOut_EVE1_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_EVE1_0LinkID;
       pObj->IPCIn_IPU1_0_EVE1_0Prm.inQueParams.prevLinkId = pObj->IPCOut_EVE1_IPU1_0_0LinkID;
       pObj->IPCIn_IPU1_0_EVE1_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_EVE1_0 -> Merge_StereoOut
       pObj->IPCIn_IPU1_0_EVE1_0Prm.outQueParams.nextLink = pObj->Merge_StereoOutLinkID;
       pObj->Merge_StereoOutPrm.inQueParams[0].prevLinkId = pObj->IPCIn_IPU1_0_EVE1_0LinkID;
       pObj->Merge_StereoOutPrm.inQueParams[0].prevLinkQueId = 0;

       //Merge_StereoOut -> IPCOut_IPU1_0_DSP1_1
       pObj->Merge_StereoOutPrm.outQueParams.nextLink = pObj->IPCOut_IPU1_0_DSP1_1LinkID;
       pObj->IPCOut_IPU1_0_DSP1_1Prm.inQueParams.prevLinkId = pObj->Merge_StereoOutLinkID;
       pObj->IPCOut_IPU1_0_DSP1_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_IPU1_0_DSP1_1 -> IPCIn_DSP1_IPU1_0_0
       pObj->IPCOut_IPU1_0_DSP1_1Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_IPU1_0_0LinkID;
       pObj->IPCIn_DSP1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_DSP1_1LinkID;
       pObj->IPCIn_DSP1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP1_IPU1_0_0 -> Alg_StereoPostProcess
       pObj->IPCIn_DSP1_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_StereoPostProcessLinkID;
       pObj->Alg_StereoPostProcessPrm.inQueParams.prevLinkId = pObj->IPCIn_DSP1_IPU1_0_0LinkID;
       pObj->Alg_StereoPostProcessPrm.inQueParams.prevLinkQueId = 0;

       //Alg_StereoPostProcess -> IPCOut_DSP1_IPU1_0_0
       pObj->Alg_StereoPostProcessPrm.outQueParams[0].nextLink = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
       pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->Alg_StereoPostProcessLinkID;
       pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_DSP1_IPU1_0_0 -> IPCIn_IPU1_0_DSP1_1
       pObj->IPCOut_DSP1_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_DSP1_1LinkID;
       pObj->IPCIn_IPU1_0_DSP1_1Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
       pObj->IPCIn_IPU1_0_DSP1_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_DSP1_1 -> Display_Disparity
       pObj->IPCIn_IPU1_0_DSP1_1Prm.outQueParams.nextLink = pObj->Display_DisparityLinkID;
       pObj->Display_DisparityPrm.inQueParams.prevLinkId = pObj->IPCIn_IPU1_0_DSP1_1LinkID;
       pObj->Display_DisparityPrm.inQueParams.prevLinkQueId = 0;

       //Sync_Org -> Alg_DmaSwMs
       pObj->Sync_OrgPrm.outQueParams.nextLink = pObj->Alg_DmaSwMsLinkID;
       pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkId = pObj->Sync_OrgLinkID;
       pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkQueId = 0;

       //Alg_DmaSwMs -> Display_Org
       pObj->Alg_DmaSwMsPrm.outQueParams.nextLink = pObj->Display_OrgLinkID;
       pObj->Display_OrgPrm.inQueParams.prevLinkId = pObj->Alg_DmaSwMsLinkID;
       pObj->Display_OrgPrm.inQueParams.prevLinkQueId = 0;

       //GrpxSrc -> Display_Grpx
       pObj->GrpxSrcPrm.outQueParams.nextLink = pObj->Display_GrpxLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkId = pObj->GrpxSrcLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkQueId = 0;

}

Int32 chains_issMultCaptIspSimcop_Stereo_Create(chains_issMultCaptIspSimcop_StereoObj *pObj, Void *appObj){

       Int32 status;

       chains_issMultCaptIspSimcop_Stereo_SetLinkId(pObj);
       chains_issMultCaptIspSimcop_Stereo_ResetLinkPrms(pObj);

       chains_issMultCaptIspSimcop_Stereo_SetPrms(pObj);
       chains_issMultCaptIspSimcop_Stereo_SetAppPrms(pObj, appObj);

       chains_issMultCaptIspSimcop_Stereo_ConnectLinks(pObj);
       status = System_linkCreate(pObj->IssCaptureLinkID, &pObj->IssCapturePrm, sizeof(pObj->IssCapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IssM2mIspLinkID, &pObj->IssM2mIspPrm, sizeof(pObj->IssM2mIspPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_IssAewbLinkID, &pObj->Alg_IssAewbPrm, sizeof(pObj->Alg_IssAewbPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IssM2mResizer_CaptureLinkID, &pObj->IssM2mResizer_CapturePrm, sizeof(pObj->IssM2mResizer_CapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Select_CaptureLinkID, &pObj->Select_CapturePrm, sizeof(pObj->Select_CapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IssM2mSimcopLinkID, &pObj->IssM2mSimcopPrm, sizeof(pObj->IssM2mSimcopPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Merge_SimcopLinkID, &pObj->Merge_SimcopPrm, sizeof(pObj->Merge_SimcopPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_SimcopLinkID, &pObj->Dup_SimcopPrm, sizeof(pObj->Dup_SimcopPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_CensusInLinkID, &pObj->Sync_CensusInPrm, sizeof(pObj->Sync_CensusInPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_CensusInLinkID, &pObj->Dup_CensusInPrm, sizeof(pObj->Dup_CensusInPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_EVE1_0LinkID, &pObj->IPCOut_IPU1_0_EVE1_0Prm, sizeof(pObj->IPCOut_IPU1_0_EVE1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_EVE1_IPU1_0_0LinkID, &pObj->IPCIn_EVE1_IPU1_0_0Prm, sizeof(pObj->IPCIn_EVE1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_CensusLinkID, &pObj->Alg_CensusPrm, sizeof(pObj->Alg_CensusPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DisparityHamDistLinkID, &pObj->Alg_DisparityHamDistPrm, sizeof(pObj->Alg_DisparityHamDistPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_EVE1_IPU1_0_0LinkID, &pObj->IPCOut_EVE1_IPU1_0_0Prm, sizeof(pObj->IPCOut_EVE1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_EVE1_0LinkID, &pObj->IPCIn_IPU1_0_EVE1_0Prm, sizeof(pObj->IPCIn_IPU1_0_EVE1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Merge_StereoOutLinkID, &pObj->Merge_StereoOutPrm, sizeof(pObj->Merge_StereoOutPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_DSP1_1LinkID, &pObj->IPCOut_IPU1_0_DSP1_1Prm, sizeof(pObj->IPCOut_IPU1_0_DSP1_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP1_IPU1_0_0LinkID, &pObj->IPCIn_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCIn_DSP1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_StereoPostProcessLinkID, &pObj->Alg_StereoPostProcessPrm, sizeof(pObj->Alg_StereoPostProcessPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP1_IPU1_0_0LinkID, &pObj->IPCOut_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCOut_DSP1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_DSP1_1LinkID, &pObj->IPCIn_IPU1_0_DSP1_1Prm, sizeof(pObj->IPCIn_IPU1_0_DSP1_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_DisparityLinkID, &pObj->Display_DisparityPrm, sizeof(pObj->Display_DisparityPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_OrgLinkID, &pObj->Sync_OrgPrm, sizeof(pObj->Sync_OrgPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DmaSwMsLinkID, &pObj->Alg_DmaSwMsPrm, sizeof(pObj->Alg_DmaSwMsPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_OrgLinkID, &pObj->Display_OrgPrm, sizeof(pObj->Display_OrgPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->GrpxSrcLinkID, &pObj->GrpxSrcPrm, sizeof(pObj->GrpxSrcPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_GrpxLinkID, &pObj->Display_GrpxPrm, sizeof(pObj->Display_GrpxPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_issMultCaptIspSimcop_Stereo_Start(chains_issMultCaptIspSimcop_StereoObj *pObj){

       Int32 status;

       status = System_linkStart(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_OrgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_OrgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_DisparityLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_StereoPostProcessLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Merge_StereoOutLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DisparityHamDistLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_CensusLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_CensusInLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_CensusInLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_SimcopLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Merge_SimcopLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IssM2mSimcopLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Select_CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IssM2mResizer_CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_IssAewbLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IssM2mIspLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IssCaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_issMultCaptIspSimcop_Stereo_Stop(chains_issMultCaptIspSimcop_StereoObj *pObj){

       Int32 status;

       status = System_linkStop(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_OrgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_OrgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_DisparityLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_StereoPostProcessLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Merge_StereoOutLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DisparityHamDistLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_CensusLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_CensusInLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_CensusInLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_SimcopLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Merge_SimcopLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IssM2mSimcopLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Select_CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IssM2mResizer_CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_IssAewbLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IssM2mIspLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IssCaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_issMultCaptIspSimcop_Stereo_Delete(chains_issMultCaptIspSimcop_StereoObj *pObj){

       Int32 status;

       status = System_linkDelete(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_OrgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_OrgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_DisparityLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_StereoPostProcessLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Merge_StereoOutLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DisparityHamDistLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_CensusLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_CensusInLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_CensusInLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_SimcopLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Merge_SimcopLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IssM2mSimcopLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Select_CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IssM2mResizer_CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_IssAewbLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IssM2mIspLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IssCaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Void chains_issMultCaptIspSimcop_Stereo_printBufferStatistics(chains_issMultCaptIspSimcop_StereoObj *pObj){
       System_linkPrintBufferStatistics(pObj->IssCaptureLinkID);
       System_linkPrintBufferStatistics(pObj->IssM2mIspLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_IssAewbLinkID);
       System_linkPrintBufferStatistics(pObj->IssM2mResizer_CaptureLinkID);
       System_linkPrintBufferStatistics(pObj->Select_CaptureLinkID);
       System_linkPrintBufferStatistics(pObj->IssM2mSimcopLinkID);
       System_linkPrintBufferStatistics(pObj->Merge_SimcopLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_SimcopLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_CensusInLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_CensusInLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_CensusLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DisparityHamDistLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_EVE1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_EVE1_0LinkID);
       System_linkPrintBufferStatistics(pObj->Merge_StereoOutLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_StereoPostProcessLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_DSP1_1LinkID);
       System_linkPrintBufferStatistics(pObj->Display_DisparityLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_OrgLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DmaSwMsLinkID);
       System_linkPrintBufferStatistics(pObj->Display_OrgLinkID);
       System_linkPrintBufferStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintBufferStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

Void chains_issMultCaptIspSimcop_Stereo_printStatistics(chains_issMultCaptIspSimcop_StereoObj *pObj){
       System_linkPrintStatistics(pObj->IssCaptureLinkID);
       System_linkPrintStatistics(pObj->IssM2mIspLinkID);
       System_linkPrintStatistics(pObj->Alg_IssAewbLinkID);
       System_linkPrintStatistics(pObj->IssM2mResizer_CaptureLinkID);
       System_linkPrintStatistics(pObj->Select_CaptureLinkID);
       System_linkPrintStatistics(pObj->IssM2mSimcopLinkID);
       System_linkPrintStatistics(pObj->Merge_SimcopLinkID);
       System_linkPrintStatistics(pObj->Dup_SimcopLinkID);
       System_linkPrintStatistics(pObj->Sync_CensusInLinkID);
       System_linkPrintStatistics(pObj->Dup_CensusInLinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_CensusLinkID);
       System_linkPrintStatistics(pObj->Alg_DisparityHamDistLinkID);
       System_linkPrintStatistics(pObj->IPCOut_EVE1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_EVE1_0LinkID);
       System_linkPrintStatistics(pObj->Merge_StereoOutLinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_StereoPostProcessLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_DSP1_1LinkID);
       System_linkPrintStatistics(pObj->Display_DisparityLinkID);
       System_linkPrintStatistics(pObj->Sync_OrgLinkID);
       System_linkPrintStatistics(pObj->Alg_DmaSwMsLinkID);
       System_linkPrintStatistics(pObj->Display_OrgLinkID);
       System_linkPrintStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

