/*
 *  Copyright (C) 2016 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 *  \file stw_qspiTestcases.h
 *
 *  \brief This file defines the test cases for QSPI UT.
 */

#ifndef STW_QSPI_TEST_CASES_H_
#define STW_QSPI_TEST_CASES_H_

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
#include <st_qspi.h>
#include <st_qspiConfig.h>

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */
#define QSPI_NUM_TESTCASES   (sizeof (gQSPITestcaseParams) / \
                               sizeof (st_QSPITestcaseParams_t))

#define USE_DEF_LP_CNT        (DEF_LOOP_CNT)

/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/** \brief Defines the various QSPI test cases. */
static st_QSPITestcaseParams_t gQSPITestcaseParams[] =
{
    /* enableTest, testCaseId,
     * testCaseFxnPtr,
     * *reqId,
     * *testCaseName,
     * *userInfo,
     * *disableReason,
     * *passFailCriteria
     * printEnable,
     * testType,
     * loopCnt,
     * st_QspiTestCfgPrms,
     */
    {
        TEST_ENABLE, 0U,
        &st_qspiTest_quickFlash,
        ":PDK-96:PDK-472:PDK-476:PDK-479:PDK-482:PDK-483:PDK-1440:PDK-1441:PDK-1446:PDK-1448:PDK-1449:PDK-1450:PDK-1451:PDK-1492:PDK-62:PDK-101:PDK-473:",
        "QSPI-1 Quick Flash Test with Memory Map Mode Disable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 1U,
        &st_qspiTest_quickFlash,
        ":PDK-477:PDK-474:PDK-475:PDK-485:PDK-487:PDK-1452:PDK-1454:PDK-1455:PDK-1456:PDK-1457:PDK-1461:PDK-1462:PDK-1464:PDK-1465:PDK-1466:PDK-1473:PDK-1474:",
        "QSPI-1 Quick Flash with Memory Map Mode Enable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 2U,
        &st_qspiTest_fullFlash,
        ":PDK-1475:PDK-1476:PDK-1477:PDK-484:PDK-486:",
        "QSPI-1 Full Flash Test with Memory Map Mode Enable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_FULL | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_FULL_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 3U,
        &st_qspiTest_quickFlash,
        ":PDK-480:PDK-475:PDK-1463:PDK-1468:PDK-1475:",
        "QSPI-4 Quick Flash Test with Memory Map Mode Disable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 4U,
        &st_qspiTest_quickFlash,
        ":PDK-480:PDK-1443:PDK-475:PDK-1475:",
        "QSPI-4 Quick Flash Test with Memory Map Mode Enable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 5U,
        &st_qspiTest_fullFlash,
        ":PDK-480:PDK-484:PDK-486:",
        "QSPI-4 Full Flash Test",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_FULL | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_FULL_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 6U,
        &st_qspiTest_quickFlash,
        ":PDK-1452:",
        "QSPI-1 Quick Flash Test with Read and write Data Width as 8bit",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            8U,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 7U,
        &st_qspiTest_quickFlash,
        ":PDK-1452:",
        "QSPI-4 Quick Flash Test with Read and Write Data Width as 16bit",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            16U,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 8U,
        &st_qspiTest_quickFlash,
        ":PDK-1452:",
        "QSPI-1 Quick Flash Test with Read and write Data Width as 32bit",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            32U,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 9U,
        &st_qspiTest_quickFlash,
        ":PDK-1452:",
        "QSPI-4 Quick Flash Test with Read and Write Data Width as 64bit",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            64U,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 10U,
        &st_qspiTest_quickFlash,
        ":PDK-1452:",
        "QSPI-1 Quick Flash Test with Read and write Data Width as 128bit",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            128U,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 11U,
        &st_qspiTest_quickFlash,
        ":PDK-1452:",
        "QSPI-1 Quick Flash Test with Read and Write Data Width as 120bit",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            120U,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 12U,
        &st_qspiTest_quickFlash,
        ":PDK-1469:PDK-1458:",
        "QSPI-1 Quick Flash Test with clock Mode as 0 and clock frequency as 12MHz",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_12MHz,
            ST_QSPI_CLK_MODE_0,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 13U,
        &st_qspiTest_quickFlash,
        ":PDK-1469:PDK-1458:",
        "QSPI-4 Quick Flash Test with clock Mode as 0 and clock frequency as 16MHz",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_16MHz,
            ST_QSPI_CLK_MODE_0,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 14U,
        &st_qspiTest_quickFlash,
        ":PDK-1469:PDK-1458:",
        "QSPI-1 Quick Flash Test with clock Mode as 0 and clock frequency as 24MHz",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_24MHz,
            ST_QSPI_CLK_MODE_0,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 15U,
        &st_qspiTest_quickFlash,
        ":PDK-1469:PDK-1458:",
        "QSPI-4 Quick Flash Test with clock Mode as 0 and clock frequency as 32MHz",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_32MHz,
            ST_QSPI_CLK_MODE_0,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 16U,
        &st_qspiTest_quickFlash,
        ":PDK-1469:PDK-1458:",
        "QSPI-1 Quick Flash Test with clock Mode as 0 and clock frequency as 48MHz",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_48MHz,
            ST_QSPI_CLK_MODE_0,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 17U,
        &st_qspiTest_quickFlash,
        ":PDK-1491:PDK-1458:",
        "QSPI-4 Quick Flash Test with clock Mode as 0 and clock frequency as 96MHz",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_96MHz,
            ST_QSPI_CLK_MODE_0,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 18U,
        &st_qspiTest_quickFlash,
        ":PDK-1459:PDK-1470:",
        "QSPI-1 Quick Flash Test with clock Mode as 3 and clock frequency as 12MHz",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_12MHz,
            ST_QSPI_CLK_MODE_3,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 19U,
        &st_qspiTest_quickFlash,
        ":PDK-1459:PDK-1470:",
        "QSPI-4 Quick Flash Test with clock Mode as 3 and clock frequency as 16MHz",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_16MHz,
            ST_QSPI_CLK_MODE_3,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 20U,
        &st_qspiTest_quickFlash,
        ":PDK-1459:PDK-1470:",
        "QSPI-1 Quick Flash Test with clock Mode as 3 and clock frequency as 24MHz",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_24MHz,
            ST_QSPI_CLK_MODE_3,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 21U,
        &st_qspiTest_quickFlash,
        ":PDK-1459:PDK-1470:",
        "QSPI-4 Quick Flash Test with clock Mode as 3 and clock frequency as 32MHz",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_32MHz,
            ST_QSPI_CLK_MODE_3,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 22U,
        &st_qspiTest_quickFlash,
        ":PDK-1459:PDK-1470:",
        "QSPI-1 Quick Flash Test with clock Mode as 3 and clock frequency as 48MHz",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_48MHz,
            ST_QSPI_CLK_MODE_3,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 23U,
        &st_qspiTest_quickFlash,
        ":PDK-1459:PDK-1490:",
        "QSPI-4 Quick Flash Test with clock Mode as 3 and clock frequency as 64MHz",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_64MHz,
            ST_QSPI_CLK_MODE_3,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 24U,
        &st_qspiTest_quickFlash,
        ":PDK-1445:PDK-1709:",
        "QSPI-1 Quick Flash Test with Fast read",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_48MHz,
            ST_QSPI_CLK_MODE_0,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_FASTREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 25U,
        &st_qspiTest_quickFlash,
        ":PDK-481:PDK-1442:PDK-1467:",
        "QSPI-1 Quick Flash with Dual Read",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_48MHz,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            2U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 26U,
        &st_qspiTest_quickFlash,
        ":PDK-1468:PDK-1475:",
        "QSPI-4 Quick Flash with Quad Read",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_48MHz,
            ST_QSPI_CLK_MODE_0,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 27U,
        &st_qspiTest_quickFlash,
        ":PDK-478:",
        "QSPI-1 Quick Flash Test with QSPI Read using EDMA",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            ST_QSPI_DMA_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 28U,
        &st_qspiTest_fullFlash,
        ":PDK-478:",
        "QSPI-1 Full Flash Test with QSPI Read using EDMA",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_FULL | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_FULL_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            ST_QSPI_DMA_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 29U,
        &st_qspiTest_quickFlash,
        ":PDK-478:",
        "QSPI-4 Quick Flash Test with QSPI Read using EDMA",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            ST_QSPI_DMA_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 30U,
        &st_qspiTest_fullFlash,
        ":PDK-478:",
        "QSPI-4 Full Flash Test with QSPI Read using EDMA",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_FULL | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_FULL_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            ST_QSPI_DMA_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 31U,
        &st_qspiTest_quickFlash_Interrupt,
        ":PDK-1460:PDK-1471:PDK-1472:PDK-1489:",
        "QSPI-1 Quick Flash Test with Interrupt Enable for WC & FC",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            32U,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            TRUE,
            TRUE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 32U,
        &st_qspiTest_quickFlash_Interrupt,
        ":PDK-1460:PDK-1471:PDK-1472:PDK-1489:",
        "QSPI-1 Quick Flash Test with Interrupt Enable for WC",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            32U,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            TRUE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 33U,
        &st_qspiTest_quickFlash_Interrupt,
        ":PDK-1460:PDK-1471:PDK-1472:PDK-1489:",
        "QSPI-1 Quick Flash Test with Interrupt Enable for FC",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            32U,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            TRUE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 34U,
        &st_qspiTest_quickFlash_Interrupt,
        ":PDK-1472:PDK-1489:",
        "QSPI-1 Quick Flash Test with Interrupt Disable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            32U,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 35U,
        &st_qspiTest_quickFlash,
        ":PDK-1444:PDK-1446:",
        "QSPI-4 Quick Flash Test with Custom Device Type & Memory Map Mode Disable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_CUSTOM,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 36U,
        &st_qspiTest_quickFlash,
        ":PDK-1444:PDK-1446:",
        "QSPI-4 Quick Flash Test with Custom Device Type & Memory Map Mode Enable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_CUSTOM,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 37U,
        &st_qspiTest_quickFlash,
        ":PDK-1444:PDK-1446:",
        "QSPI-2 Quick Flash Test with Custom Device Type & Memory Map Mode Disable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_CUSTOM,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            2U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 38U,
        &st_qspiTest_quickFlash,
        ":PDK-1444:PDK-1446:",
        "QSPI-2 Quick Flash Test with Custom Device Type & Memory Map Mode Enable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_CUSTOM,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            2U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 39U,
        &st_qspiTest_quickFlash,
        ":PDK-1444:PDK-1446:",
        "QSPI-1 Quick Flash Test with Custom Device Type & Memory Map Mode Disable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_CUSTOM,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 40U,
        &st_qspiTest_quickFlash,
        ":PDK-1444:PDK-1446:",
        "QSPI-1 Quick Flash Test with Custom Device Type & Memory Map Mode Enable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_CUSTOM,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {/* Read Data using EDMA for full flash size : fails at end*/
        TEST_DISABLE, 41U,
        &st_qspiTest_fullFlash_Test,
        "None",
        "QSPI-1 Full Flash Test",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_FULL | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_FULL_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    /*
     * API Related Testcases for coverage
     */
    {
        TEST_ENABLE, 100U,
        &st_qspiTest_GetMemMapCfg,
        ":PDK-476:",
        "QSPI-1: Get Memory Map Setup register configuration for coverage",
        "None",
        "None",
        "Check for configured cmd is correct or not",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_API,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            QSPI_SCLK_FREQ_48MHz,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DREAD,
            },
        },
    },
    /*
     * Negative Testcases
     */
    {
        TEST_ENABLE, 150U,
        &st_qspiTest_WrNullDataCheck,
        ":PDK-476:",
        "QSPI-1 Flash Test for Null Write Data Ptr for coverage",
        "None",
        "None",
        "Error needs to be detected and reported",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_NEGATIVE,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            32U,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 151U,
        &st_qspiTest_RdNullDataCheck,
        ":PDK-476:",
        "QSPI-1 Flash Test for Null Read Data Ptr for coverage",
        "None",
        "None",
        "Error needs to be detected and reported",
        PRINT_ENABLE,
        ST_TT_REGRESSION | ST_TT_NEGATIVE,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_DEFAULT_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            32U,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    /*
     * Stress Testcases
     */
    {
        TEST_ENABLE, 200U,
        &st_qspiTest_quickFlash,
        ":PDK-476:PDK-1492:",
        "QSPI-1 Quick Flash Test with Memory Map Mode Disable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_FULL | ST_TT_STRESS,
        50U,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 201U,
        &st_qspiTest_quickFlash,
        ":PDK-476:PDK-1492:",
        "QSPI-1 Quick Flash with Memory Map Mode Enable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_FULL | ST_TT_STRESS,
        50U,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 202U,
        &st_qspiTest_fullFlash,
        ":PDK-476:PDK-1492:",
        "QSPI-1 Full Flash Test with Memory Map Mode Enable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_FULL | ST_TT_STRESS,
        10U,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_FULL_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 203U,
        &st_qspiTest_quickFlash,
        ":PDK-476:PDK-1492:",
        "QSPI-4 Quick Flash Test with Memory Map Mode Disable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_FULL | ST_TT_STRESS,
        50U,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 204U,
        &st_qspiTest_quickFlash,
        ":PDK-476:PDK-1492:",
        "QSPI-4 Quick Flash Test with Memory Map Mode Enable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_FULL | ST_TT_STRESS,
        50U,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 205U,
        &st_qspiTest_fullFlash,
        ":PDK-476:PDK-1492:",
        "QSPI-4 Full Flash Test",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_FULL | ST_TT_STRESS,
        10U,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI4,
            ST_QSPI_FULL_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_ENABLE,
            DEF_DATA_WIDTH,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            4U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_QREAD,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
    {
        TEST_ENABLE, 300U,
        &st_qspiTest_RdCorruptionCheckFor16BitData,
        ":PDK-2818:",
        "QSPI-1 Flash Read Test to check corruption as reported in PDK-2818 with Memory Map Mode Enable",
        "None",
        "None",
        "QSPI Read and Write should happen and verify for data match",
        PRINT_ENABLE,
        ST_TT_SANITY | ST_TT_FUNCTIONAL,
        USE_DEF_LP_CNT,
        {
            ST_QSPI_TEST_TYPE_QUICK,
            DEVICE_TYPE_QSPI1,
            ST_QSPI_BLOCK_ERASE,
            DEF_ERASE_BLOCK_NO,
            DEF_ERASE_SECTOR_NO,
            ST_QSPI_FLASH_BLOCK_SIZE,
            DEF_OFFSET_ADDR,
            MEM_MAP_MODE_DISABLE,
            16U,
            DEF_CLK_FREQUENCY,
            DEF_CLK_MODE,
            DEF_DATA_TRANSFER_MODE,
            1U,
            FALSE,
            FALSE,
            {
                ST_QSPI_FLASH_IDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_RDCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_SUBSECTERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_FULLERASECMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_STATCMD_CFGID_DEFAULT,
            },
            {
                ST_QSPI_FLASH_WRENCMD_CFGID_DEFAULT,
            },
        },
    },
};

#endif /* #ifndef ST_UART_TEST_CASES_H_ */
